### ISSUE TITLE
Getting information about a folder overwritten by a file gives 500 error instead of 404

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#1239] opened 2020-07-21 05:16 UTC
## Description: 
There are scenarios where a file(say testfile.txt) is copied over the top of an existing folder(say FOLDER), which overwrites the folder. The folder changes into the file and the name is of the folder(FOLDER). When we try to find if the actual folder(FOLDER) exists for the user, then 500 Internal server error is returned instead of 404 Not Found. However, if we check for the completely non-existence folder, which was never created, then it returns 404 correctly.

## Steps To Reproduce: 
1. Create User `Alice`
2. Alice creates a file `testfile.txt` with content `some data`

```
curl -u Alice:1234 -X PUT "http://localhost:9140/remote.php/webdav/testfile.txt" -d "some data" -v                                                  

< HTTP/1.1 201 Created

```
3. Alice creates folder `FOLDER`
```
curl -u Alice:1234 -X MKCOL "http://localhost:9140/remote.php/webdav/FOLDER" -v                                                                       

< HTTP/1.1 201 Created

```

4. Alice creates folder `FOLDER/sample-folder`

```
curl -u Alice:1234 -X MKCOL "http://localhost:9140/remote.php/webdav/FOLDER/sample-folder" -v                                                         

< HTTP/1.1 201 Created

```
5. Alice copies file `testfile.txt` to `FOLDER` using webdav API
```
curl -u Alice:1234 -X COPY "http://localhost:9140/remote.php/webdav/testfile.txt" -H "Destination: http://localhost:9140/remote.php/webdav/FOLDER" -v 

< HTTP/1.1 204 No Content

```
6. Alice checks the content of file `FOLDER`
```
curl -u Alice:1234 -X GET "http://localhost:9140/remote.php/webdav/FOLDER" -v                                                                      

< HTTP/1.1 200 OK

some data%                                    
```
7. Alice checks if folder `FOLDER/sample-folder` exists
```
curl -u Alice:1234 -X GET "http://localhost:9140/remote.php/webdav/FOLDER/sample-folder" -v


< HTTP/1.1 500 Internal Server Error

```

8. But when Alice checks for a folder `Non-existent-folder` which was never created
```
 curl -u Alice:1234 -X GET "http://localhost:9140/remote.php/webdav/Not-Existent-Folder" -v 

< HTTP/1.1 404 Not Found

```

**Comment by ScharfViktor** [comment] 2021-08-31 14:50
Perhaps something has changed. Getting information about a folder using the GET method always gives `HTTP/1.1 501 Not Implemented` question: should it work correctly in this case?


server log:
`21-08-31T16:41:28+02:00 WRN resource is a folder and cannot be downloaded handler=get path=/home/1/2 pkg=rhttp service=storage svc=ocdav traceid=4cfe3d3412acac1417f7e4be6986155d
2021-08-31T16:41:28+02:00 ERR http end="31/Aug/2021:16:41:28 +0200" host=::1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=0 start="31/Aug/2021:16:41:28 +0200" status=501 time_ns=52276458 traceid=4cfe3d3412acac1417f7e4be6986155d uri=/remote.php/webdav/1/2 url=/remote.php/webdav/1/2`

question: should it work correctly in this case?

method `curl -X PROPFIND "http://localhost:9140/remote.php/webdav/1/1"` works to get information about the folder

**Comment by SagarGi** [comment] 2022-08-12 04:57
The above bug seems to have been fixed and the expected to failure for `ocis` that has been tag with this issue is irrelevant to this but acts differently than `oc10` when we copy the file on the top of an existing folder.

**Comment by kiranparajuli589** [comment] 2022-08-15 06:51
@SagarGi if the issue is not relevant further, please close it with the proper current behavior in a comment. The expected failure files also need an update regarding the scenarios linked with these issues.

**Comment by amrita-shrestha** [comment] 2023-08-08 08:23
RE-TESTED As @SagarGi mentioned this issue has been resolved but the issue exists in expected-failure file and need to remove

**Closed by amrita-shrestha** 2023-08-08 08:23 UTC
Labels: Type:Bug, Interaction:Needs-help

**Comment by amrita-shrestha** [comment] 2023-08-22 07:34
@SwikritiT 
- [ ] backport to stable
