### ISSUE TITLE
ldap.crt/ldap.key certiticate expired OCIS 5.0.7

### ISSUE THREAD

**Issue by scarmonar** [owncloud/ocis#10140] opened 2024-09-23 14:44 UTC
## Describe the bug
On 19th September the internal LDAP/IDM certificate expired and OCIS didnt renewd it automaticatly, so we receive "Unexpected HTTP response: 500. Please check your connection and try again." when we try to log in. 

Removing ldap.crt/ldap.key from /var/lib/ocis/idm/ and restarting the server solve the problem.

## Steps to reproduce
1. 
2.
3.

## Expected behavior
Certificate should be automatically renewed

## Actual behavior
The certificate was not renewed so we cannot log into OCIS. 

## Setup
Docker Compose

<details>
<p>

```console
networks:
  traefik_network:
    external: true

################### SECRETS ################
secrets:
  serv_acc_id: 
    file: ./secrets/SERVICE_ACCOUNT_ID
    
################### SERVICIOS ##############
services:
########## OCIS ###############
  ocis:
    container_name: ocis_server
    image: owncloud/ocis:5.0.7
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    networks:
      - traefik_network
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    #ports:
    #    - 9200:9200
    healthcheck: 
      test: "ocis graph health"
      interval: 15s
      timeout: 2s
      retries: 5
      start_period: 60s
    environment:
      TZ: $TZ
      OCIS_URL: https://nube.$DOMAINNAME
      OCIS_LOG_LEVEL: info
      OCIS_LOG_COLOR: true
      PROXY_TLS: false # do not use SSL between Traefik and oCIS
      OCIS_INSECURE: false
      PROXY_ENABLE_BASIC_AUTH: false
      #PROXY_INSECURE_BACKENDS: false
      IDM_ADMIN_PASSWORD: XXXXXXX
      FRONTEND_AUTO_ACCEPT_SHARES: true
      ###### MODIFICACIONES A LA WEB
      WEB_OPTION_DISABLE_FEEDBACK_LINK: true
      WEB_UI_THEME_SERVER: https://nube.$DOMAINNAME
      WEB_UI_THEME_PATH: /themes/theme.json
      GRAPH_ASSIGN_DEFAULT_USER_ROLE: false
      GRAPH_USERNAME_MATCH: none
      OCIS_SERVICE_ACCOUNT_ID: xxxxxxxxxxxxxxxxxxxx
      OCIS_SERVICE_ACCOUNT_SECRET: xxxxxxxxxxxxxx
      OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
      FRONTEND_DEFAULT_LINK_PERMISSIONS: 1
    volumes:
      - type: bind
        source: /media/DiscoD/ocis/ocis-config
        target: /etc/ocis
      - type: bind
        source: /media/DiscoD/ocis/ocis-data
        target: /var/lib/ocis
    labels:
      traefik.enable: true
      traefik.http.routers.ocis-rtr.tls: true
      traefik.http.routers.ocis-rtr.entrypoints: websecure
      traefik.http.routers.ocis-rtr.rule: Host(`nube.${DOMAINNAME}`)
      #traefik.http.routers.ocis-rtr.middlewares=chain-no-auth@file ## App no puede descargar si se activa, revisar. 
      traefik.http.routers.ocis-rtr.tls.certresolver: tls-resolver
      traefik.http.routers.ocis-rtr.service: ocis-svc
      traefik.http.services.ocis-svc.loadbalancer.server.port: 9200
```

</p>
</details>

**Comment by rhafer** [comment] 2024-09-23 15:21
duplicate of #8552

**Closed by rhafer** 2024-09-23 15:21 UTC
Labels: Type:Bug
