### ISSUE TITLE
Configuration report

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#2672] opened 2021-10-25 06:28 UTC
## Is your feature request related to a problem? Please describe.
As ownCloud support I want to have an easy / uniform way for people to report their oCIS configuration.

## Describe the solution you'd like
There is a command that reports the configuration of oCIS. This also includes the count and configuration of each extension running.

## Describe alternatives you've considered
- 

## Additional context
In the single-binary use case it should be quite easy. But it should also support a spread / multi services deployment.

**Comment by jvillafanez** [comment] 2021-11-19 14:30
A specific configuration service might make sense; it should be easy for a client to query that service, and the rest of the services could get their configuration from there. It seems a lot of work though.

Assuming we still want each service to manage its own configuration, we need a way for a client to get the service's configuration. The main idea is to use protobuf definitions so the service can send the configuration via grpc and http (code is expected to be automatically generated from the protobuf definition)

There are some challenges found so far:
* Protobuf definition must be shared because the way we'll ask for the configuration to each service is expected to be the same.
  * I guess the definition should be placed somewhere inside the ocis-pkg folder
  * The code should be generated inside each service that will answer the "getConfig" request
* API call should be homogeneous.
* We'll need to get a list of services that are able to respond to the request.

**Comment by jvillafanez** [comment] 2022-01-25 12:06
> Protobuf definition must be shared because the way we'll ask for the configuration to each service is expected to be the same.
    I guess the definition should be placed somewhere inside the ocis-pkg folder
    The code should be generated inside each service that will answer the "getConfig" request

This is taken care with the protobuf refactor done in https://github.com/owncloud/ocis/pull/2960

> API call should be homogeneous.

The plan is to create a "/protogen/proto/ocis/services/config/v1/config.proto" file (and the associated messages) with the service definition. All the microservices are expected to implement that service.

> We'll need to get a list of services that are able to respond to the request.

go-micro's registry can take care of this. For each service we can get all the endpoints as well as information about the parameters. Although not fail-proof, we can know what services we can get the configuration information from.

For services that don't implement the interface, we'll have to either log something or show an error to notice that we can't get the configuration from that service.

go-micro's registry also offers information about the nodes, so we probably should include part of it as part of the config report. Knowing there are 2 or more nodes could be useful if we need to debug problems.

-----

Additional notes:
* Need to figure out how to extract the configuration information. The code is expected to be the same for all the services, so the ocis-pkg folder seems to be a good place to add the code for the extraction and formatting.
* Thumbnails microservice seems to require a refactor for the service registration. Accounts, store and settings microservices are easier to modify in order to implement this new config service

**Comment by jvillafanez** [comment] 2022-02-08 10:03
We'll need to decide on the output format and the information we want to show.
For testing purposes, only the thumbnail service is sending its configuration. The rest either aren't sending anything, or don't have the service implemented.

Possible configuration formats:

### full JSON
A JSON with a list containing the report of each service
```
[
  {
    "Name": "com.owncloud.web.web",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.web-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9100",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.api.store",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.api.store-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9460",
        "Metadata": {
          "broker": "http",
          "protocol": "grpc",
          "registry": "mdns",
          "server": "grpc",
          "transport": "grpc"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.graph.graph",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.graph.graph-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9120",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.web.settings",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.settings-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9190",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.web.graph-explorer",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.graph-explorer-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9135",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.api.settings",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.api.settings-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9191",
        "Metadata": {
          "broker": "http",
          "protocol": "grpc",
          "registry": "mdns",
          "server": "grpc",
          "transport": "grpc"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.storage.metadata",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.storage.metadata-68e77308-5356-406d-bd71-cd5a1ff1f1c6",
        "Addr": "127.0.0.1:9215",
        "Metadata": {
          "broker": "http",
          "protocol": "grpc",
          "registry": "mdns",
          "server": "grpc",
          "transport": "grpc"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.web.idp",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.idp-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9130",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.api.thumbnails",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.api.thumbnails-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9185",
        "Metadata": {
          "broker": "http",
          "protocol": "grpc",
          "registry": "mdns",
          "server": "grpc",
          "transport": "grpc"
        }
      }
    ],
    "Config": {
      "GRPC.Addr": "127.0.0.1:9185",
      "GRPC.Namespace": "com.owncloud.api",
      "Log.Color": "false",
      "Log.File": "",
      "Log.Level": "debug",
      "Log.Pretty": "false",
      "Service.Name": "thumbnails",
      "Thumbnail.CS3AllowInsecure": "true",
      "Thumbnail.FileSystemStorage.RootDirectory": "/root/.ocis/thumbnails",
      "Thumbnail.FontMapFile": "",
      "Thumbnail.Resolutions": "16x16,32x32,64x64,128x128,1920x1080,3840x2160,7680x4320",
      "Thumbnail.RevaGateway": "127.0.0.1:9142",
      "Thumbnail.WebdavAllowInsecure": "true",
      "Tracing.Collector": "",
      "Tracing.Enabled": "false",
      "Tracing.Endpoint": "",
      "Tracing.Type": ""
    }
  },
  {
    "Name": "com.owncloud.web.proxy",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.proxy-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "172.17.0.2:9200",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.storage",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.storage-4570e679-f3ca-44dd-a765-18b4a8258c01",
        "Addr": "127.0.0.1:9142",
        "Metadata": {
          "broker": "http",
          "protocol": "grpc",
          "registry": "mdns",
          "server": "grpc",
          "transport": "grpc"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.web.accounts",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.accounts-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9181",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.web.ocs",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.ocs-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9110",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.api.accounts",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.api.accounts-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9180",
        "Metadata": {
          "broker": "http",
          "protocol": "grpc",
          "registry": "mdns",
          "server": "grpc",
          "transport": "grpc"
        }
      }
    ],
    "Config": null
  },
  {
    "Name": "com.owncloud.web.webdav",
    "Version": "1310b573b",
    "Nodes": [
      {
        "Id": "com.owncloud.web.webdav-e13ee552-09dc-40cf-b885-ab2d34b5a3d5",
        "Addr": "127.0.0.1:9115",
        "Metadata": {
          "broker": "http",
          "protocol": "http",
          "registry": "mdns",
          "server": "http"
        }
      }
    ],
    "Config": null
  }
]
```
* Advantages:
  * Easy to parse
* Disadvantages:
  * Need to figure out how to show errors:
    * Some of the microservices above don't implement the config service, so we can't know their configuration.
    * Other microservices implement the config service, but aren't responding (or send an empty response)
  * In a local environment, it takes 2 secs to show the information. It might be worse if it needs external services. There is no activity indicator meanwhile.

-------

### Microservice-based JSON
For each microservice, a JSON object holding the report will be printed
```
{
  "Name": "com.owncloud.api.store",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.api.store-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9460",
      "Metadata": {
        "broker": "http",
        "protocol": "grpc",
        "registry": "mdns",
        "server": "grpc",
        "transport": "grpc"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.api.settings",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.api.settings-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9191",
      "Metadata": {
        "broker": "http",
        "protocol": "grpc",
        "registry": "mdns",
        "server": "grpc",
        "transport": "grpc"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.web.idp",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.idp-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9130",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.web.proxy",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.proxy-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "172.17.0.2:9200",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.api.thumbnails",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.api.thumbnails-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9185",
      "Metadata": {
        "broker": "http",
        "protocol": "grpc",
        "registry": "mdns",
        "server": "grpc",
        "transport": "grpc"
      }
    }
  ],
  "Config": {
    "GRPC.Addr": "127.0.0.1:9185",
    "GRPC.Namespace": "com.owncloud.api",
    "Log.Color": "false",
    "Log.File": "",
    "Log.Level": "debug",
    "Log.Pretty": "false",
    "Service.Name": "thumbnails",
    "Thumbnail.CS3AllowInsecure": "true",
    "Thumbnail.FileSystemStorage.RootDirectory": "/root/.ocis/thumbnails",
    "Thumbnail.FontMapFile": "",
    "Thumbnail.Resolutions": "16x16,32x32,64x64,128x128,1920x1080,3840x2160,7680x4320",
    "Thumbnail.RevaGateway": "127.0.0.1:9142",
    "Thumbnail.WebdavAllowInsecure": "true",
    "Tracing.Collector": "",
    "Tracing.Enabled": "false",
    "Tracing.Endpoint": "",
    "Tracing.Type": ""
  }
}
{
  "Name": "com.owncloud.web.accounts",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.accounts-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9181",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.web.ocs",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.ocs-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9110",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.api.accounts",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.api.accounts-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9180",
      "Metadata": {
        "broker": "http",
        "protocol": "grpc",
        "registry": "mdns",
        "server": "grpc",
        "transport": "grpc"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.storage",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.storage-c7ca48d9-558a-46cd-bf05-e5af516a608e",
      "Addr": "127.0.0.1:9142",
      "Metadata": {
        "broker": "http",
        "protocol": "grpc",
        "registry": "mdns",
        "server": "grpc",
        "transport": "grpc"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.web.webdav",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.webdav-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9115",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.web.web",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.web-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9100",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.graph.graph",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.graph.graph-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9120",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.web.graph-explorer",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.graph-explorer-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9135",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.storage.metadata",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.storage.metadata-bd3935ed-2671-486c-ad0e-6ec823951991",
      "Addr": "127.0.0.1:9215",
      "Metadata": {
        "broker": "http",
        "protocol": "grpc",
        "registry": "mdns",
        "server": "grpc",
        "transport": "grpc"
      }
    }
  ],
  "Config": null
}
{
  "Name": "com.owncloud.web.settings",
  "Version": "1310b573b",
  "Nodes": [
    {
      "Id": "com.owncloud.web.settings-44ad73e4-a3bd-472f-823c-ff3d59488c6b",
      "Addr": "127.0.0.1:9190",
      "Metadata": {
        "broker": "http",
        "protocol": "http",
        "registry": "mdns",
        "server": "http"
      }
    }
  ],
  "Config": null
}
```
* Advantages:
  * We can start printing info as soon as we get the information of the first microservice. This is usually fast, and we don't need to wait X seconds thinking if the command is doing anything or has been stuck.
  * Each piece can be parsed.
* Disadvantages:
  * The whole data can't be parsed by itself, because it isn't a valid JSON object by itself.
  * Need to figure out how to show errors:
    * Some of the microservices above don't implement the config service, so we can't know their configuration.
    * Other microservices implement the config service, but aren't responding (or send an empty response)

------

### Custom format
Information from each microservice is visually separated, and it's indented to be easier to read
```
com.owncloud.web.web:1310b573b
  Nodes:
    com.owncloud.web.web-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9100
      registry = mdns
      server = http
      broker = http
      protocol = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.settings:1310b573b
  Nodes:
    com.owncloud.web.settings-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9190
      broker = http
      protocol = http
      registry = mdns
      server = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.api.settings:1310b573b
  Nodes:
    com.owncloud.api.settings-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9191
      protocol = grpc
      registry = mdns
      server = grpc
      transport = grpc
      broker = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.ocs:1310b573b
  Nodes:
    com.owncloud.web.ocs-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9110
      broker = http
      protocol = http
      registry = mdns
      server = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.api.store:1310b573b
  Nodes:
    com.owncloud.api.store-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9460
      broker = http
      protocol = grpc
      registry = mdns
      server = grpc
      transport = grpc
  Configuration:
    Couldn't get the configuration
-------
com.owncloud.api.thumbnails:1310b573b
  Nodes:
    com.owncloud.api.thumbnails-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9185
      broker = http
      protocol = grpc
      registry = mdns
      server = grpc
      transport = grpc
  Configuration:
    GRPC.Addr = 127.0.0.1:9185
    GRPC.Namespace = com.owncloud.api
    Log.Color = false
    Log.File = 
    Log.Level = debug
    Log.Pretty = false
    Service.Name = thumbnails
    Thumbnail.CS3AllowInsecure = true
    Thumbnail.FileSystemStorage.RootDirectory = /root/.ocis/thumbnails
    Thumbnail.FontMapFile = 
    Thumbnail.Resolutions = 16x16,32x32,64x64,128x128,1920x1080,3840x2160,7680x4320
    Thumbnail.RevaGateway = 127.0.0.1:9142
    Thumbnail.WebdavAllowInsecure = true
    Tracing.Collector = 
    Tracing.Enabled = false
    Tracing.Endpoint = 
    Tracing.Type = 
-------
com.owncloud.graph.graph:1310b573b
  Nodes:
    com.owncloud.graph.graph-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9120
      broker = http
      protocol = http
      registry = mdns
      server = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.graph-explorer:1310b573b
  Nodes:
    com.owncloud.web.graph-explorer-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9135
      protocol = http
      registry = mdns
      server = http
      broker = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.storage.metadata:1310b573b
  Nodes:
    com.owncloud.storage.metadata-bbb7f53c-fd8e-4953-952a-b4f1dd8fd3ab 127.0.0.1:9215
      broker = http
      protocol = grpc
      registry = mdns
      server = grpc
      transport = grpc
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.storage:1310b573b
  Nodes:
    com.owncloud.storage-b915d672-4d0e-4036-a57e-cb74701976f6 127.0.0.1:9142
      protocol = grpc
      registry = mdns
      server = grpc
      transport = grpc
      broker = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.webdav:1310b573b
  Nodes:
    com.owncloud.web.webdav-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9115
      protocol = http
      registry = mdns
      server = http
      broker = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.idp:1310b573b
  Nodes:
    com.owncloud.web.idp-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9130
      server = http
      broker = http
      protocol = http
      registry = mdns
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.proxy:1310b573b
  Nodes:
    com.owncloud.web.proxy-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 172.17.0.2:9200
      broker = http
      protocol = http
      registry = mdns
      server = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.accounts:1310b573b
  Nodes:
    com.owncloud.web.accounts-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9181
      protocol = http
      registry = mdns
      server = http
      broker = http
  Configuration:
    ConfigService.GetConfig endpoint not found
-------
com.owncloud.api.accounts:1310b573b
  Nodes:
    com.owncloud.api.accounts-1a9c1a28-4ca3-4dc4-85b4-0a3c484a8593 127.0.0.1:9180
      protocol = grpc
      registry = mdns
      server = grpc
      transport = grpc
      broker = http
  Configuration:
    Couldn't get the configuration
-------
```
* Advantages:
  * Compact information
  * Output starts very early
  * Can show error information for some scenarios
    * Accounts is showing a "couldn't get the configuration" because the microservice is sending an empty response
    * Proxy is showning a "ConfigService.GetConfig endpoint not found" because it isn't implemented yet
* Disadvantages:
  * Not parseable
  * Need to format the information ourselves.

**Comment by jvillafanez** [comment] 2022-02-08 17:40
Additional problem found: a microservice can register multiple services in micro. Settings, is an example where both a HTTP (com.owncloud.web.settings) and a GRPC (com.owncloud.api.settings) service are registered. The configuration is expected to be the same because it will be the same function the one responding both calls.

The issue is that the HTTP server doesn't have enough information to know how we could get the configuration from there. We have to assume that there is an known url that can respond, but the endpoint could be a different one or it could be missing.

To solve this, the idea is that we'll add a "ConfigService.GetConfig" metadata information such as "see other: com.web.api.settings" to redirect the user to the service holding the configuration.
Once we detect that metadata, we'll just show the metadata, but not the configuration (it's duplicated information anyway.)

**Comment by jvillafanez** [comment] 2022-02-09 09:18
Planned format (to be agreed)
```
com.owncloud.api.thumbnails:1310b573b
  Nodes:
    127.0.0.1:9185
      broker=http; protocol=grpc; registry=mdns; server=grpc; transport=grpc
  Configuration:
    GRPC.Addr = 127.0.0.1:9185
    GRPC.Namespace = com.owncloud.api
    Log.Color = false
    Log.File = 
    Log.Level = debug
    Log.Pretty = false
    Service.Name = thumbnails
    Thumbnail.CS3AllowInsecure = true
    Thumbnail.FileSystemStorage.RootDirectory = /root/.ocis/thumbnails
    Thumbnail.FontMapFile = 
    Thumbnail.Resolutions = 16x16,32x32,64x64,128x128,1920x1080,3840x2160,7680x4320
    Thumbnail.RevaGateway = 127.0.0.1:9142
    Thumbnail.WebdavAllowInsecure = true
    Tracing.Collector = 
    Tracing.Enabled = false
    Tracing.Endpoint = 
    Tracing.Type = 
-------
com.owncloud.web.web:1310b573b
  Nodes:
    127.0.0.1:9100
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.api.settings:1310b573b
  Nodes:
    127.0.0.1:9191
      broker=http; protocol=grpc; registry=mdns; server=grpc; transport=grpc
  Configuration:
    Asset.Path = 
    DataPath = /root/.ocis/settings
    GRPC.Addr = 127.0.0.1:9191
    GRPC.Namespace = com.owncloud.api
    HTTP.Addr = 127.0.0.1:9190
    HTTP.CORS.AllowCredentials = true
    HTTP.CORS.AllowedHeaders = Authorization,Origin,Content-Type,Accept,X-Requested-With
    HTTP.CORS.AllowedMethods = GET,POST,PUT,PATCH,DELETE,OPTIONS
    HTTP.CORS.AllowedOrigins = *
    HTTP.CacheTTL = 604800
    HTTP.Namespace = com.owncloud.web
    HTTP.Root = /
    Log.Color = false
    Log.File = 
    Log.Level = debug
    Log.Pretty = false
    Service.Name = settings
    Tracing.Collector = 
    Tracing.Enabled = false
    Tracing.Endpoint = 
    Tracing.Type = 
-------
com.owncloud.web.ocs:1310b573b
  Nodes:
    127.0.0.1:9110
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.graph.graph:1310b573b
  Nodes:
    127.0.0.1:9120
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.webdav:1310b573b
  Nodes:
    127.0.0.1:9115
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.graph-explorer:1310b573b
  Nodes:
    127.0.0.1:9135
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.proxy:1310b573b
  Nodes:
    172.17.0.2:9200
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.idp:1310b573b
  Nodes:
    127.0.0.1:9130
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.storage:1310b573b
  Nodes:
    127.0.0.1:9142
      broker=http; protocol=grpc; registry=mdns; server=grpc; transport=grpc
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.accounts:1310b573b
  Nodes:
    127.0.0.1:9181
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.api.store:1310b573b
  Nodes:
    127.0.0.1:9460
      broker=http; protocol=grpc; registry=mdns; server=grpc; transport=grpc
  Configuration:
    Datapath = /root/.ocis/store
    GRPC.Addr = 127.0.0.1:9460
    GRPC.Namespace = com.owncloud.api
    Log.Color = false
    Log.File = 
    Log.Level = debug
    Log.Pretty = false
    Service.Name = store
    Tracing.Collector = 
    Tracing.Enabled = false
    Tracing.Endpoint = 
    Tracing.Type = 
-------
com.owncloud.api.accounts:1310b573b
  Nodes:
    127.0.0.1:9180
      broker=http; protocol=grpc; registry=mdns; server=grpc; transport=grpc
  Configuration:
    Error: Couldn't get the configuration
-------
com.owncloud.storage.metadata:1310b573b
  Nodes:
    127.0.0.1:9215
      broker=http; protocol=grpc; registry=mdns; server=grpc; transport=grpc
  Configuration:
    Error: ConfigService.GetConfig endpoint not found
-------
com.owncloud.web.settings:1310b573b
  Nodes:
    127.0.0.1:9190
      broker=http; protocol=http; registry=mdns; server=http
  Configuration:
    See: com.owncloud.api.settings
-------
```
Note: the configuration for the `com.owncloud.web.settings` is delegated to the `com.owncloud.api.settings` since the configuration will be the same and we can't really distinguish which piece of configuration belongs to which service.
Other services not implemented yet might have the same behavior

The report command will only access to the configuration via GRPC

**Comment by kobergj** [comment] 2024-06-07 13:33
Since there is no action for 2 years I assume this isn't needed any more? I'll close this. Please reopen and make some noise  if you think differently.

**Closed by kobergj** 2024-06-07 13:33 UTC
Labels: Type:Technical-Debt, Category:Enhancement
