### ISSUE TITLE
[QA] Files shared are listed in files view after the user that shared the file was deleted

### ISSUE THREAD

**Issue by davitol** [owncloud/ocis#890] opened 2020-11-18 13:50 UTC
Tested using oCIS 1.0.0-RC5

## Steps to reproduce

1.  Alice shares a file with Bob
2. Bob accepts the share
3. Admin user deletes user Alice
4. Check Bob's file view

## Expected behaviour

File should no longer be listed (as it happened in oC10)

## Current behaviour

File shared is listed after Alice user was deleted

**Comment by kobergj** [comment] 2024-06-03 13:48
cannot reproduce any more. closing.

**Closed by kobergj** 2024-06-03 13:48 UTC
Labels: Type:Bug, Category:Technical, Interaction:Needs-Concept
