### ISSUE TITLE
Unable to download a shared file by share reciever

### ISSUE THREAD

**Issue by nabim777** [owncloud/ocis#8618] opened 2024-03-12 09:22 UTC
## Describe the bug
When a sharee tries to download the shared file the ocis server returns `404`

## Steps to reproduce
1. As a user `admin`, create a file `file.txt`
2. As a user `admin`, share a file `file.txt` with user `einstein`
3. As a user `einstein`, try to download the shared file but unable to download the file

## Expected behavior
The share reciever have to able to download the file

## Actual behavior
The share reciever unable to download

## Test Environment set up
`ownCloud Web UI 9.0.0-alpha.1`
`Infinite Scale 5.1.0-prealpha+db3ed9fc4 Community`

But bug not reproduced on 
`ownCloud Web UI 8.0.0`  
 `Infinite Scale 5.0.0-rc.5 Community`

**Comment by ScharfViktor** [comment] 2024-03-12 09:30
<img width="1668" alt="image" src="https://github.com/owncloud/ocis/assets/84779829/81087224-5340-465c-b891-8f815a170345">

ocis log: 
```
2024/03/12 10:29:38 http: TLS handshake error from 127.0.0.1:53185: remote error: tls: unknown certificate
2024/03/12 10:29:51 http: TLS handshake error from [::1]:53292: remote error: tls: unknown certificate
```

**Comment by kobergj** [comment] 2024-03-12 09:48
Can confirm. Download fails when clicking in `Actions` menu.

NOTE: Download works fine when clicking the button in the image viewer!

**Comment by nabim777** [comment] 2024-03-13 06:21
@kulmann I've used bisect to check, and it seems that there's a bug originating from this particular PR https://github.com/owncloud/ocis/commit/050c025a6a13c9c8e78c799104eac9bdb1ff14f4

**Comment by kulmann** [comment] 2024-03-13 06:45
> @kulmann I've used bisect to check, and it seems that there's a bug originating from this particular PR [050c025](https://github.com/owncloud/ocis/commit/050c025a6a13c9c8e78c799104eac9bdb1ff14f4)

I've forward ported the web `stable-8.0` branch to web `master` recently. Let me tag a `v9.0.0-alpha.2` from web `master` and bump it in ocis. Could you check again after I did the web update?

**Comment by kulmann** [comment] 2024-03-13 08:52
Web bump is in progress here: https://github.com/owncloud/ocis/pull/8634

**Comment by kulmann** [comment] 2024-03-13 09:52
... and merged. @nabim777 could you check again?

**Comment by kobergj** [comment] 2024-03-13 10:14
I still get the error locally

**Comment by saw-jan** [comment] 2024-03-13 10:23
> ... and merged. @nabim777 could you check again?

AFAIK, the bug report was from building/using the latest web-master and latest ocis (master) image. so the bug is expected to persist even if the web is bumped in ocis.

**Comment by micbar** [comment] 2024-03-13 12:35
how do we fix that?

**Comment by JammingBen** [comment] 2024-03-13 13:57
As we found out earlier: Web manually appends the `SHARE_JAIL_ID` to the `webDavPath`, which is used to download a file: https://github.com/owncloud/web/blob/master/packages/web-client/src/helpers/share/functionsNG.ts#L107

IMO this is wrong, it should simply use the drive items's id instead (assuming the server sends it correctly). In my tests, omitting the `SHARE_JAIL_ID` fixes the issue with downloading the file.

**Comment by kobergj** [comment] 2024-03-13 15:28
@JammingBen great you found out! :+1: So this needs a web change only? Could you take care of this?

**Comment by JammingBen** [comment] 2024-03-13 15:43
> @JammingBen great you found out! 👍 So this needs a web change only? Could you take care of this?

Yes, a Web-only change should be sufficient, if I don't oversee anything. I'll open a PR and see if pipeline has any objections.

**Comment by micbar** [comment] 2024-03-13 16:12
Just for completeness: are we sure that this doesn’t happen with ocis 5.0.0 and web 8.0.1?

**Comment by nabim777** [comment] 2024-03-13 16:29
After conducting a bisect in the web, it appears that this pull request may be the origin of the bug https://github.com/owncloud/web/commit/514c4ea29794a4309dc2f66c3623c8a416a38c02

**Comment by JammingBen** [comment] 2024-03-13 16:41
> Just for completeness: are we sure that this doesn’t happen with ocis 5.0.0 and web 8.0.1?

Yes, this is definitely a Web issue that broke with the transition to sharing NG on current master (= Web `9.0.0`).

**Comment by saw-jan** [comment] 2024-03-14 03:46
> After conducting a bisect in the web, it appears that this pull request may be the origin of the bug [owncloud/web@514c4ea](https://github.com/owncloud/web/commit/514c4ea29794a4309dc2f66c3623c8a416a38c02)

looking on the changes, commit doesn't seem to the cause. but maybe the commit before or after
Fix is already there https://github.com/owncloud/web/pull/10599

**Closed** 2024-03-14 06:06 UTC
Labels: Type:Bug, Priority:p2-high
