### ISSUE TITLE
traces show wrong service names

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#6813] opened 2023-07-14 15:00 UTC
The service names in tracing are wrong after merging some of the trace PRs:
![image](https://github.com/owncloud/ocis/assets/956847/9df78ba5-20df-4da0-bdac-62f02dd5e106)

The IdP has nothing to do with ListStorageSpaces, not as a client, not as a server ...

**Comment by butonic** [comment] 2023-07-14 15:06
this only seems to happen when running in single process ...

**Comment by micbar** [comment] 2023-07-17 08:22
@ainmosni @dragonchaser Can you fix that?

**Comment by ainmosni** [comment] 2023-07-19 07:14
I'm not able to reproduce this in the single process mode.

![Screenshot_20230719_091317](https://github.com/owncloud/ocis/assets/1147920/b1b0c285-e9cd-4770-83a3-883e8efd942c)

**Comment by dragonchaser** [comment] 2023-08-29 13:30
closing, could not reproduce

**Closed as completed by dragonchaser** 2023-08-29 13:30 UTC
Labels: Type:Bug
