### ISSUE TITLE
User can manipulate space after role has been changed to `Guest`

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5852] opened 2023-03-16 07:25 UTC
## Describe the bug

After changing the user role from `Space Admin` or `Admin` to the `Guest`. The user is allowed to do what the Space Admin role implicates(delete space, disable space, upload resources to the space, add members to space, share the space) except creating new space. 

## Steps to reproduce

1.  user `Alice` has been assigned the role `Space Admin` or `Admin`
2. user `Alice` create space `Project1`
3. admin has set the user `Alice` role to `Guest`
4. Alice tries to disable/delete/add member/share space `Project1`

## Expected behavior
User Alice should not able to perform any action related to Space Admin after the role has been changed to Guest

## Actual behavior
User `Alice` is allowed to do what the Space Admin role implicates(delete space, disable space, upload resources to the space, add members to space, share the space) except creating new space.

**Comment by ScharfViktor** [comment] 2023-03-16 08:25
Guest hasn't personal account and can only upload in project space if he has access. But if he started as user -> he has personal space and can upload files.

I would prohibit changing the user's role to Guest to prevent this from happening. 
A guest in my understanding is a temporary user who has logged in to get acquainted. I accept the case of translation of guest->user, but not the reverse. What is the situation in real life? @micbar @tbsbdr 

My expected behavior after step3: it's not possible to change user role to Guest

**Comment by micbar** [comment] 2023-03-20 07:28
@amrita-shrestha @ScharfViktor There is some confusion because two different issues are mixing up here.
You are mixing up "Space Admin" and "Manager"

There are

1) Global Roles

and 

2) Space Membership Roles

which are completely independent.

## Expected behavior

1) A global role grants users permissions like "create.space" or change users quota. These permissions only apply to "global" application permissions. So the steps 1-4 are correct. Step 5 would be "Alice cannot create a new space"

A user with the role "Space Admin" should not be able to add/remove users from a space  where he is not a member of.

2) Alice has created the space "project1" and  has a space membership as a "Manager" therefore she can add/remove members, enable/disable/delete, upload and so on. The change of the global User Role doesn't affect the space memberships.

## Concept

Clear separation between "Space Management" from the Admin POV and "Content Management". Use case is, e.g. an "Admin" or "Space Admin" is not able to see the content of any space where he is not a member of.

I hope that clarifies the concept.

**Comment by phil-davis** [comment] 2023-03-20 07:38
@amrita-shrestha the "Expected Behavior" currently says:
"User Alice should not able to perform any action related to Space Admin after the role has been changed to normal user"

That confuses me. Maybe you meant to say:
"User Alice should not able to perform any action related to Space Admin after the role has been changed to guest"

**Comment by phil-davis** [comment] 2023-03-20 07:47
General comment: it seems strange to me that a real ordinary user can be created, can then do things (create files/folder in their personal space, create a space (if they have that permissions), create files/folder in spaces that they have access to...) and then the Admin changes their role to "guest".

When the Admin changes their role to "guest", what would be the requirement for their personal space? Should it be deleted? (and the files/folders in it are gone)

Similarly, should Admin be able to change the role of someone from "guest" to "user"? If so, then I suppose the implementation/requirement is easier - for the existing "guest", the code would now create them a personal space, and set their role to "user" (and do anything else that a "user" needs).

So firstly, is there a requirement that, after initial creation of an account:
a) the role can be changed from "guest" to "user"
b) the role can be changed from "user" to "guest"

**Comment by ScharfViktor** [comment] 2023-03-20 10:17
I tested it again. After `Alice` logs in as guest:

> ## Actual behavior
> User `Alice` is allowed to do what the Space Admin role implicates(delete space, disable space, upload resources to the space, add members to space, share the space) except creating new space.
- can manage `Project1 ` space - because she is `Manager` of the space - **OK**

>  Step 5 would be "Alice cannot create a new space"
- she cannot create new Project space -  **OK**

- she has no access to `Administration settings` tab- **OK**

**but**:
- she has personal space and can create new recourses - **NOT OK**

I created bug for that #5874  to don't to create confusion here

If we can close this problem in favor of #5874

**Comment by micbar** [comment] 2023-03-20 14:02
> she has personal space and can create new recourses - NOT OK

I would say "works as designed" because at the time she logged in, she had the permission to create a personal space.

I think we will think about the workflow here, @tbsbdr IMO we should think about if the "Downgrade" direction is supported at all. The "upgrade" from Guest to "User" is far more likely.

**Comment by rhafer** [comment] 2024-08-20 08:41
> If we can close this problem in favor of #5874

I think all the issue reported here have be clarified. I am closing this.

**Closed by rhafer** 2024-08-20 08:41 UTC
Labels: Type:Bug, Interaction:Needs-help
