### ISSUE TITLE
Folder with '.' in its name is shown as an extension

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#1216] opened 2021-01-15 11:35 UTC
Folder with '.' in its name is shown as an extension. It happens for any other extension followed by '.'
Example: testFolder.xyz, testFolder.mp3, etc

## Steps to recreate
- User moss uploads a folder `testFolder`
- User moss renames folder `testFolder` to `testFolder.part`

## Expected
Folder `testFolder.part` should exist with `.part` should be the part of the folder's name

## Actual
Folder `testFolder.part` exists but `.part` is displayed as extension unless the page is refreshed.

https://user-images.githubusercontent.com/17021686/104722427-e756e380-5755-11eb-9063-869ae4991bd3.mp4

**Comment by phil-davis** [comment] 2021-01-15 11:57
@swoichha is this a special "feature" for folders with `.part` extension? Or does it happen for any "extension" that you put?

**Comment by swoichha** [comment] 2021-01-15 12:02
> @swoichha is this a special "feature" for folders with `.part` extension? Or does it happen for any "extension" that you put?

@phil-davis It happens for any other extension followed by '.' for example: testFolder.xyz, testFolder.mp3, etc.

**Comment by individual-it** [comment] 2021-01-25 06:15
- [ ]  ToDo QA-team: add tests for that case

**Comment by pascalwengerter** [comment] 2021-06-10 19:10
Closing as fixed since I can't reproduce this in current `master`

**Closed by pascalwengerter** 2021-06-10 19:10 UTC
Labels: Platform:Web, Type:Bug
