### ISSUE TITLE
There are LDAP errors in the syslog from an old certificate

### ISSUE THREAD

**Issue by georgebarnett** [owncloud/ocis#9309] opened 2024-06-04 07:41 UTC
## Describe the bug

After restart I saw these errors in the logs.  I'm using the onboard IDM.

Turns out there was an old certificate in `/var/lib/ocis/idm/ldap.*` which I removed and then the normal startup as it was regenerated.

Leaving the following here to be indexed by google.

```
Jun  4 17:32:33 hostname ocis[59007]: {"level":"error","service":"idp","error":"ldap identifier backend get user connect error: LDAP Result Code 200 \"Network
 Error\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-06-04T17:32:33+10:00 is after 2024-06-02T02:
34:29Z","time":"2024-06-04T17:32:33.051275278+10:00","message":"IdentifierIdentityManager: fetch failed to get user from userID"}

```
## Steps to reproduce
1.  Have an old cert and see errors in the logs.

## Expected behavior
Not breaking.  Seems like this is internal, so it could be auto regenerated?

## Actual behavior
Authentication is down until the trust is resolved.

## Setup
OCIS 4.

**Comment by rhafer** [comment] 2024-06-04 07:49
Duplicate of #8552

**Closed by rhafer** 2024-06-04 07:49 UTC
Labels: Type:Bug
