### ISSUE TITLE
[e2e-test] `participantManagement.ocis.feature:3` failed in nightly 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#5400] opened 2023-01-13 03:46 UTC
Following scenario failed on master nightly 

```feature
Feature: spaces participant management # tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature:1

  Scenario: participant management # tests/e2e/cucumber/features/smoke/spaces/participantManagement.ocis.feature:3
    Given "Admin" creates following users
      │ id      │
      │ Alice   │
      │ Brian   │
      │ Carol   │
      │ Marie   │
      │ Richard │
    And "Admin" creates following group
      │ id       │
      │ sales    │
      │ security │
    And "Admin" adds user to the group
      │ user    │ group    │
      │ Marie   │ sales    │
      │ Richard │ security │
    And "Admin" assigns following roles to the users
      │ id    │ role       │
      │ Alice │ SpaceAdmin │
    When "Alice" logs in
    And "Alice" opens the "files" app
    And "Alice" navigates to the projects space page
    And "Alice" creates the following project spaces
      │ name │ id     │
      │ team │ team.1 │
    And "Alice" navigates to the project space "team.1"
    And "Alice" adds following members to the project space
      │ member   │ role   │ kind  │
      │ Brian    │ editor │ user  │
      │ Carol    │ viewer │ user  │
      │ sales    │ viewer │ group │
      │ security │ editor │ group │
    When "Brian" logs in
    And "Brian" navigates to the projects space page
    And "Brian" navigates to the project space "team.1"
    And "Brian" creates the following resources
      │ resource │ type   │
      │ parent   │ folder │
    And "Brian" uploads the following resources
      │ resource  │ to     │
      │ lorem.txt │ parent │
    When "Marie" logs in
    And "Marie" navigates to the projects space page
    And "Marie" navigates to the project space "team.1"
    Then "Marie" should see folder "parent" but should not be able to edit
    And "Marie" logs out
    When "Richard" logs in
    And "Richard" navigates to the projects space page
    And "Richard" navigates to the project space "team.1"
    And "Richard" creates the following resources
      │ resource │ type   │
      │ richard  │ folder │
    And "Richard" uploads the following resources
      │ resource  │ to      │
      │ lorem.txt │ richard │
    And "Richard" logs out
    When "Carol" logs in
    And "Carol" navigates to the projects space page
    And "Carol" navigates to the project space "team.1"
    Then "Carol" should see folder "parent" but should not be able to edit
    When "Alice" reloads the spaces page
    And "Alice" creates a public link for the resource "parent" using the sidebar panel
    And "Alice" edits the public link named "Link" of resource "parent" changing role to "editor"
    And "Anonymous" opens the public link "Link"
    And "Anonymous" uploads the following resources in public link page
      │ resource     │
      │ textfile.txt │
    ✖ failed
      locator.click: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for locator('#upload-menu-btn')
      ============================================================
          at uploadResource (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/actions.ts:164:46)
          at Public.upload (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/page/public.ts:54:44)
          at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/public.ts:77:26)
    And "Anonymous" deletes the following resources from public link
      │ resource  │
      │ lorem.txt │
    - skipped
    And "Brian" deletes the following resources
      │ resource            │
      │ parent/textfile.txt │
    - skipped
    And "Anonymous" logs out
    - skipped
    When "Carol" navigates to the trashbin of the project space "team.1"
    - skipped
    Then "Carol" should not be able to delete following resources from the trashbin
      │ resource            │
      │ parent/lorem.txt    │
      │ parent/textfile.txt │
    - skipped
    And "Carol" should not be able to restore following resources from the trashbin
      │ resource            │
      │ parent/lorem.txt    │
      │ parent/textfile.txt │
    - skipped
    And "Carol" logs out
    - skipped
    When "Brian" navigates to the trashbin of the project space "team.1"
    - skipped
    Then "Brian" should be able to restore following resources from the trashbin
      │ resource            │
      │ parent/lorem.txt    │
      │ parent/textfile.txt │
    - skipped
    When "Alice" navigates to the projects space page
    - skipped
    And "Alice" navigates to the project space "team.1"
    - skipped
    And "Alice" removes access to following users from the project space
      │ user  │
      │ Brian │
    - skipped
    When "Brian" navigates to the projects space page
    - skipped
    Then "Brian" should not be able to see space "team.1"
    - skipped
    And "Brian" logs out
    - skipped
    When "Alice" changes the roles of the following users in the project space
      │ user  │ role    │
      │ Carol │ manager │
    - skipped
    And "Alice" as project manager removes their own access to the project space
    - skipped
    Then "Alice" should not be able to see space "team.1"
    - skipped
    And "Alice" logs out
    - skipped
```
Build link: https://drone.owncloud.com/owncloud/ocis/18266/80/9

**Comment by SwikritiT** [comment] 2023-01-13 03:51
Seems like it was introduce by https://github.com/cs3org/reva/pull/3583

**Comment by saw-jan** [comment] 2023-01-13 04:16
Also see: https://chat.owncloud.com/channel/ocis-internal?msg=vANsQraaH99ScTTsC
From the conversation, the problem is in the server. Probably, there will be a fix and also reva bump in oCIS then we can close this with that.

**Comment by saw-jan** [comment] 2023-01-16 04:22
Passes now with revert PR https://github.com/cs3org/reva/pull/3597 and reva bump https://github.com/owncloud/ocis/pull/5404

So, closing here

**Closed by saw-jan** 2023-01-16 04:22 UTC
Labels: QA:team
