### ISSUE TITLE
Web e2e test can fail when creating multiple text files using API - oCIS couldn't handle all requests properly

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#9648] opened 2024-07-18 04:19 UTC
## Description
Build: https://drone.owncloud.com/owncloud/web/45882/13/8

Failed Scenario:
```feature
Scenario: pagination (attempt 2) # tests/e2e/cucumber/features/navigation/personalSpacePagination.feature:6
   ✔ Before # tests/e2e/cucumber/environment/index.ts:44
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:45
   ✔ And "Alice" creates 55 folders in personal space using API # tests/e2e/cucumber/steps/api.ts:74
   ✖ And "Alice" creates 55 files in personal space using API # tests/e2e/cucumber/steps/api.ts:137
       Error: expect(received).not.toBeDefined()

       Received: [Error: Unknown error]
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.44.1/node_modules/playwright/lib/matchers/expect.js:177:37)
           at Page.<anonymous> (/var/www/owncloud/web/tests/e2e/support/environment/actor/actor.ts:30:31)
           at Page.emit (node:events:514:28)
           at Page.emit (node:domain:489:12)
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/browserContext.js:124:34)
           at Proxy.emit (node:events:514:28)
           at Proxy.emit (node:domain:489:12)
           at Connection.dispatch (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/connection.js:202:21)
           at Immediate.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/inProcessFactory.js:49:83)
           at processImmediate (node:internal/timers:476:21)
   - And "Alice" creates the following files into personal space using API # tests/e2e/cucumber/steps/api.ts:108
       | pathToFile           | content                |
       | .hidden-testFile.txt | This is a hidden file. |
   - And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:15
   - When "Alice" navigates to page "2" of the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:716
   - Then "Alice" should see the text "111 items with 1 kB in total (56 files including 1 hidden, 55 folders)" at the footer of the page # tests/e2e/cucumber/steps/ui/resources.ts:734
   - And "Alice" should see 10 resources in the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:744
   - When "Alice" enables the option to display the hidden file # tests/e2e/cucumber/steps/ui/resources.ts:395
   - Then "Alice" should see 11 resources in the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:744
   - When "Alice" changes the items per page to "500" # tests/e2e/cucumber/steps/ui/resources.ts:725
   - Then "Alice" should not see the pagination in the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:754
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:58
   ✖ After # tests/e2e/cucumber/environment/index.ts:112
       Error: expect(received).not.toBeDefined()

       Received: [Error: Unknown error]
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.44.1/node_modules/playwright/lib/matchers/expect.js:177:37)
           at Page.<anonymous> (/var/www/owncloud/web/tests/e2e/support/environment/actor/actor.ts:30:31)
           at Page.emit (node:events:514:28)
           at Page.emit (node:domain:489:12)
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/browserContext.js:124:34)
           at Proxy.emit (node:events:514:28)
           at Proxy.emit (node:domain:489:12)
           at Connection.dispatch (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/connection.js:202:21)
           at Immediate.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/inProcessFactory.js:49:83)
           at processImmediate (node:internal/timers:476:21)
```

**Comment by ScharfViktor** [comment] 2024-07-18 13:55
It's backend issue so I moved to the `ocis` repo

after discussion with @butonic, we decided to temporarily skip this e2e test so as to not block CI

**Comment by ScharfViktor** [comment] 2024-07-18 14:45
How to reproduce it localy: 

- get personalSpaceUUID
- open `ocis` in browser
- run script which creates 100 txt files
- see 500 error 

run script: 

```sh
#!/bin/bash


for i in {1..100}
do
  response=$(curl -k -s -o /dev/null -w "%{http_code}" -X PUT "https://localhost:9200/remote.php/dav/spaces/yourSpaceUUid/${i}.txt" -u admin:admin --data "This is the content of file ${i}.txt")
  
  if [ "$response" -ne 201 ]; then
    echo "File ${i}.txt creation failed with response code $response"
    exit 1
  else
    echo "File ${i}.txt created successfully"
  fi
done
```

**Comment by saw-jan** [comment] 2024-07-19 05:55
Don't know if it is related to https://github.com/owncloud/ocis/issues/9573

**Comment by butonic** [comment] 2024-07-19 14:45
hm I cannot reproduce this with the script when running it locally. even after 1000 files I don't see an error ... (basic auth vs oidc makes no difference)

**Comment by butonic** [comment] 2024-07-19 14:57
ok, now I'm running three concurrent scripts with 1k files each against a kubernetes deployment with ocis in a single container ... still no errors.

**Comment by ScharfViktor** [comment] 2024-07-19 14:57
hm, now I cannot reproduce it. but there was a bug. I recorded it 😀

I'll try to enable test again. let see

**Comment by ScharfViktor** [comment] 2024-07-22 07:33
> I'll try to enable test again. let see

error still exist😪 https://drone.owncloud.com/owncloud/web/45973/14/9

**Comment by saw-jan** [comment] 2024-07-31 05:24
still fails: https://drone.owncloud.com/owncloud/web/46239/14/9
but small amount of wait between each request can make the test pass. (https://drone.owncloud.com/owncloud/web/46238/14/9)

**Comment by ScharfViktor** [comment] 2024-07-31 08:19
> still fails: https://drone.owncloud.com/owncloud/web/46239/14/9 but small amount of wait between each request can make the test pass. (https://drone.owncloud.com/owncloud/web/46238/14/9)

let try to small amount

or we can implement getting token using api to avoid this issue or similar

what do test now: 
- Alice opens browser (to set bearer token -> it needed for api requests)
- Alice using api(Given step) creates  55 files -> web page stays open (in personal space) and immediately tries to display the new files we are uploading and catch UNCAUGHT EXCEPTION and 500 errors. 
We have similar test for uploading files in the project space-> works fine because personal space is open in web. I'm sure if we go inside to project space before uploading files -> we get same error

How in conclusion I see  3 ways how to solve this issue: 
- add small amount between uploading each file. 
- getting token using api (do not login) - best way for me 
- before uploading files in personal space -> go off the personal space page

**Comment by saw-jan** [comment] 2024-07-31 08:30
>getting token using api (do not login) - best way for me

This would be the way to go if we can get valid token using API

**Comment by S-Panta** [comment] 2024-09-03 06:26
Closing this issue as this is solved with https://github.com/owncloud/web/pull/11368.
As per @ScharfViktor  suggestion, the bearer token is received with API before login.

**Closed by S-Panta** 2024-09-03 06:26 UTC
Labels: Type:Bug
