### ISSUE TITLE
Public share are not deleted when user is deleted

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/ocis#1240] opened 2020-07-22 08:16 UTC
### Steps to reproduce
1.  from ocis repo start phoenix `bin/ocis server` . For details about the setup, check the section `run tests > with Ocis backend` https://owncloud.github.io/clients/web/testing/
2. Import ldap users and as `user1` create a public link
3. delete `user1` (from LDAP)
4. Even after deleting `user1` share info is not deleted from `publicshares.json` file.
Similar behavior is noticed for normal share https://github.com/owncloud/ocis-reva/issues/262

**Comment by refs** [comment] 2021-01-18 11:33
duplicate of https://github.com/owncloud/ocis/issues/1226

**Closed by refs** 2021-01-18 11:33 UTC
