### ISSUE TITLE
Overall performance difference with phoenix.owncloud.com

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#931] opened 2020-11-23 10:41 UTC
![](https://i.imgur.com/HRjletS.png)

There is a significant performance hit on our deployment compared with the demo Phoenix instance. 

(By looking at the JS flamegraph, it looks like a recursion issue)

**Comment by kulmann** [comment] 2020-11-28 05:59
My strongest guess at the moment is, that this is caused by rendering the files list. Switching from Flame Chart to Waterfall I can see a lot of `Recalculate Style`, `Layout` and `Apply Style Changes` events in the list. However, with our recent changes (caching the `userinfo`, making sure that the `.wellknown` endpoint is only fetched once, caching phoenix web assets in the browser with force revalidation) brought pretty good web ui performance on ocis-bridge.owncloud.works.

For background: the files list component will be rewritten to reach accessibility compliance. We'll pay attention to performance behaviour with the new component then. But I don't think that the symptoms in the flame chart are related to performance issues.

How can we proceed with this issue?

**Comment by refs** [comment] 2021-01-13 12:22
Can someone have a second / third look into this?

ping @butonic @kulmann @micbar as you are the only participants. Worth keeping an eye at it in the near future, as it might be a quick win.

**Comment by micbar** [comment] 2021-01-13 12:29
IMO this was solved by fixing the request overhead.

**Comment by refs** [comment] 2021-01-13 12:50
if we can get a confirmation then I'd say let's close the issue

**Comment by micbar** [comment] 2021-01-13 15:36
@SamuAlfageme I will close here, please re-open if necessary

**Closed by micbar** 2021-01-13 15:36 UTC
Labels: Category:Technical, Type:Discussion, p3-medium
