### ISSUE TITLE
Intermittent webUI test scenario

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#1492] opened 2021-01-26 10:37 UTC
https://drone.owncloud.com/owncloud/ocis/2906/71/7
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:59
```

I have noticed this scenario has failed a few times in recent days. But mostly it passes.

Investigate and try to fix it.

**Comment by phil-davis** [comment] 2021-01-28 02:35
Another example here last night: https://drone.owncloud.com/owncloud/ocis/2996/71/7
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:59
```

**Comment by dpakach** [comment] 2021-01-28 06:10
The test failing here 
https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature#L59

If we remove that line, the test on the following line 
https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature#L60

will fail. It seems to me that the server is not fully ready when the tests fail because the first test fails intermittently. 
@phil-davis any idea why this is happening?

https://drone.owncloud.com/owncloud/ocis/3006/30/7

**Comment by phil-davis** [comment] 2021-01-29 08:01
I have seen this twice today: https://drone.owncloud.com/owncloud/ocis/3031/71/7
```
  Scenario Outline: share a folder with multiple users using role as advanced permissions role and different extra permissions
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (3319ms).
  Using: chrome (80.0.3987.149) on Linux platform.

  tests/acceptance/features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:59

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no"
    And the administrator has set the default folder for received shares to "Shares"
    And these users have been created with default attributes:
      │ username │
      │ user1    │
      │ user2    │
(node:390) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
    Given these users have been created with default attributes:
      │ username │
      │ user0    │
      │ user3    │
      │ user4    │
    And user "user1" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 907 milliseconds.
√ Element <#oc-app-container> was visible after 1263 milliseconds.
√ Element <//button[@id="new-file-menu-btn" and contains(@class, "oc-button-primary") and not(@disabled)]> was present after 32 milliseconds.
√ Element <//div[contains(@class, "oc-file") and @data-preview-loaded="false"]> was not present after 25 milliseconds.
    When the user opens the share dialog for folder "simple-folder" using the webUI
√ Element <#files-list-container> was present after 37 milliseconds.
Timed out while waiting for element <.vue-recycle-scroller> to be present for 20000 milliseconds. - expected "visible" but got: "not found" (20006ms)
undefined    ✖ failed
      Timed out while waiting for element <.vue-recycle-scroller> to be present for 20000 milliseconds. - expected "visible" but got: "not found" (20006ms)
          at Proxy._callee28$ (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:570:18)
          at new Promise (<anonymous>)
          at Proxy.filesListScrollToTop (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:569:25)
          at Proxy._callee19$ (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:285:18)
    And the user opens the share creation dialog in the webUI
    - skipped
    And the user selects the following collaborators for the share as "Advanced permissions" with "delete" permissions:
      │ collaborator │ type │
      │ Regular User │ user │
      │ User Two     │ user │
      │ User Three   │ user │
      │ User Four    │ user │
    - skipped
    And the user removes "User Four" as a collaborator from the share
    - skipped
    And the user removes "Regular User" as a collaborator from the share
    - skipped
    And the user shares with the selected collaborators
    - skipped
    And user "user2" accepts the share "simple-folder" offered by user "user1" using the sharing API
    - skipped
    And user "user3" accepts the share "simple-folder" offered by user "user1" using the sharing API
    - skipped
    Then custom permissions "delete" should be set for user "User Two" for folder "simple-folder" on the webUI
    - skipped
    And custom permissions "delete" should be set for user "User Three" for folder "simple-folder" on the webUI
    - skipped
    And user "User Two" should be listed as "Advanced permissions" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "User Three" should be listed as "Advanced permissions" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "user2" should have received a share with these details:
      │ field       │ value                 │
      │ uid_owner   │ user1                 │
      │ share_with  │ user2                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ read, delete          │
    - skipped
    And user "user3" should have received a share with these details:
      │ field       │ value                 │
      │ uid_owner   │ user1                 │
      │ share_with  │ user3                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ read, delete          │
    - skipped
    But user "Regular User" should not be listed in the collaborators list on the webUI
    - skipped
    And as "user0" folder "/Shares/simple-folder" should not exist
    - skipped
    And user "User Four" should not be listed in the collaborators list on the webUI
    - skipped
    And as "user4" folder "/Shares/simple-folder" should not exist
    - skipped
```

**Comment by phil-davis** [comment] 2021-01-29 08:49
It seems to be a "hard" failure today: https://drone.owncloud.com/owncloud/ocis/3032/71/7

**Comment by dpakach** [comment] 2021-01-29 09:06
The really strange thing is that only the first test fails. I tried waiting for sometime before the tests start to see if they pass that way
https://drone.owncloud.com/owncloud/ocis/3027/32/6
But that seems to be the case. At this point, I have no idea why it's failing.

**Comment by dpakach** [comment] 2021-02-09 11:13
The reason we started to see this failure recently because we used the script to run tests with expected failure scenarios and this issue https://github.com/owncloud/web/issues/4728

We still need to find why this fails on first try.

**Comment by phil-davis** [comment] 2021-02-19 06:21
This happened in OCIS CI just now: https://drone.owncloud.com/owncloud/ocis/3567/73/7

**Comment by phil-davis** [comment] 2021-02-19 07:17
Here https://drone.owncloud.com/owncloud/ocis/3569/54/7 is a different fail.
```
  tests/acceptance/features/webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:56

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no"
    And the administrator has set the default folder for received shares to "Shares"
    And these users have been created with default attributes:
      │ username │
      │ user1    │
      │ user2    │
    Given user "user1" has created folder "/simple-folder/simple-empty-folder/new-folder"
    And user "user1" has uploaded file with content "test" to "/simple-folder/simple-empty-folder/lorem.txt"
    And user "user1" has shared folder "simple-folder" with user "user2"
    And user "user2" has accepted the share "simple-folder" offered by user "user1"
    When user "user1" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 920 milliseconds.
√ Element <#oc-app-container> was visible after 1541 milliseconds.
√ Element <//button[@id="new-file-menu-btn" and contains(@class, "oc-button-primary") and not(@disabled)]> was present after 23 milliseconds.
√ Element <//div[contains(@class, "oc-file") and @data-preview-loaded="false"]> was not present after 21 milliseconds.
    And the user opens the share dialog for folder "simple-folder" using the webUI
√ Element <#files-list-container> was present after 20 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 38 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 27 milliseconds.
√ Element <//span[contains(@class, "oc-file-name") and text()='simple-folder' and not(../span[contains(@class, "oc-file-extension")])]/ancestor::div[@data-is-visible="true"]//div[contains(@class, "oc-file") and (@data-preview-loaded="true" or @data-preview-loaded="disabled")]> was visible after 41 milliseconds.
√ Element <#files-list-container> was present after 14 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 34 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 37 milliseconds.
√ Element <//span[contains(@class, "oc-file-name") and text()='simple-folder' and not(../span[contains(@class, "oc-file-extension")])]/ancestor::div[@data-is-visible="true"]//div[contains(@class, "oc-file") and (@data-preview-loaded="true" or @data-preview-loaded="disabled")]> was visible after 29 milliseconds.
√ Element <//div[@class="sidebar-container"]> was visible after 45 milliseconds.
    Then the following resources should have share indicators on the webUI
      │ fileName      │ expectedIndicators │
      │ simple-folder │ user-direct        │
√ Element <#files-list-container> was present after 15 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 27 milliseconds.
√ Element <.vue-recycle-scroller> was visible after 34 milliseconds.
√ Element <//span[contains(@class, "oc-file-name") and text()='simple-folder' and not(../span[contains(@class, "oc-file-extension")])]/ancestor::div[@data-is-visible="true"]//div[contains(@class, "oc-file") and (@data-preview-loaded="true" or @data-preview-loaded="disabled")]> was visible after 29 milliseconds.
    ✖ failed
      AssertionError [ERR_ASSERTION]: Expected share indicators to be the same for "simple-folder": expected [user-direct] got []
          + expected - actual
      
          -false
          +true
      
          at _callee59$ (/srv/app/web/tests/acceptance/stepDefinitions/filesContext.js:1091:12)
          at tryCatch (/srv/app/web/node_modules/regenerator-runtime/runtime.js:63:40)
          at Generator.invoke [as _invoke] (/srv/app/web/node_modules/regenerator-runtime/runtime.js:293:22)
          at Generator.next (/srv/app/web/node_modules/regenerator-runtime/runtime.js:118:21)
          at asyncGeneratorStep (/srv/app/web/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
          at _next (/srv/app/web/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This is a different scenario to the ones above, but it is related to sharing. Maybe there will be a common problem with the test code that will fix "everything".

**Comment by dpakach** [comment] 2021-02-22 03:58
https://github.com/owncloud/web/pull/4737 
this Pr should have supressed the errors in the CI, but it still needs to be looked into why it fails at first attemp.

**Comment by individual-it** [comment] 2021-02-26 09:21
waiting for the web commit id get bumped in ocis https://github.com/owncloud/ocis/pull/1669

**Comment by individual-it** [comment] 2021-03-02 07:08
I could not reproduce the issue with the latest master of ocis and web (bumping all commit ids in the test setup) see https://github.com/owncloud/ocis/pull/1733 & https://github.com/owncloud/web/pull/4774
running the suite 10x in a pipeline only reports expected failures and the first and second runs are the same

closing the issue, feel free to reopen in case the issue is still there

**Closed by individual-it** 2021-03-02 07:08 UTC
Labels: QA:team
