### ISSUE TITLE
sharees API don't return shareType 4 if user is guest (user role guest)

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/ocis#6058] opened 2023-04-17 07:16 UTC
## Describe the bug

shareType is 0 but should be 4 if the user is a guest or has the guest role, as spoken with @butonic

**Comment by micbar** [comment] 2023-04-17 08:58
@hurradieweltgehtunter let me clarify the expectations:

The "guest" user is a user type property which cannot be set currently from the frontend. So we should think of renaming the role "guest" to "Contributor" to avoid naming clashes and wrong expectation.

**Comment by JanAckermann** [comment] 2023-04-17 09:26
I highly agree with the Contributor role and we should make this change ASAP before we introduce real guest users

**Comment by kulmann** [comment] 2023-04-17 09:41
Wait, why `Contributor`?

Looking at share roles (instead of share types), we already have a link sharing role `Contributor` for public links. So that would be a name clash and probably confusing.

Apart from that we already made the experience that `Contributor` and `Editor` link sharing roles are a frequent source of confusion, because nobody understands from the title what the difference is. I would suspect, that having a `Contributor` share type (now talking about share types again) causes similar lack of intuitive understanding.

**Comment by micbar** [comment] 2023-04-17 09:43
Agreed. 

The issue is the naming of the "Guest"  Role.

Suggesttions?

**Comment by JanAckermann** [comment] 2023-04-17 11:00
As discussed we don't need this role in the project and therefore it can be omitted

**Comment by kulmann** [comment] 2023-04-17 11:04
Clarified in a call:
- the "Guest" role and the "guest" user flag are semantically connected, but the single source of truth is the ldap guest user flag. It should not be derived from the `Guest` role.
- whether or not a user is a guest is defined by how the user comes into the system (managed in LDAP by sysadmin vs. invited via sharing)
- a guest user doesn't have a user role. Therefore we will **delete** the `Guest` user role in our set of default roles!

**Comment by JanAckermann** [comment] 2023-05-02 12:42
@micbar has the guest role removed? if yes, feel free to close the issue

**Comment by micbar** [comment] 2023-06-06 20:34
fixed by https://github.com/owncloud/ocis/pull/6456

**Closed by micbar** 2023-06-06 20:34 UTC
Labels: Type:Bug
