### ISSUE TITLE
webUISharingInternalUsers/shareWithUsers.feature:342 flaky

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2981] opened 2022-01-19 09:21 UTC
failed with ocis in https://drone.owncloud.com/owncloud/ocis/8801

**Comment by phil-davis** [comment] 2022-02-18 03:45
https://drone.owncloud.com/owncloud/ocis/9474/42/9 last night failed

**Comment by kiranparajuli589** [comment] 2022-02-21 14:17
related to https://github.com/owncloud/web/issues/6419#issuecomment-1042814956

**Comment by kiranparajuli589** [comment] 2022-02-22 08:02
### Steps to reproduce
Run the mentioned test `webUISharingInternalUsers/shareWithUsers.feature:342` multiple times in a row (10-20 times)

### Expected
`Shares` folder not shareable message should be displayed while opening `People` section from the sidebar

### Actual
Sometimes, screen like below is seen:

![Screenshot from 2022-02-22 13-43-23](https://user-images.githubusercontent.com/39373750/155087871-deb2b4f2-e2f4-44f1-8b67-f925a62a570f.png)

**Comment by kiranparajuli589** [comment] 2022-02-22 08:07
If I cancel the test (failing one) in between and try to open the `Peoples` section again, the issue persists.
![Peek 2022-02-22 13-52](https://user-images.githubusercontent.com/39373750/155089139-c48d84cc-decd-44b1-ac40-eba4d8436b6d.gif)

**Comment by kiranparajuli589** [comment] 2022-02-22 08:46
closing as the issue is already reported at https://github.com/owncloud/web/issues/6419

**Comment by individual-it** [comment] 2022-02-22 08:46
should we skip the tests?

**Comment by phil-davis** [comment] 2022-02-22 08:50
> should we skip the tests?

let's wait and see if we get any ideas from @kulmann or @pascalwengerter today. I pinged them late last week in issue comment https://github.com/owncloud/web/issues/6419#issuecomment-1042987270

But we may as well close this here. In the web issue, I specifically linked back to here, so it is easy to find the investigation results here.

**Closed by phil-davis** 2022-02-22 08:50 UTC
Labels: QA:team, QA:p2
