### ISSUE TITLE
Requests to webdav URLs with an fileid containing an invalid storage_id result in error 500

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#772] opened 2020-10-29 05:13 UTC
make any HTTP request to the meta data endpoint but give a fileId that base64 decodes to an invalid storage_id
e.g.: `curl -k -u richard:superfluidity -XPROPFIND https://localhost:9200/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU2OjhjY2QyNzUxLTkwYTQtNDBmMi1iOWYzLTYxZWRmODQ0MjFmNA==/v -v`

Its not the servers issue when the client sends an invalid request

## Ocis logs:

```
2020-10-29T10:53:28+05:45 ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/storageregistry/storageregistry.go:127 > error finding storage provider error="error: not found: storage provider not found for ref id:<storage_id:\"1284d238-aa92-42ce-bdc4-0b0000009156\" opaque_id:\"8ccd2751-90a4-40f2-b9f3-61edf84421f4\" > " pkg=rgrpc service=storage traceid=a6c24d7f170923f20a589c99f5894289
2020-10-29T10:53:28+05:45 INF unary code=OK end="29/Oct/2020:10:53:28 +0545" from=tcp://127.0.0.1:42392 pkg=rgrpc service=storage start="29/Oct/2020:10:53:28 +0545" time_ns=146269 traceid=a6c24d7f170923f20a589c99f5894289 uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-10-29T10:53:28+05:45 ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1283 > error finding storage provider error="gateway: grpc failed with code CODE_INTERNAL" pkg=rgrpc service=storage traceid=a6c24d7f170923f20a589c99f5894289
2020-10-29T10:53:28+05:45 ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1306 > error during STAT id: storage_id:"1284d238-aa92-42ce-bdc4-0b0000009156" opaque_id:"8ccd2751-90a4-40f2-b9f3-61edf84421f4"  error="gateway: grpc failed with code CODE_INTERNAL" pkg=rgrpc service=storage traceid=a6c24d7f170923f20a589c99f5894289
2020-10-29T10:53:28+05:45 INF unary code=OK end="29/Oct/2020:10:53:28 +0545" from=tcp://127.0.0.1:42382 pkg=rgrpc service=storage start="29/Oct/2020:10:53:28 +0545" time_ns=546021 traceid=a6c24d7f170923f20a589c99f5894289 uri=/cs3.gateway.v1beta1.GatewayAPI/Stat user-agent=grpc-go/1.26.0
2020-10-29T10:53:28+05:45 ERR grpc stat request failed pkg=rhttp resourceid={"opaque_id":"8ccd2751-90a4-40f2-b9f3-61edf84421f4","storage_id":"1284d238-aa92-42ce-bdc4-0b0000009156"} service=storage status={"code":15,"message":"error during STAT id: storage_id:\"1284d238-aa92-42ce-bdc4-0b0000009156\" opaque_id:\"8ccd2751-90a4-40f2-b9f3-61edf84421f4\" ","trace":"a6c24d7f170923f20a589c99f5894289"} traceid=a6c24d7f170923f20a589c99f5894289
2020-10-29T10:53:28+05:45 ERR http end="29/Oct/2020:10:53:28 +0545" host=127.0.0.1 method=PROPFIND pkg=rhttp proto=HTTP/1.1 service=storage size=0 start="29/Oct/2020:10:53:28 +0545" status=500 time_ns=54314206 traceid=a6c24d7f170923f20a589c99f5894289 uri=/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU2OjhjY2QyNzUxLTkwYTQtNDBmMi1iOWYzLTYxZWRmODQ0MjFmNA==/v url=/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU2OjhjY2QyNzUxLTkwYTQtNDBmMi1iOWYzLTYxZWRmODQ0MjFmNA==/v
```

**Comment by dpakach** [comment] 2020-11-25 04:50
Additional Note. Sending an invalid id, the server panics
```
curl https://localhost:9200/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjAzY2I1NzQ5LTE3ODUtNDI2Yi04ZmNjLWFhOWRhMmVjNzjMQ\=\=/v -ksv -u einstein:relativity 
> GET /remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjAzY2I1NzQ5LTE3ODUtNDI2Yi04ZmNjLWFhOWRhMmVjNzjMQ==/v HTTP/1.1
> Host: localhost:9200
> Authorization: Basic ZWluc3RlaW46cmVsYXRpdml0eQ==
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< Date: Wed, 25 Nov 2020 04:47:31 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

```

On Server
```
e20e58 uri=/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjAzY2I1NzQ5LTE3ODUtNDI2Yi04ZmNjLWFhOWRhMmVjNzRjMQ==/v url=/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjAzY2I1NzQ5LTE3ODUtNDI2Yi04ZmNjLWFhOWRhMmVjNzRjMQ==/v
2020-11-25T10:32:31+05:45 INF access-log from=127.0.0.1:44736 method=GET path=/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjAzY2I1NzQ5LTE3ODUtNDI2Yi04ZmNjLWFhOWRhMmVjNzjMQ==/v service=proxy
2020-11-25 10:32:31.918384 I | http: panic serving 127.0.0.1:35968: runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
net/http.(*conn).serve.func1(0xc0012f2000)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x3589340, 0x55fbfc0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.wrapResourceID(...)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/ocdav.go:194
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*VersionsHandler).Handler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7800)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/versions.go:49 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc0012faea0, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*MetaHandler).Handler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7800)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/meta.go:54 +0x183
net/http.HandlerFunc.ServeHTTP(0xc0012fae80, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*DavHandler).Handler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7700)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/dav.go:130 +0xd04
net/http.HandlerFunc.ServeHTTP(0xc0012fae60, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7700)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*svc).Handler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7600)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/ocdav.go:177 +0x8b8
net/http.HandlerFunc.ServeHTTP(0xc0001a98f0, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7500)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a2d0, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.(*Server).getHandler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7500)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:244 +0x46b
net/http.HandlerFunc.ServeHTTP(0xc0012e8010, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7400)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a6c0, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7400)
	/home/dipakacharya/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc0012e6200, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7300)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a7b0, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/auth.New.func1.1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7200)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/interceptors/auth/auth.go:245 +0xe9d
net/http.HandlerFunc.ServeHTTP(0xc0012b6240, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc0012f9620, 0xc0012f7100)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a7e0, 0x7fb2944cb280, 0xc0012f9620, 0xc0012f7100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/log.loggingHandler.ServeHTTP(0x3f84c40, 0xc00129a7e0, 0x3fd6960, 0xc001309310, 0xc0012f7100)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/interceptors/log/log.go:57 +0x297
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x3fd6960, 0xc001309310, 0xc0012f7000)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a810, 0x3fd6960, 0xc001309310, 0xc0012f7000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/appctx.handler.func1(0x3fd6960, 0xc001309310, 0xc0012f6f00)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/interceptors/appctx/appctx.go:52 +0x5e9
net/http.HandlerFunc.ServeHTTP(0xc00037e150, 0x3fd6960, 0xc001309310, 0xc0012f6f00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc0003d44b0, 0x3fd6960, 0xc001309310, 0xc0012f6d00)
	/home/dipakacharya/go/pkg/mod/go.opencensus.io@v0.22.5/plugin/ochttp/server.go:92 +0x2b9
net/http.serverHandler.ServeHTTP(0xc0002388c0, 0x3fd45a0, 0xc000238a80, 0xc0012f6d00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0012f2000, 0x3fe1ee0, 0xc001282080)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
2020-11-25 10:32:31.918936 I | http: panic serving 127.0.0.1:36036: runtime error: invalid memory address or nil pointer dereference
goroutine 48 [running]:
net/http.(*conn).serve.func1(0xc0012f20a0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x3589340, 0x55fbfc0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.wrapResourceID(...)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/ocdav.go:194
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*VersionsHandler).Handler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332400)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/versions.go:49 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc0012e6ca0, 0x7fb2944cb280, 0xc00129ae70, 0xc001332400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*MetaHandler).Handler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332400)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/meta.go:54 +0x183
net/http.HandlerFunc.ServeHTTP(0xc0012e6c80, 0x7fb2944cb280, 0xc00129ae70, 0xc001332400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*DavHandler).Handler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332300)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/dav.go:130 +0xd04
net/http.HandlerFunc.ServeHTTP(0xc0012e6c60, 0x7fb2944cb280, 0xc00129ae70, 0xc001332300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*svc).Handler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332200)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/services/owncloud/ocdav/ocdav.go:177 +0x8b8
net/http.HandlerFunc.ServeHTTP(0xc0001a98f0, 0x7fb2944cb280, 0xc00129ae70, 0xc001332200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332100)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a2d0, 0x7fb2944cb280, 0xc00129ae70, 0xc001332100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.(*Server).getHandler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332100)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:244 +0x46b
net/http.HandlerFunc.ServeHTTP(0xc0012e8010, 0x7fb2944cb280, 0xc00129ae70, 0xc001332100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332000)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a6c0, 0x7fb2944cb280, 0xc00129ae70, 0xc001332000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc001332000)
	/home/dipakacharya/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc0012e6200, 0x7fb2944cb280, 0xc00129ae70, 0xc001332000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc0006a9f00)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a7b0, 0x7fb2944cb280, 0xc00129ae70, 0xc0006a9f00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/auth.New.func1.1(0x7fb2944cb280, 0xc00129ae70, 0xc0006a9e00)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/interceptors/auth/auth.go:245 +0xe9d
net/http.HandlerFunc.ServeHTTP(0xc0012b6240, 0x7fb2944cb280, 0xc00129ae70, 0xc0006a9e00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb2944cb280, 0xc00129ae70, 0xc0006a9d00)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a7e0, 0x7fb2944cb280, 0xc00129ae70, 0xc0006a9d00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/log.loggingHandler.ServeHTTP(0x3f84c40, 0xc00129a7e0, 0x3fd6960, 0xc0003d4640, 0xc0006a9d00)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/interceptors/log/log.go:57 +0x297
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x3fd6960, 0xc0003d4640, 0xc0006a9c00)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a810, 0x3fd6960, 0xc0003d4640, 0xc0006a9c00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/appctx.handler.func1(0x3fd6960, 0xc0003d4640, 0xc0006a9b00)
	/home/dipakacharya/go/pkg/mod/github.com/cs3org/reva@v1.4.1-0.20201123062044-b2c4af4e897d/internal/http/interceptors/appctx/appctx.go:52 +0x5e9
net/http.HandlerFunc.ServeHTTP(0xc00037e150, 0x3fd6960, 0xc0003d4640, 0xc0006a9b00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc0003d44b0, 0x3fd6960, 0xc0003d4640, 0xc0012f7900)
	/home/dipakacharya/go/pkg/mod/go.opencensus.io@v0.22.5/plugin/ochttp/server.go:92 +0x2b9
net/http.serverHandler.ServeHTTP(0xc0002388c0, 0x3fd45a0, 0xc001304000, 0xc0012f7900)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0012f20a0, 0x3fe1ee0, 0xc001282ac0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
2020-11-25 10:32:31.919090 I | http: proxy error: EOF
```

**Comment by wkloucek** [comment] 2021-03-12 10:41
@individual-it I can reproduce both examples given by you in this issue but I cannot find them in the feature files. There are different examples in there. Could you add these two too or did I miss something?

https://github.com/owncloud/core/blob/191438a3b26608e0c84ec4a3015d0999f031f986/tests/acceptance/features/apiVersions/fileVersions.feature#L384-L397

**Comment by individual-it** [comment] 2021-03-12 11:07
@wkloucek you are pointing to the correct tests, those are the tests that show how I think the requests should work

**Comment by individual-it** [comment] 2021-03-12 11:24
you are right the base64 in https://github.com/owncloud/core/blob/191438a3b26608e0c84ec4a3015d0999f031f986/tests/acceptance/features/apiVersions/fileVersions.feature#L384 decodes to an invalid string `1284d238-aa92-42ce-bd�4-0b0000009156:8ccd2751-90a4-40f2-b9f3-61edf84421f4`

ToDo QA:team: 
- [ ] move example from L384 to example table below
- [ ] change scenario in L384 to a valid id e.g. `MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU2OjhjY2QyNzUxLTkwYTQtNDBmMi1iOWYzLTYxZWRmODQ0MjFmNA==`

**Comment by kobergj** [comment] 2024-06-04 09:32
Closing this because it is *probably* fixed by now.

**Closed by kobergj** 2024-06-04 09:32 UTC
Labels: Type:Bug, Category:Defect

**Comment by phil-davis** [comment] 2024-06-04 09:42
`fileVersions.feature` tests are all passing nowadays, and that was mentioned above as an example failing test scenario. And issue 772 is not mention in expected-failures. So yes, I suppose that this was fixed.
