### ISSUE TITLE
public links allow upload and delete as 'viewer'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#406] opened 2020-07-22 18:23 UTC
Reproduce on ocis 1.0.0-beta8 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

firefox https://xxx.xxx.xxx.xxx:9200

* log in as einstein,
* create a folder `jw`
* create a public link by clicking on the broken chain icon of `jw`

![image](https://user-images.githubusercontent.com/1108546/88212887-40870400-cc58-11ea-8604-4799bf9d47b2.png)
* the public link is expired immediately after creation.

* upload a file into folder `jw`
* open an anonymous browsing tab with the public link.
* use '+ New' to upload another file into the folder.
* delete the exising files.

Expected behaviour:
* the public links is not expired immediately after creation. (see screenshot)
* the public link neither allows upload nor delete, as it is viewer.

**Comment by individual-it** [comment] 2020-07-27 03:01
duplicate of https://github.com/owncloud/ocis-reva/issues/292 ?

**Comment by micbar** [comment] 2020-07-28 15:49
Correct. Known limitiation.

Let us keep the reva issue

**Closed by micbar** 2020-07-28 15:49 UTC
Labels: qa
