### ISSUE TITLE
Requesting a file preview when it is disabled by the administrator

### ISSUE THREAD

**Issue by swoichha** [owncloud/ocis#192] opened 2020-04-08 08:46 UTC
# Steps to reproduce
-  Administrator disables the generation of previews by setting `'enable_previews' => false` 
- User downloads the preview of file with width "32" and height "32" 
e.g. `curl http://172.17.0.1:9140/remote.php/dav/files/admin/parent.txt\?x\=32\&y\=32\&forceIcon\=0\&preview\=1 -u admin:admin -v` 

# Expected
-  HTTP code 404 - Not Found

# Actual
- HTTP code 200 - OK

**Comment by refs** [comment] 2021-01-12 10:18
tested with:

server: `OWNCLOUD_ENABLE_PREVIEWS=false OCIS_LOG_PRETTY=true PROXY_ENABLE_BASIC_AUTH=true go run cmd/ocis/main.go server`

client: `curl -k https://localhost:9200/remote.php/dav/files/admin/docker\?x\=32\&y\=32\&forceIcon\=0\&preview\=1 -u admin:admin -v`

Got: `400`
Expected: `404`

**Comment by C0rby** [comment] 2021-04-12 11:09
AFAIK, we don't support the flag `OWNCLOUD_ENABLE_PREVIEWS`.

The service returns 400 because the request doesn't contain the etag but that will be resolved with this PR: https://github.com/owncloud/ocis/pull/1898

**Comment by kiranparajuli589** [comment] 2021-05-24 06:18
the endpoint still returns 200
https://drone.owncloud.com/owncloud/ocis/5106/24/6

**Comment by micbar** [comment] 2022-05-11 19:05
@C0rby Is that now possible to switch off?

**Comment by C0rby** [comment] 2022-06-22 08:23
No, it's not.

**Comment by kulmann** [comment] 2023-06-22 14:15
I don't support the expected behaviour. The option was only ever meant for speeding up the file list rendering. Doesn't mean that the thumbnail service should forbid rendering thumbnails or larger previews in other situations. E.g. the thumbnail service is used to render an image with relatively high resolution in the "preview" app, where you can browse through images in a folder.
In my opinion ocis behaves like it should and this issue should be closed without changing anything.

**Comment by kulmann** [comment] 2023-06-22 14:34
Please discuss with @JammingBen @tbsbdr or @micbar I'm out of office for a while. Just stumbled over this in my github notifications.

**Comment by dragonchaser** [comment] 2023-06-23 11:12
We have discussed with @micbar & @kobergj:

- we will not disable the thumbnail service via the runtime (if needed this can be done through the `OCIS_EXCLUDE_RUN_SERVICES` env variable
- we will add a specific variable to allow webdav to disable previews
- we will not deprecate the web specific variable to disable previews
- we will also add a global env variable to disable the previews in both services

**Closed** 2023-06-27 13:29 UTC
Labels: Type:Bug, Category:Defect
