### ISSUE TITLE
access ocis before docker container fully started breaks it

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#2964] opened 2022-01-14 09:18 UTC
## Describe the bug

sometimes the docker container starts in a way that makes it impossible to upload files
It seems to be triggered more if access already come in when the container is still starting, but not sure if its limited to that

## Steps to reproduce

1. run requests in a loop `while true; do curl --head --fail --insecure "https://localhost:9200/"; done`
2. start docker `docker run  --rm --publish 9200:9200 --name ocis owncloud/ocis`
3. login to web (do it fast)
4. be unlucky

## Expected behavior
web works normal, files can be uploaded

## Actual behavior
no files can be uploaded
![grafik](https://user-images.githubusercontent.com/2425577/149489916-33dc48df-c65f-4299-88f1-95092fb36cf6.png)

**Comment by wkloucek** [comment] 2022-01-20 11:54
Error looks the same as https://github.com/owncloud/ocis/issues/2995 (404 on webdav propfind)
Possible fix https://github.com/cs3org/reva/pull/2457

**Comment by rhafer** [comment] 2024-08-21 08:11
I am not able to reproduce this issue with the latest ocis-rolling. I am closing this. Please re-open if it re-appears.

**Closed by rhafer** 2024-08-21 08:10 UTC
Labels: Type:Bug
