### ISSUE TITLE
Same users can be added in a group multiple time

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#5702] opened 2023-03-02 04:06 UTC
## Describe the bug

Add users to a group at once. Again try to add the same users in the same group then we have a 204  status code.
Both endpoints to add members to the group behave in the same way
- Adding a single member to a group
- Adding multiple members in a single request

## Steps to reproduce

1. add users to a group at once
```
curl --location --request PATCH 'https://localhost:9200/graph/v1.0/groups/bdac72d5-1bfe-42ea-849d-72c52f885980/' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data-raw '{
    "members@odata.bind": [
        "https://localhost:9200/graph/v1.0/users/4c510ada-c86b-4815-8820-42cdf82c3d51",
        "https://localhost:9200/graph/v1.0/users/058bff95-6708-4fe5-91e4-9ea3d377588b"
    ]
}'
```
2. Again add same user to same group 
```
curl --location --request PATCH 'https://localhost:9200/graph/v1.0/groups/bdac72d5-1bfe-42ea-849d-72c52f885980/' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data-raw '{
    "members@odata.bind": [
        "https://localhost:9200/graph/v1.0/users/4c510ada-c86b-4815-8820-42cdf82c3d51",
        "https://localhost:9200/graph/v1.0/users/058bff95-6708-4fe5-91e4-9ea3d377588b"
    ]
}'
```

## Expected behavior
Some error message should be thrown/

## Actual behavior
Gives Http status code `204` 

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by amrita-shrestha** [comment] 2023-03-02 04:32
@ScharfViktor  @kulmann  Is this a bug or feature?

**Comment by rhafer** [comment] 2023-03-02 09:21
The spec is really clear about the correct behavior here. So we just tried this on the MS Graph APIs, there you get an error:

Status Code: 400 
```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "One or more added object references already exist for the following modified properties: 'members'.",
        "innerError": {
            "date": "2023-03-02T09:01:20",
            "request-id": "5ef365ba-e185-4acb-a980-c15e7fb094fb",
            "client-request-id": "00cac98e-3a83-17cd-98ba-9b7a4775f720"
        }
    }
}
```

So it's a bug, not a feature. However, likely not a blocker, as long as the user doesn't show up multiple times when listing the members.

**Comment by rhafer** [comment] 2023-03-21 10:22
This seems to be a duplicate of #5855

**Closed by rhafer** 2023-03-21 10:22 UTC
Labels: Type:Bug

**Comment by rhafer** [comment] 2023-03-21 12:01
Actually I was a bit too quick with closing this as a duplicate. This issue happens when sending the same request twice. The second time the graph service will basically detect that there is nothing to do (both users are already a member of the group) and return a 204. MSGraph otoh treats this as an error and returns a 400.
