### ISSUE TITLE
`PROPFIND` for personal space is flaky

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#4597] opened 2022-09-15 11:42 UTC
## Describe the bug
We noticed that the `PROPFIND` for the personal space is flaky on current master.

## Steps to reproduce

1. Curl your personal space a few ties: `curl -X PROPFIND https://localhost:9200/remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157%2412a30d44-3145-4659-9a86-b4cfdc4e3d19 -k -u admin:admin -i`

## Expected behavior
A consistent `207` response.

## Actual behavior
From time to time, oCIS returns a `502: Bad gateway`

**Comment by rhafer** [comment] 2022-09-15 12:40
This is basically a duplicate of https://github.com/owncloud/ocis/issues/3134

Happens when multiple ocis instances (all using the mdns registry) are running in the same network. This results in both instance "seeing" each others service registrations -> :bomb: :boom:

**Comment by micbar** [comment] 2022-09-19 07:06
closing because of duplicate.

**Closed by micbar** 2022-09-19 07:06 UTC
Labels: Type:Bug
