### ISSUE TITLE
Overwriting a file in the space within the allowed quota does not work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#2829] opened 2021-11-29 20:50 UTC
## Describe the bug

Api test for case: https://github.com/owncloud/ocis/tree/apiTestQuota

## Steps to reproduce

1. Create Space with quota 15 Bytes
2. Upload file 7 bytes to space: `curl -k https://localhost:9200/dav/spaces/{space_id}/test.txt -X PUT -d "7 bytes" -v -u admin:admin`
3. Overwrite file "test.txt" 10 bytes: `curl -k https://localhost:9200/dav/spaces/{space_id}/test.txt -X PUT -d "0010 bytes" -v -u admin:admin`

## Expected behavior
the total quota is not exceeded by the new version of the file. The new file should be saved. 
expect: 204. used quota: 10. remaining quota: 5

## Actual behavior
error 507. File "test.txt" 10 Bytes does not overwrite

```console
OCIS_VERSION=1.15.0
```

</p>
</details>

**Comment by C0rby** [comment] 2022-05-11 13:35
@micbar  is that really the expected behavior?
When overwriting a file we are creating a new version. Do versions count into the quota?

**Comment by micbar** [comment] 2022-05-11 13:42
@C0rby Versions and trashbin do not count into the quota. It should already be implemented like that.

**Comment by C0rby** [comment] 2022-05-11 15:31
Ok, follow up question: In case the quota is exceeded let's say quota is 15 bytes and is 100% utilized, and the user overwrites a file with a bigger file, do we allow that? This means the user would effectively use more than 100% of their quota.

Storage (15 bytes quota):
- File1 (5 bytes)
- File2 (10 bytes)

Now overwrite File1 with a file containing 30 bytes.

Storage (15 bytes quota):
- File1 (30 bytes)
- File2 (10 bytes)

**Comment by micbar** [comment] 2022-05-11 18:23
> Ok, follow up question: In case the quota is exceeded let's say quota is 15 bytes and is 100% utilized, and the user overwrites a file with a bigger file, do we allow that? This means the user would effectively use more than 100% of their quota.

No, we do not allow exceeding the quota.

**Comment by C0rby** [comment] 2022-05-13 15:53
A fix has been implemented but the ticket is still open because Reva hasn't been updated in oCIS yet.

**Comment by kobergj** [comment] 2022-05-16 09:07
Fix has landed in ocis. Closing this...

**Closed by kobergj** 2022-05-16 09:07 UTC
Labels: OCIS-Fastlane, Estimation:XS(1), Type:Bug, Priority:p2-high, Topic:good-first-issue
