### ISSUE TITLE
[QA] share owner cannot access other users files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1118] opened 2020-12-16 14:11 UTC
Deployed ocis master 2020-12-15 13:00h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* login in as einstein, create folder 'for-marie', share with marie as editor.
* login as marie at a diffent browser session, accept the share, upload a png file.
* click on the png file, the media-viewer shows the file. OK
* with einstein's session: navigate into the folder 'for-marie', see that the png file is there.
* click on the png file, the media-viewer fails and shows an exclamation mark on a red triangle. BAD
* try download, rename, delete. all fails. BAD
* also share the folder with user moss
* log in as moss, accept, and test: everything is fine. Okayish

expected behaviour: the share owner should be able to view files too.

**Comment by individual-it** [comment] 2020-12-17 06:17
duplicate of #763

**Comment by refs** [comment] 2021-01-12 14:10
closing as duplicate of #763 

I also tried the described steps and can confirm is no longer happening.

**Closed by refs** 2021-01-12 14:10 UTC
