### ISSUE TITLE
ocis version also prints out an error not being able to connect to nats

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#8692] opened 2024-03-19 18:25 UTC
When running `ocis version` under the following conditions:

* Just downloaded, but before `ocis init`
* After `ocis init` but not started with `ocis server`

You get an output about `Failed to connect to NATS Server`: --> this should imho not be, only the version should get printed and no info about not started services...
```
ocis version
Version: 5.0.0
Compiled: 2024-03-18 00:00:00 +0000 UTC

could not list services: Failed to connect to NATS Server: nats: no servers available for connection
Failed to connect to NATS Server: nats: no servers available for connection
```

When ocis has started with `ocis server`, you get:
```
ocis version
Version: 5.0.0
Compiled: 2024-03-18 00:00:00 +0000 UTC

+---------+--------------------+--------------------------------------------------------------------------+
| Version |      Address       |                                    Id                                    |
+---------+--------------------+--------------------------------------------------------------------------+
| 5.0.0   | 127.0.0.1:9142     | com.owncloud.api.gateway-51c1e100-216d-49e5-8ee7-e58fddca0957            |
...
```

Finally when ocis is not running but you type `ocis version --skip-services` you only get the version printed:
```
Version: 5.0.0
Compiled: 2024-03-18 00:00:00 +0000 UTC
```
Using the parameter `--skip-services` is confusing at this stage.

**Expectation:**
* `ocis version` _only_ prints the version in any case 
* `--skip-services` does the same as above but when ocis has started

**Comment by dragonchaser** [comment] 2024-03-21 07:51
duplicate of #8070 solved in `master`

**Closed** 2024-03-21 07:52 UTC
Labels: Type:Bug
