### ISSUE TITLE
Feedback from AARNet

### ISSUE THREAD

**Issue by madsi1m** [owncloud/ocis#45] opened 2019-11-07 23:21 UTC
## Overview

We now have an almost working deployment of OCIS, here are some notes on what is not working/missing

### Environment

Phoenix [0.2.3](https://github.com/owncloud/phoenix/releases/download/0.2.3/phoenix.tar.gz)
Reva from github [Nov 7, 2019 e56ca76b99b163e8d27dad2630bf415fae73c16a](https://github.com/cs3org/reva/commit/e56ca76b99b163e8d27dad2630bf415fae73c16a)

### These are the things that currently do not work for us:

* Sharing buttons are missing in the UI
* Navigating into a sub folder does not work
* Media view can not get to /remote.php/dav/public-files//<<USER>>/image.png?stuff
* ~~example toml files do not work~~
(FIXED [fix configuration examples in separate folder by madsi1m · Pull Request #351 · cs3org/reva · GitHub](https://github.com/cs3org/reva/pull/351))
* /ocs/v2.php/apps/notifications/api/v1/notifications?format=json still misssing 404
* Trash bin does not work
* Favorites does not work
* Media viewer does not recognise mp4 as media
* Deleteing a file is broken
* Overwrite a file is broken

### These are the things that are currently missing:

* We authenticate via federated (almost) openid connect compatible end point. In the current model OCIS makes the assumption that the user must exist in the "basic auth". We need a way to create a user on successful login. At the moment it seems OCIS is smart enough to create missing user folders on first login but not create the user.
* Sync client compatibility, I am not able to add ocdav/frontend to the sync client as it tells me the "Host requires authentication"

**Comment by butonic** [comment] 2019-11-11 10:05
Tested with carrent example/separate config: https://github.com/cs3org/reva/commit/ac1b9619db30825e80c602e2746199ac4562fb32

- [ ] Sharing buttons are missing in the UI
  -  should be visible with the right capabilities, will test (jfd)
- [x] Navigating into a sub folder does not work
  - works with current example/separate config (jfd)
- [ ] Media view can not get to /remote.php/dav/public-files//<<USER>>/image.png?stuff
  -  net implemented yet (jfd)
- [x] ~~example toml files do not work~~
(FIXED [fix configuration examples in separate folder by madsi1m · Pull Request #351 · cs3org/reva · GitHub](https://github.com/cs3org/reva/pull/351))
- [ ] /ocs/v2.php/apps/notifications/api/v1/notifications?format=json still misssing 404
  -  net implemented, should be disabled with the right capabilities, will test (jfd)
- [ ] Trash bin does not work
  - confirmed, will debug
- [ ] Favorites does not work
  - confirmed
- [ ] Media viewer does not recognise mp4 as media
  - needs to be tested
- [ ] Deleteing a file is broken
  - works with current example/separate config (jfd)
- [ ] Overwrite a file is broken
  - needs to be tested

**Comment by DeepDiver1975** [comment] 2019-11-11 11:16
>     * Media viewer does not recognise mp4 as media

phoenix media viewer is currently only for images - videos to come

**Comment by butonic** [comment] 2019-11-11 12:36
@DeepDiver1975 is that tracked in phoenix or is there a dedicated repo for the mediaviewer?

**Comment by DeepDiver1975** [comment] 2019-11-11 12:49
>  is that tracked in phoenix o

in the phoenix repo - THX

**Comment by butonic** [comment] 2019-11-11 13:54
I either linked an existing issue, created a new one or could not reproduce the problem (likely due to a not up to date config). Feedback adressed -> closing.

**Closed by butonic** 2019-11-11 13:54 UTC

**Comment by madsi1m** [comment] 2019-12-09 05:07
The sync client points to /oauth2/.* which does not exist is our deployment as we do not have a oidcprovider in our frontend.toml. Do I need to add one? How to i link it to my external openidc provider?
