### ISSUE TITLE
500 on searches that contain ":"

### ISSUE THREAD

**Issue by diocas** [owncloud/ocis#7282] opened 2023-09-14 13:55 UTC
It seems that after adding KQL, a search like "test:test" is causing 500s in oCIS.

I didn't see any other issue reporting something similar, hope I didn't miss it.

**Comment by fschade** [comment] 2023-09-14 17:43
Thanks, we had a hack week, sorry for late answer!
I’ll have a look tomorrow morning.

**Comment by fschade** [comment] 2023-09-15 06:40
@diocas i had a look, no 500 here for me, i tested it locally using the latest master!

i used the following body for the request:
```
<?xml version="1.0"?>
<oc:search-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
    <oc:permissions />
    <oc:favorite />
    <oc:fileid />
    <oc:file-parent />
    <oc:name />
    <d:lockdiscovery />
    <d:activelock />
    <oc:owner-id />
    <oc:owner-display-name />
    <oc:shareid />
    <oc:shareroot />
    <oc:share-types />
    <oc:privatelink />
    <d:getcontentlength />
    <oc:size />
    <d:getlastmodified />
    <d:getetag />
    <d:getcontenttype />
    <d:resourcetype />
    <oc:downloadURL />
    <oc:tags />
  </d:prop>
  <oc:search>
    <oc:pattern>test:test</oc:pattern>
    <oc:limit>8</oc:limit>
  </oc:search>
</oc:search-files>
```

and received a 207 response.

Can you please show me how your request looks?

**Comment by fschade** [comment] 2023-09-15 07:40
now i think i got what you mean, you mean terms wrapped in quotation marks, for example `"test:test"`.
I can reproduce it with that term, but it looks like bleve is the problematic part in that case, not the kql parser.

I've also adde a testcase for that:
https://github.com/owncloud/ocis/blob/6eea04987b4b0505202558b77e66922cc64eed17/services/search/pkg/query/kql/dictionary_test.go#L1211

i have a look aftert my current kql pr is merged. cc.: @2403905

**Comment by diocas** [comment] 2023-09-15 08:43
Yes... I was using web, which has it's own way of creating the pattern:

```
<oc:pattern>name:&quot;*test:test*&quot;</oc:pattern>
```

**Comment by 2403905** [comment] 2023-09-15 08:51
We have to care about escaping the characters `+-=&|><!(){}[]^\"~*?:\\/ `  following  docs https://blevesearch.com/docs/Query-String-Query/

**Comment by fschade** [comment] 2023-09-15 09:36
> Yes... I was using web, which has it's own way of creating the pattern:

@diocas thanks for your report, will be fixed!

**Closed** 2023-09-15 16:31 UTC
Labels: Type:Bug
