### ISSUE TITLE
cannot run tests with docker

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#7071] opened 2023-08-18 20:47 UTC
I had assumed that I do not need any php on my machine because the tests run in docker constainers ... But I get a problem with php and the ldap extension ...
```
make -C tests/acceptance/docker localApiTests-apiGraph-ocis
[...]
behat composer.lock is not up to date.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-ldap 2.15.0 requires ext-ldap * -> it is missing from your system. Install or enable PHP's ldap extension.
    - laminas/laminas-ldap[2.16.0, ..., 2.17.0] require php ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (7.4; overridden via config.platform, actual: 8.2.9) does not satisfy that requirement.
    - Root composer.json requires laminas/laminas-ldap ^2.15 -> satisfiable by laminas/laminas-ldap[2.15.0, 2.16.0, 2.17.0].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-ldap` to temporarily ignore these required extensions.
make[1]: *** [Makefile:263: ../../../vendor-bin/behat/composer.lock] Fehler 2
make: *** [Makefile:145: localApiTests-apiGraph-ocis] Fehler 2
make: Verzeichnis „/home/jfd/Repositories/ocis/tests/acceptance/docker“ wird verlassen
```

**Comment by amrita-shrestha** [comment] 2023-08-22 11:54
Can't reproduce locally in ubuntu22.04 
- checked in both PHP version `image: owncloudci/php:8.0` and `image: owncloudci/php:7.4`

@butonic can you give more information like
- Operating system
- PHP version in your system?

**Comment by butonic** [comment] 2023-08-24 11:01
OS is arch based [Elementary OS](https://elementary.io/)

```console
✗ php -v
PHP 8.2.9 (cli) (built: Aug 13 2023 06:12:43) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.9, Copyright (c) Zend Technologies
```

I had assumed the docker based tests do NOT use my local PHP. That complicates things ...

**Comment by butonic** [comment] 2023-08-24 15:59
fix in https://github.com/cs3org/reva/pull/4134

**Closed** 2023-09-06 13:01 UTC
Labels: Type:Bug, QA:team
