### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by krsvital** [owncloud/ocis#3519] opened 2022-04-13 03:51 UTC
## Describe the bug

this error apears every fourth time when downloading shared file
url for checking:
https://mycloud.g-service.ru:4430/s/OyfqK3rxkMbeQej/download

## Steps to reproduce

download 4 times url above

## Expected behavior

content-length of file have to be equals to content-length in header

## Actual behavior

nginx logs:

84.22.140.8 - - [[12/Apr/2022:20:31:40 +0700]](https://trac.nginx.org/nginx/changeset/12/nginx/Apr/2022%3A20%3A31%3A40%20%2B0700) "GET /s/OyfqK3rxkMbeQej/download HTTP/1.1" 200 1075126 "[link]" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) [AppleWebKit]()/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29"
84.22.140.8 - - [[12/Apr/2022:20:31:44 +0700]](https://trac.nginx.org/nginx/changeset/12/nginx/Apr/2022%3A20%3A31%3A44%20%2B0700) "GET /s/OyfqK3rxkMbeQej/download HTTP/1.1" 200 1075126 "[link]" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) [AppleWebKit]()/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29"
84.22.140.8 - - [[12/Apr/2022:20:31:47 +0700]](https://trac.nginx.org/nginx/changeset/12/nginx/Apr/2022%3A20%3A31%3A47%20%2B0700) "GET /s/OyfqK3rxkMbeQej/download HTTP/1.1" 200 1075126 "[link]" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) [AppleWebKit]()/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29"
84.22.140.8 - - [[12/Apr/2022:20:31:51 +0700]](https://trac.nginx.org/nginx/changeset/12/nginx/Apr/2022%3A20%3A31%3A51%20%2B0700) "GET /s/OyfqK3rxkMbeQej/download HTTP/1.1" 200 637814 "[link]" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) [AppleWebKit]()/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29"

last content length is 637814 (have to be 1075126), but in header content length is correct

## Setup

owncloud is running with latest nginx version
answer from nginx about this problem:

https://trac.nginx.org/nginx/ticket/2343

<details>
<p>

```console
OCIS_VERSION=vX.X.X
BRANCH=v10.9.1
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by kobergj** [comment] 2024-06-07 14:26
Closing since it wasn't reproducible 2 years ago.

**Closed by kobergj** 2024-06-07 14:26 UTC
Labels: Type:Bug
