### ISSUE TITLE
Downloading the older version of shared file  as share receiver gives `403`

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#3868] opened 2022-05-25 06:29 UTC
## Describe the bug

It is not possible to download the older version of a shared file

## Steps to reproduce

1. As user `Marie` create a file 
`curl -X PUT -vk -u marie:radioactivity https://localhost:9200/remote.php/dav/files/marie/test.txt -d"original"`
2. overwrite the file 
`curl -X PUT -vk -u marie:radioactivity https://localhost:9200/remote.php/dav/files/marie/test.txt -d"version 1"`
3. Share the file with user `einstein` and accept the share 
4. find the file id 
`curl -X PROPFIND -vk -u einstein:relativity https://localhost:9200/remote.php/dav/files/einstein/Shares/test.txt | xmllint --format -`
5. get the version of the file
`curl -X PROPFIND -vk -u einstein:relativity https://localhost:9200/remote.php/dav/meta/<fileid>/v | xmllint --format -`
6. download data from the link mentioned in the href element 
`curl -X GET -vk -u einstein:relativity https://localhost:9200/<href>`

## Expected behavior
It should be possible to download the content of old version of the file

## Actual behavior
Gives `404` status code

## Setup

Current master

**Comment by ScharfViktor** [comment] 2022-06-21 14:52
ownCloud Web UI 5.5.0-rc.8 
Infinite Scale 2.0.0-beta.3+275b551cb 

I can't reproduce this on an actual master. 6 step gives me `200`

**Comment by JammingBen** [comment] 2022-11-17 12:30
I can also reproduce it, although I'm getting a `404` response. It can also be reproduced via Web:

* `userA` creates `somefile.txt` and edits it to create a new version
* `userA` shares `somefile.txt` with `userB`
* `userB` accepts the share on the "Shared with me"-page
* `userB` tries to download (`head` request) or revert (`copy` request) the previous version

**Comment by butonic** [comment] 2022-11-18 10:18
we are copying all extended attributes between versions and the code has these nice comments:
```

		err = xattrs.CopyMetadataWithSourceLock(targetPath, versionsPath, func(attributeName string) bool {
			return true
			// TODO determine all attributes that must be copied, currently we just copy all and overwrite changed properties
			/*
				return strings.HasPrefix(attributeName, xattrs.GrantPrefix) || // for grants
					strings.HasPrefix(attributeName, xattrs.MetadataPrefix) || // for arbitrary metadata
					strings.HasPrefix(attributeName, xattrs.FavPrefix) || // for favorites
					strings.HasPrefix(attributeName, xattrs.SpaceNameAttr) || // for a shared file
			*/
		}, lock)
```

That means that new grants do not apply to old versions ... hmm ... we may not even have to copy metadata at all ... since I only use the version nodes to keep track of the blob id ...

🤔 

would make the code a lot simpler ...

🤔 

since I am rewriting the FinishUpload code in https://github.com/cs3org/reva/pull/3473 already I can look

**Comment by butonic** [comment] 2022-11-18 11:55
fixed by https://github.com/cs3org/reva/pull/3473 ... but needs a review and reva ci has some hiccups.

**Closed** 2022-11-23 15:42 UTC
Labels: Type:Bug, Priority:p3-medium
