### ISSUE TITLE
Publicly shared image not visible via share link

### ISSUE THREAD

**Issue by pbek** [owncloud/ocis#1370] opened 2021-01-21 08:14 UTC
## Describe the bug

Publicly shared images are not visible via share link (not even to the owner).

## Steps to reproduce

1. Follow docker instructions on https://owncloud.github.io/ocis/getting-started/#docker
2. Upload image to https://localhost:9200
3. Publicly share image
4. Open link (e.g. `https://localhost:9200/#/s/DsXHhfQMnXvQYZE`)
5. See image file in folder
6. Click on image
7. See preview with no image

## Expected behavior

Be able to see image

## Actual behavior

<img width="991" alt="image" src="https://user-images.githubusercontent.com/1798101/105322274-ec3dec00-5bc8-11eb-8529-9ffbf72ca946.png">

## Setup

`docker run --rm -ti -p 9200:9200 owncloud/ocis` just now

`https://localhost:9200/remote.php/dav/public-files/DsXHhfQMnXvQYZE/paris.jpg?a=1&c=58abe4c96fa75ddcf3ce187d318c9e11&preview=1&scalingup=0` receives a 404 error.

**Comment by Rastaman3** [comment] 2021-01-21 15:44
This seems to be bug caused by different file extentions. 
If I click on ".jpg" Files, they will be visible. If I click on ".JPG" and ".jpeg" Files they are not.

**Comment by individual-it** [comment] 2021-01-25 06:12
ToDo QA-team:
- [ ] reproduce bug
- [ ] find out if the bug is only in public links
- [ ] add UI tests to cover the bug

**Comment by individual-it** [comment] 2021-01-25 06:20
duplicate of https://github.com/owncloud/web/issues/4647 ?

**Comment by jasson99** [comment] 2021-01-26 09:42
@Rastaman3 there are separate issues: https://github.com/owncloud/ocis/issues/1490 and https://github.com/owncloud/web/issues/4647

**Closed** 2021-04-28 07:54 UTC
Labels: Type:Bug
