### ISSUE TITLE
Mobile apps failing against ocis.owncloud.works

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ocis#897] opened 2020-11-19 10:08 UTC
Both mobile clients Android & iOS are not working agains `ocis.owncloud.works`

Authorization process against OIDC works, but the `PROPFIND` request against `/remote.php/dav/files` returns 500. This is the request body (iOS):

```
<?xml version="1.0" encoding="UTF-8"?>
<D:propfind xmlns:D="DAV:" xmlns:oc="http://owncloud.org/ns">
  <D:prop>
    <D:supported-method-set/>
  </D:prop>
</D:propfind>
```

Android is asking for something different, with the same result:

```
<propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav" xmlns:SABRE="http://sabredav.org/ns" xmlns:OC="http://owncloud.org/ns">
  <prop>
    <displayname />
    <getcontenttype />
    <resourcetype />
    <getcontentlength />
    <getlastmodified />
    <creationdate />
    <getetag />
    <quota-used-bytes />
    <quota-available-bytes />
    <OC:permissions />
    <OC:id />
    <OC:size />
    <OC:privatelink />
  </prop>
</propfind>
```

So, the mobile apps can not show the list of files.

**Comment by jnweiger** [comment] 2020-11-19 10:22
I'd assume the same would happen for an ocis-eos instance. 
Also: We are currently unable to provide an ocis-eos on a remote system. Only localhost deployments are currently possible.

Eiither of these blocks mobile testing.

**Comment by micbar** [comment] 2020-11-20 09:55
will be fixed by #https://github.com/owncloud/ocis/pull/823

**Comment by kulmann** [comment] 2020-11-26 20:45
While the PROPFIND returns a `405` now, we found out that it has to return a `207` when the header value `depth: 0` is set. Working on a fix.

**Comment by refs** [comment] 2020-11-27 08:53
as seen by @kulmann @michaelstingl and I, #823 did not fix this as the cause is the clients sending `depth 0` header. Looking into it now.

**Comment by kulmann** [comment] 2020-11-27 13:01
Should be fixed by https://github.com/owncloud/ocis/pull/971

**Comment by kulmann** [comment] 2020-11-27 13:11
Can confirm that the iOS login works again against ocis.owncloud.works
![IMG_3482](https://user-images.githubusercontent.com/3532843/100452974-7468af00-30ba-11eb-9411-46f9bfc4ebd4.png)

**Closed by kulmann** 2020-11-27 13:11 UTC
Labels: bug
