### ISSUE TITLE
Login issue with clients

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4754] opened 2022-10-07 06:59 UTC
## Describe the bug
I'm running into an issue when logging in for the first time: the user name is grayed out and can't be selected. Only when I open the OIDC login a second time can I select the account

## Steps to reproduce

1. have an oCIS with the builtin IDP
1. use iOS / Desktop Client
2. set up the client to sync

## Expected behavior
Login is possible on the first time

## Actual behavior
I can not select my user

https://user-images.githubusercontent.com/34452982/194486864-15399d0b-13ab-4dd7-a3b1-b2e412cf1b6f.mov

**Comment by micbar** [comment] 2022-10-07 07:02
duplicate of #4704

**Closed as completed** 2022-10-07 07:05 UTC
Labels: Type:Bug
