### ISSUE TITLE
[QA] RC7 mediaviewer fails to display images

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1058] opened 2020-12-10 21:01 UTC
Deployed ocis v1.0.0-rc7 via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/
* log in as user einstein via web UI
* upload a file screenshot.png
* click on the file name
![image](https://user-images.githubusercontent.com/1108546/101829202-f7661c80-3b32-11eb-8c6b-e3283c4b8f1e.png)
* the image is not shown. BAD
* click the download icon.
* The file is downloaded and displays nicely in a local Linux image viewer.

**Comment by wkloucek** [comment] 2020-12-16 09:45
Should have been fixed by #1068 !?  @jnweiger Can this be closed?

**Comment by refs** [comment] 2021-01-13 12:37
Just tested, cannot reproduce with the latest master.

**Closed by refs** 2021-01-13 12:37 UTC
Labels: Type:Bug, p3-medium
