### ISSUE TITLE
[QA][OCIS] 2.7-daily shows UUID instead of username

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1413] opened 2020-09-08 20:02 UTC
Tested with
* ocis-1.0.0-rc1 via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_eos_test.sh
* and desktop daily (20200908) client ownCloud version 2.7.0 (build 2058) 

![image](https://user-images.githubusercontent.com/1108546/92521843-362bc400-f21e-11ea-8e0e-d25d8817c16f.png)

the mouse over hover also has the UUID.
The UUID is also in the "Connected to ... as ..." string.

Expected behaviour:
* The full name "Albert Einstein" is shown, 
* The mouse over and the "Connected ... to ..." has the login name "einstein"

**Comment by phil-davis** [comment] 2021-02-22 07:37
@jnweiger this is an old issue that was transferred from the archived `ocis-ocs` repo a few weeks ago.
Please close if no longer relevant.

**Comment by pascalwengerter** [comment] 2021-06-10 19:40
@TheOneRing could you take another look and update/close the issue? :)

**Comment by TheOneRing** [comment] 2021-06-10 19:47
OK I can't read. But yes the issue is fixed in the server.

**Closed** 2021-06-10 19:46 UTC

**Comment by pascalwengerter** [comment] 2021-06-10 19:51
> OK I can't read. But yes the issue is fixed in the server.

Sorry, wasn't aware! Jürgen re-opened this with a screenshot that showed an obscure string as the username in September 2020 but perhaps it's fixed as you already said 😀
