### ISSUE TITLE
`Failed to get upload` in s3ng mode

### ISSUE THREAD

**Issue by Gentoli** [owncloud/ocis#7026] opened 2023-08-13 17:13 UTC
## Describe the bug

Error logs with `Failed to get upload` after upload via Windows client (VFS). Manually downloading the file gives success and a good checksum.

Not sure if this should be logged with this wording.

## Steps to reproduce

1. Create RGW bucket on ceph 
2. Setup ocis via Helm with `s3ng`
3. Upload files via Windows client (~16k files)
4. Check logs

## Expected behavior
No error logs or logs explains this might be expected and don't results in data loss or integrity issue. When the object is missing it should log a hard error message.

## Actual behavior
Error logs that may or may not be true.

Logs:
``` jsonl
{"level":"info","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","data-server":"http://storageusers:9158/data/simple/68a9497b-9168-439d-8a67-867b8d0fce4c","fn":"./<filename>","xs":"map[md5:100 unset:1000]","time":"2023-08-13T16:43:25.883900549Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230731132956-0fb5212d0551/internal/grpc/services/storageprovider/storageprovider.go:441","message":"file upload"}
{"level":"info","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","data-server":"http://storageusers:9158/data/tus/68a9497b-9168-439d-8a67-867b8d0fce4c","fn":"./<filename>","xs":"map[md5:100 unset:1000]","time":"2023-08-13T16:43:25.883958099Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230731132956-0fb5212d0551/internal/grpc/services/storageprovider/storageprovider.go:441","message":"file upload"}
{"level":"info","service":"storage-users","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-08-13T16:43:25.888151258Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230731132956-0fb5212d0551/internal/http/interceptors/auth/auth.go:195","message":"skipping auth check for: /data/tus/68a9497b-9168-439d-8a67-867b8d0fce4c"}
{"level":"error","error":"upload not found","uploadID":"68a9497b-9168-439d-8a67-867b8d0fce4c","time":"2023-08-13T16:46:16.339009506Z","caller":"github.com/cs3org/reva/v2@v2.15.1-0.20230731132956-0fb5212d0551/pkg/storage/utils/decomposedfs/decomposedfs.go:246","message":"Failed to get upload"}
{"level":"info","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","data-server":"http://storageusers:9158/data","ref":{"resource_id":{"storage_id":"be3a412d-1c2d-4cb0-b07a-cca0b07ed484","opaque_id":"96ef0599-864d-4332-a2fb-aa2f6fb454cb","space_id":"96ef0599-864d-4332-a2fb-aa2f6fb454cb"},"path":"./<filename>"},"time":"2023-08-13T16:49:42.204377676Z","line":"github.com/cs3org/reva/v2@v2.15.1-0.20230731132956-0fb5212d0551/internal/grpc/services/storageprovider/storageprovider.go:279","message":"file download"}
```

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

Helm values, everything is default other than storage:
<details>
<p>

```yaml
storageusers:
  persistence:
    enabled: true
    storageClassName: ceph-fs-replicated-ssd
  storageBackend:
    driver: s3ng
    driverConfig:
      s3ng:
        endpoint: "https://<s3-domain>"
        bucket: "ocis-storageusers-19154375-7ecf-4375-ba60-a68c51b30a26"
```
</p>
</details>

- using image set in chart (3.1.0-rc.1)
- file in question is ~70KiB

## Additional context

This is a fresh install.

**Comment by wkloucek** [comment] 2023-09-05 13:51
Looks like a duplicate of https://github.com/owncloud/ocis/issues/6962

Your S3 Bucket configuration seems not to be right. If you switch to oCIS 4.0.1 you'll see an error at upload time.

**Comment by wkloucek** [comment] 2023-10-23 08:54
@Gentoli please reopen / ping me if this didn't solve it for you

**Closed by wkloucek** 2023-10-23 08:54 UTC
Labels: Type:Bug

**Comment by Gentoli** [comment] 2024-03-25 00:50
@wkloucek 

This error message still exists after upgrading to 5.0.0-rc.2. I'm guessing this is a different issue than https://github.com/owncloud/ocis/issues/6962, since for me, it always was able to upload to the s3 bucket (I can see objects in the bucket). Right now I suspect it's a contributing cause for 
https://github.com/owncloud/ocis/issues/8720 which have major impact on the service. Let's follow up there.
