### ISSUE TITLE
ApiTest. Cases for copy/move between project/personal/shares jail

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4087] opened 2022-07-04 12:47 UTC
#### copy-paste:

from | from (role) | to | to (role) | Expected result
-- | -- | -- | -- | --
project | spaceAdmin/editor/viewer | project | spaceAdmin/editor | 201
project | spaceAdmin/editor | project | viewer | 403
project | spaceAdmin/editor/viewer | personal |   | 201
project | spaceAdmin/editor/viewer | share jail | editor | 201
project | spaceAdmin/editor/viewer | share jail | viewer | 403
  |   |   |   |  
personal |   | personal |   | tests is exist in core
personal |   | project | spaceAdmin/editor | 201
personal |   | project | viewer | 403
personal |   | share jail | editor | 201
personal |   | share jail | viewer | 403
  |   |   |   |  
share jail | editor | personal |   | 201
share jail | viewer | personal |   | 201
share jail | editor/viewer | project | spaceAdmin/editor | 201
share jail | editor/viewer | project | viewer | 403
share jail | editor/viewer | share jail | editor | 201
share jail | editor/viewer | share jail | viewer | 403

#### move:

from | from (role) | to | to (role) | Expected result
-- | -- | -- | -- | --
project | spaceAdmin/editor | project | spaceAdmin/editor | 201
project | spaceAdmin/editor | project | viewer | 403
project | viewer | project | spaceAdmin/editor/viewer | 403
project | spaceAdmin/editor | personal |   | 201
project | viewer | personal |   | 403
project | spaceAdmin/editor | share jail | editor | 201
project | spaceAdmin/editor | share jail | viewer | 403
project | viewer | share jail | editor/viewer | 403
  |   |   |   |  
personal |   | personal |   | tests is exist in core
personal |   | project | spaceAdmin/editor | 201
personal |   | project | viewer | 403
personal |   | share jail | editor | 201
personal |   | share jail | viewer | 403
  |   |   |   |  
share jail | editor | personal |   | 201
share jail | viewer | personal |   | 403
share jail | editor | project | spaceAdmin/editor | 210
share jail | editor | project | viewer | 403
share jail | viewer | project | spaceAdmin/editor/viewer | 403
share jail | editor | share jail | editor | 201
share jail | editor | share jail | viewer | 403
share jail | viewer | share jail | editor | 403

**Comment by ScharfViktor** [comment] 2022-07-04 15:17
I added cases for "copy files" and "move files". We can start to implement it. @individual-it Who wants to do it? Or I can do it myself

**Comment by individual-it** [comment] 2022-07-05 07:52
@SagarGi is working on COPY tests currently anyway, so he could do this also

**Comment by ScharfViktor** [comment] 2022-07-07 09:12
@SagarGi we can only implement moving inside one project space because we prevented moving here: https://github.com/cs3org/reva/pull/3035

**Comment by phil-davis** [comment] 2022-07-07 09:52
> @SagarGi we can only implement moving inside one project space because we prevented moving here: [cs3org/reva#3035](https://github.com/cs3org/reva/pull/3035)

I guess that we can have a scenario that attempts to move between 2 spaces, and expects some HTTP 4xx status, and checks that the original resource remains in its original place. That will prevent accidental regressions of the current behavior.

**Comment by ScharfViktor** [comment] 2022-07-07 10:26
> I guess that we can have a scenario that attempts to move between 2 spaces, and expects some HTTP 4xx status, and checks that the original resource remains in its original place. That will prevent accidental regressions of the current behavior.

Yes, you're right. I misspoke.

**Comment by micbar** [comment] 2022-07-07 17:12
The return status will be `502 Bad Gateway` according to WebDAV spec. This fix is already in reva.

@butonic already updated in ocis master?

**Comment by SagarGi** [comment] 2022-07-11 07:19
TODO QA Team:
- [ ] Implement `COPY` request between spaces 
- [ ] implement `MOVE` request between spaces

**Comment by SagarGi** [comment] 2022-07-18 03:35
> here an interesting case to try #4114

Tried it and has been fixed. Response is `502` moving between cross-space. No data loss.

**Comment by SagarGi** [comment] 2022-07-26 07:29
The tests has been added for `COPY` and `MOVE` operation as mentioned in the above tests plan by @ScharfViktor. This operation is only limited to file. we can also try different other combination to test copy api between spaces (since we cannot move files between spaces) or shall we close this issue @phil-davis @ScharfViktor @phil-davis ?

**Comment by ScharfViktor** [comment] 2022-07-26 09:23
> The tests has been added for `COPY` and `MOVE` operation as mentioned in the above tests plan by @ScharfViktor. This operation is only limited to file. we can also try different other combination to test copy api between spaces (since we cannot move files between spaces) or shall we close this issue @phil-davis @ScharfViktor @individual-it ?

I think to implement same tests to coping or moving folder don't make sence. I'd changed "file" to "folder with file' in some existing positive tests (not all) and check that folder after coping or moving contains file

**Comment by SagarGi** [comment] 2022-07-27 04:06
TODO QA Team:
- [ ] Implement `COPY` request between spaces for folder (see above comment https://github.com/owncloud/ocis/issues/4087#issuecomment-1195237093 to implement for folders)
- [ ] update extected to failure for copy and move request for spaces based on this comment https://github.com/owncloud/ocis/pull/4179#discussion_r929710641

**Comment by SagarGi** [comment] 2022-08-10 03:59
API Tests for copy and move has been added with https://github.com/owncloud/ocis/issues/4087#issuecomment-1180052193 and 
https://github.com/owncloud/ocis/pull/4313 as per the above test plan issue. so this issue can be closed.

**Closed by SagarGi** 2022-08-10 03:59 UTC
Labels: QA:team
