### ISSUE TITLE
Shares jail are available after disabling/deleting space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6154] opened 2023-04-26 13:35 UTC
Infinite Scale 3.0.0-rc.1 Community 
 ownCloud Web UI 7.0.0-rc.32 

Steps: 
- space admin creates project space
- add folder f1 with file to the space
- share folder f1 to einstein and create public link with role uploader
- einstein accepts folder
- public open link
- space admin disabled space or delete (same behavior)

Actual: as a user einstein I don't understand what happens. I haven't any message or notification. I see shared folder and I know that there were files that aren't there now

- folder Shares/f1 is exist for einstein but it's empty
<img width="1421" alt="Screenshot 2023-04-26 at 15 28 48" src="https://user-images.githubusercontent.com/84779829/234589917-25f6770f-b1d3-456b-8049-7581bac76d49.png">

- all actions are available but after clicking user gets 400 code 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/84779829/234590174-98b50d15-d7dc-4d19-b542-2802f5edc479.png">

- user can decline share and cannot accept again

- for public link available with enabled `drop files` button 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/84779829/234591430-65ade494-7820-468e-94b8-07591adbc981.png">

Expect:

**Comment by micbar** [comment] 2023-04-27 10:06
Very good finding!

IMO this "works as designed" but we have a bad design.


@butonic FYI

**Comment by micbar** [comment] 2023-04-27 12:38
@butonic @kobergj @aduffeck can we teach the share manager to not list shares for disabled spaces?

**Comment by butonic** [comment] 2023-05-02 10:01
The CS3 share manager (actually the jsoncs3 share manager implementation) should be unaware of resource state. ListShares should be dumb, return all shares and point to the resource. It will filter out expired shares because that is his responsibility.

For whatever reason the GetShare() implementation does a stat request, which it IMO should not make ... it is the responsibility of the consumer to verify if the resource still exists.

When a resource / folder / space is deleted we need to walk the tree to delete all shared resources ... should be an async process, similar to indexing. deleting a space can easily delete all shares in that space, but deleting a folder has to be smarter to invalidate all shares in that folder 🤔

**Comment by butonic** [comment] 2023-05-02 10:19
AFAICT this was cause by the stat cache. It has been disabled since rc1 because invalidating entries in the stat cache was too expensive. We currently rely on the more efficient filemetadata cache.

**Comment by micbar** [comment] 2023-05-08 13:01
should be fixed in RC.2

**Closed by micbar** 2023-05-08 13:01 UTC
Labels: Type:Bug, Topic:UX-Design, Priority:p1-urgent
