### ISSUE TITLE
[QA] Phoenix: folder view does not close 'new +' dialog, when switching folders.

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#563] opened 2020-09-14 21:48 UTC
tested with 
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)
xrootd -v:            v4.11.0
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1
</pre>
</details>

Reproducer:
* Log in as user einstein
* create new folder XXX
* change to folder XXX
* open the 'New +' dialog, but do not select anything.
* click on the home icon

the folder view changes back to home, but the New dialog remains open, obscuring parts of the listing
![image](https://user-images.githubusercontent.com/1108546/93141515-9ae69300-f6e4-11ea-9ddb-19b0a308af9e.png)

Expected behavior: modal dialog. Clicking something outside the dialog closes the dialog.

**Comment by pascalwengerter** [comment] 2021-06-10 19:25
We've updated the **New** button and dropdowns, can't reproduce on current `master` so closing as fixed 🧮

**Closed by pascalwengerter** 2021-06-10 19:25 UTC
Labels: Category:Defect, Type:Bug
