### ISSUE TITLE
apiWebdavMove2/moveShareOnOcis.feature test fails

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#4245] opened 2022-07-21 03:45 UTC
Build : https://drone.owncloud.com/owncloud/ocis/13692/49/7

```
Scenario Outline: Moving a folder out of a shared folder as the sharee and as the sharer                    # /drone/src/oc10/testrunner/tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature:103
    Given using <dav_version> DAV path                                                                        # FeatureContext::usingOldOrNewDavPath()
    And user "Brian" has been created with default attributes and without skeleton files                      # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Brian" has created the following folders                                                        # FeatureContext::userHasCreatedFollowingFolders()
      | path                     |
      | /testshare               |
      | /testshare/testsubfolder |
    And user "Brian" has uploaded file with content "test data" to "/testshare/testsubfolder/testfile.txt"    # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Brian" has created a share with settings                                                        # FeatureContext::userHasCreatedAShareWithSettings()
      | path        | testshare |
      | shareType   | user      |
      | permissions | change    |
      | shareWith   | Alice     |
    And user "Alice" has accepted share "/testshare" offered by user "Brian"                                  # FeatureContext::userHasReactedToShareOfferedBy()
    When user "<mover>" moves folder "<source_folder>/testsubfolder" to "/testsubfolder" using the WebDAV API # FeatureContext::userMovesFileUsingTheAPI()
    Then the HTTP status code should be "201"                                                                 # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the content of file "/testsubfolder/testfile.txt" for user "<mover>" should be "test data"            # FeatureContext::contentOfFileForUserShouldBe()
    And as "Alice" folder "<source_folder>/testsubfolder" should not exist                                    # FeatureContext::asFileOrFolderShouldNotExist()
    And as "Brian" folder "/testshare/testsubfolder" should not exist                                         # FeatureContext::asFileOrFolderShouldNotExist()

    Examples:
      | dav_version | mover | source_folder     |
      | old         | Alice | /Shares/testshare |
        HTTP status code 502 is not the expected value 201
        Failed asserting that 502 matches expected '201'.
      | old         | Brian | /testshare        |
        folder '/testshare/testsubfolder' should not exist. But it does exist and is a folder
      | new         | Alice | /Shares/testshare |
        HTTP status code 502 is not the expected value 201
        Failed asserting that 502 matches expected '201'.
      | new         | Brian | /testshare        |
      | spaces      | Alice | /Shares/testshare |
        HTTP status code 404 is not the expected value 201
        Failed asserting that 404 matches expected '201'.
      | spaces      | Brian | /testshare        |
```

The test for the move fails on the `old` webdav needs investigation on this.

**Comment by SwikritiT** [comment] 2022-07-21 04:24
Failed here too: https://drone.owncloud.com/owncloud/ocis/13664/51/7

**Comment by SagarGi** [comment] 2022-07-21 11:23
This tests fail was seen during merge and in a PR And is not reproducable locally. Seems like in CI the move request worked as copy. I tried to fail it re running the failed scenrios in CI but is not reproduced. Build :  https://github.com/owncloud/ocis/pull/4249. I made a debug feature as `moveOcis.feature` to reproduce it but didnt fail. This can be put into backlog. If seen then can be reinvestigated.

**Comment by micbar** [comment] 2022-07-26 10:19
@tbsbdr @kulmann We need to take care of the user for cross space MOVE and inform him.

He needs to be notified. We need to decide

- Copy also the metadata?
- Need to be informed that shares are dropped.
- Keep the source file or delete? Delete always needs to be a conscious decision.

## Option

This problem occurs when doing `Ctrl+X` and browse to another space and then do `Ctrr+V`. In this case we could simply inform the user that this is not possible but offer a "Copy here". This would let him finish his task with a different but valid outcome.

**Comment by tbsbdr** [comment] 2022-07-26 14:17
> *   Copy also the metadata?

*   **default:** keep as many metadata as possible like Tags, Version, Exif-data and all in the future (As a user I would expect that all metadata as possible are kept)
*   **Drop Shares:** Shares and links are dropped
*   **Confirmation Dialog:** We would need a dialog that informs the user about loosing shares & links.
*   **Versions:** Must be kept. This is especially important as soon as we have approval processes for major versions and the possibility to track, who approved which version.

> *   Need to be informed that shares are dropped.

*   **Dialogue shows up on paste:** "Change who has access? Everyone who can see \<resourcename 1>, \<resourcename 2>, \<resourcename 3> (+84 more items) will lose access. \[Cancel\]\[Move\]"

> *   Keep the source file or delete? Delete always needs to be a conscious decision.

*   **Delete:** Source should be deleted, but moved to the trash bin so that it could be restored by other Space members who might miss that file.

How many days would the above delay the GA in contrast to just providing a copy (including the Dialogue above)?

**Comment by SwikritiT** [comment] 2022-11-28 03:57
This issue hasn't been reproduced in a long time. I'll run the tests locally few times to be extra sure and close the issue, if it doesn't reoccur

**Comment by SwikritiT** [comment] 2022-11-28 08:57
The test has been split into two maybe due to some refactoring that we usually do on test cases
https://github.com/owncloud/core/blob/1a79c5d1d34f2619a9807610b11646e76a4f2789/tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature#L104

https://github.com/owncloud/core/blob/1a79c5d1d34f2619a9807610b11646e76a4f2789/tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature#L129

But both the scenarios pass locallyon multiple runs. Closing this issue as complete

**Closed by SwikritiT** 2022-11-28 08:57 UTC
Labels: QA:team
