### ISSUE TITLE
[Sharing NG] Inviting multiple people does not work

### ISSUE THREAD

**Issue by JammingBen** [owncloud/ocis#8402] opened 2024-02-08 10:31 UTC
## Describe the bug
Inviting multiple people at the same time via the `recipients` prop does not work.

## Steps to reproduce
1. Create a file
2. Share that file with 2 or more users (payload: `{"roles":["b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5"],"recipients":[{"objectId":"f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c","@libre.graph.recipient.type":"user"},{"objectId":"058bff95-6708-4fe5-91e4-9ea3d377588b","@libre.graph.recipient.type":"user"}]}
`).

## Expected behavior
The file should be shared with all the given users.

## Actual behavior
The server throws an error `Key: 'DriveItemInvite.Recipients' Error:Field validation for 'Recipients' failed on the 'len' tag`.

**Comment by rhafer** [comment] 2024-02-08 11:01
This is basically a duplicate of https://github.com/owncloud/ocis/issues/7962. That ticket has a lengthy discussion about why we don't currenty support adding mulitple recipients at once.

The plan is to add it in the future though.

**Closed by rhafer** 2024-02-08 11:01 UTC
Labels: Type:Bug
