### ISSUE TITLE
[QA] Remove the data row from data table

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#8349] opened 2024-02-02 08:57 UTC
Previously we used `resourceType` in step implementation to get the `itemId`. We used two methods `getResourceId` for a folder and `getFileId` for a file. Now, we use only `getResourceId` to get an ID for both file and folder. `resourceType` is no more in use so we can remove that from the data table given in the step.

Files to be refactored:
- [x] `apiSharingNg/shareInvitations.feature` https://github.com/owncloud/ocis/pull/8369
- [x] `apiSharingNg/sharedByMe.feature` https://github.com/owncloud/ocis/pull/8369
- [x] `apiSharingNg/deletePermissions.feature` https://github.com/owncloud/ocis/pull/8370
```
When user "Alice" sends the following share invitation using the Graph API:
      | resourceType    | <resource-type>    |
      | resource        | <path>             |
      | space           | Personal           |
      | sharee          | Brian              |
      | shareType       | user               |
      | permissionsRole | <permissions-role> |
```
```
Given user "Alice" has sent the following share invitation:
      | resourceType    | file         |
      | resource        | textfile.txt |
      | space           | Personal     |
      | sharee          | Brian        |
      | shareType       | user         |
      | permissionsRole | Viewer       |
```
and refactor an example table where needed.

- [x] `apiSharingNg/linkShare.feature`
Also, make the necessary changes in step implementation for this step. https://github.com/owncloud/ocis/pull/8370
```
When user "Alice" creates the following link share using the Graph API:
      | resourceType    | folder            |
      | resource        | folder            |
      | space           | Personal          |
      | permissionsRole | <permissionsRole> |
      | password        | %public%          |
```

**Comment by S-Panta** [comment] 2024-02-09 10:10
Closing this PR as the issue is solved by https://github.com/owncloud/ocis/pull/8369 and https://github.com/owncloud/ocis/pull/8370

**Closed by S-Panta** 2024-02-09 10:10 UTC
Labels: QA:team
