### ISSUE TITLE
CORS on /data does not work

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#8380] opened 2024-02-06 13:58 UTC
## Describe the bug
Set `OCIS_CORS_ALLOW_ORIGINS="https:/foobar.com"` when `OCIS_URL=https://something.else`

## Steps to reproduce
1. create an upload and use tus from https:/foobar.com (this is a cross origin scenario!)

## Expected behavior
The upload works

## Actual behavior
The upload fails because the OPTIONS request on /data doesn#t return thre right CORS header.

Responses on other routs contain this header, while /data doesn't:
`Access-Control-Allow-Origin: https:/foobar.com`

## Setup

oCIS 5.0.0-rc.3 deployed with the oCIS Chart from next (https://github.com/owncloud/ocis-charts/commit/ebbd8c0dbadbe61ae21afa66968400e3f236b468)

**Comment by DeepDiver1975** [comment] 2024-02-06 14:47
Which version of tusd are you using? In late 2023 cors handling was added to tusd ...

see https://github.com/tus/tusd/pull/987  & https://github.com/tus/tusd/pull/997

Let me know if you need a helping hand ....

**Comment by wkloucek** [comment] 2024-02-07 05:56
> Which version of tusd are you using? In late 2023 cors handling was added to tusd ...
> 
> see [tus/tusd#987](https://github.com/tus/tusd/pull/987) & [tus/tusd#997](https://github.com/tus/tusd/pull/997)
> 
> Let me know if you need a helping hand ....

As said, it's oCIS 5.0.0-rc.3 and I don't know if it has incorporated those changes.

**Comment by DeepDiver1975** [comment] 2024-02-07 14:21
tusd is integrated via reva
in order to set the cors configuration in tusd reva needs to be patched here https://github.com/owncloud/ocis/blob/5362f82efaf78ae25496626f91171315bf7676f2/vendor/github.com/cs3org/reva/v2/pkg/rhttp/datatx/manager/tus/tus.go#L94

**Comment by micbar** [comment] 2024-02-07 19:02
assigning @butonic 
work in https://github.com/cs3org/reva/pull/4507

**Comment by butonic** [comment] 2024-02-19 09:35
reva part got merged. reva bump in ocis that also contains the necessary configuration is in https://github.com/owncloud/ocis/pull/8412

**Comment by butonic** [comment] 2024-02-21 10:54
https://github.com/owncloud/ocis/pull/8412 took a while to turn green, but is now merged.

**Comment by wkloucek** [comment] 2024-03-13 14:11
Not fixed, tested with 5.0.0-rc.5:

![Screenshot_2024-03-13_15-08-12](https://github.com/owncloud/ocis/assets/34452982/d42b948c-956e-44ff-aa51-66af8120940b)

**Comment by micbar** [comment] 2024-03-13 14:17
There is a passing test. See linked PR.

Are you sure that rc.5 should already work?

**Comment by micbar** [comment] 2024-03-13 14:20
rc.5 should work.

Did you configure it?

The new defaults are not targeting ocis 5.0.0 #8514

**Comment by micbar** [comment] 2024-03-13 14:39
@butonic Can you help? You did the reva fix. Was there something missing on the ocis side?

**Comment by wkloucek** [comment] 2024-03-14 06:18
> Did you configure it?

Sure, `OCIS_CORS_ALLOW_ORIGINS` is explicitly set, see description of this issue.


Actually the OPTIONS call responds correctly for `Access-Control-Request-Method: HEAD` but not for `Access-Control-Request-Method: PATCH`

> There is a passing test. See linked PR.

I didn't see a obvious link / result fore the passing test. I just saw the whole REVA testsuite passing. Does the test suite cover OPTIONS calls for different request methods?

**Comment by saw-jan** [comment] 2024-03-14 06:25
I see this test scenario with OPTIONS request:
https://github.com/owncloud/ocis/blob/b72e5ceddf5ccbab19b63830dca9dc942aa5b12a/tests/acceptance/features/apiCors/cors.feature#L54-L72

**Comment by wkloucek** [comment] 2024-03-14 06:26
Actually there was another change touching the same code path: https://github.com/cs3org/reva/pull/4527

**Comment by wkloucek** [comment] 2024-03-14 06:27
> I see this test scenario with OPTIONS request:
> 
> https://github.com/owncloud/ocis/blob/b72e5ceddf5ccbab19b63830dca9dc942aa5b12a/tests/acceptance/features/apiCors/cors.feature#L54-L72

But that one is about OCS API and not the reva data gateway :thinking:

**Comment by saw-jan** [comment] 2024-03-14 06:32
>But that one is about OCS API and not the reva data gateway 🤔

I am only aware of the public API level. if the /data is an internal service level thing then I have no idea :sweat_smile:

**Comment by wkloucek** [comment] 2024-03-14 06:34
> I am only aware of the public API level. if the /data is an internal service level thing then I have no idea 😅

That's a public API :wink: It's part of the TUS upload flow

**Comment by saw-jan** [comment] 2024-03-14 06:45
>That's a public API 😉 It's part of the TUS upload flow

Ahh, then I don't the test coverage related to that (at least not for OPTIONS to  /data with different methods)

**Comment by saw-jan** [comment] 2024-03-14 06:48
do you think adding these to the above test scenario will cover your cases?
```feature
| 2 |  /data | HEAD           |
| 2 |  /data | PATCH          |
```

**Comment by wkloucek** [comment] 2024-03-14 06:51
> do you think adding these to the above test scenario will cover your cases?
> 
> ```
> | 2 |  /data | HEAD           |
> | 2 |  /data | PATCH          |
> ```

From what I saw in the code of https://github.com/cs3org/reva/pull/4507, the OPTIONS call checks authentication. That means the tests needs to initalize a upload first. I don't know how it's handled after the changes in https://github.com/cs3org/reva/pull/4527.

But generally I'd really love to have tests for it (if there are none yet) :hugs:

**Comment by saw-jan** [comment] 2024-03-14 07:00
>But generally I'd really love to have tests for it (if there are none yet) 🤗

Yeah, looks like there's no coverage for it. I will add to the suite :smiley: 

Also, I confirmed these results
>```feature
>| 2 |  /data | HEAD  | ✔️
>| 2 |  /data | PATCH | ❌
> Missing expected header 'Access-Control-Allow-Headers'
>```

**Comment by wkloucek** [comment] 2024-03-14 07:18
Probably there are more methods allowed on the /data endpoint. At least POST comes to my mind. But that should be checked with somebody into TUS / the data gateway / provider

**Comment by saw-jan** [comment] 2024-03-14 10:12
@wkloucek Could you check if this scenario helps?
https://github.com/owncloud/ocis/blob/b7b5d45b66767d6842ebc19a3ef88cdbc2388453/tests/acceptance/features/apiCors/cors.feature#L138-L160

**Comment by wkloucek** [comment] 2024-03-14 10:14
@butonic will take over from here

**Comment by micbar** [comment] 2024-03-14 16:06
@wkloucek can we set the patch method for the frontend service as a workaround?

**Comment by wkloucek** [comment] 2024-03-15 06:02
@micbar @butonic please give https://github.com/owncloud/ocis-charts/pull/504 a review

**Closed** 2024-03-18 11:33 UTC
Labels: Type:Bug, Priority:p2-high
