### ISSUE TITLE
Certain filenames get blacklisted

### ISSUE THREAD

**Issue by ThePatrickHe** [owncloud/ocis#6686] opened 2023-07-01 04:23 UTC
Fedora 38 Client, Fedora 37 Server, server is running ocis docker.
Both client and server are the latest.

*edited

The bug:
Certain files will not sync with server when placed into client folder. The ownCloud client simply states "error" for the selected files and after retrying a few times, blacklists them.

1. Drag files into ownCloud folder on client
2. Attempt to sync

Here is a screenshot of my ownCloud client
![image](https://github.com/owncloud/ocis/assets/61365551/29b5a13a-cc0a-48d2-957e-132e3b6ebb90)

Occasionally, I also get `Server replied "412 Precondition failed" to "POST https://........."`:
![image](https://github.com/owncloud/ocis/assets/61365551/bd3f4c11-040e-4f93-8d6b-2fc093b7ea80)
(I blacked out the letters in the full addresses because I don't know if that's sensitive information)

I start the ownCloud server with:
```bash
docker run \
    --name ocis_runtime \
	--detach \
    --restart=always \
    -it \
    -p 9200:9200 \
    --mount type=bind,source=/mnt/expansion/ocis/ocis-config,target=/etc/ocis \
    --mount type=bind,source=/mnt/expansion/ocis/ocis-data,target=/var/lib/ocis \
    -e OCIS_INSECURE=true \
    -e PROXY_HTTP_ADDR=0.0.0.0:9200 \
    -e OCIS_URL=https://192.168.1.24:9200 \
    owncloud/ocis
```

*edit
After playing around with the filenames it seems that there is no particular filename pattern that gets blacklisted or not. For instance, I had a folder where all 3 files were being blacklisted. The following files are the 3rd, 4th, and 5th files listed in my first screenshot above:
![image](https://github.com/owncloud/ocis/assets/61365551/07c4fbdf-2bc0-476f-aa42-a67603729853)
When I changed their names to "test1" all three would upload. However, what is really interesting is that after reverting the names back to the originals, they stayed synced and did not fail.
Additionally, if I upload those specific files directly into the folder using the web viewer, they upload with no issues.
However, using the web viewer to upload my files is not really a workaround because when I attempt to upload the entire folder, it also fails.

**Comment by rootyElf** [comment] 2023-07-03 07:20
Same issue here, also with the docker image and Linux client. It seems to happen if the file path is over a certain length. I can reproduce it by creating a folder with a 128 character file name and putting a file inside which also has a 128 character long file name. It works when I upload it with a shorter file name and rename it to the long one afterwards.

**Comment by micbar** [comment] 2023-07-03 08:24
NOTE: most linux filesystems have a 255 Charakter limit on filenames.

**Comment by ThePatrickHe** [comment] 2023-07-03 16:54
> NOTE: most linux filesystems have a 255 Charakter limit on filenames.

I took a look and the files are not in violation. The longest filepath has only 197 characters and the filenames that are getting blacklisted are 100 to 200 characters long.

**Comment by ThePatrickHe** [comment] 2023-07-03 16:57
> Same issue here, also with the docker image and Linux client. It seems to happen if the file path is over a certain length. I can reproduce it by creating a folder with a 128 character file name and putting a file inside which also has a 128 character long file name. It works when I upload it with a shorter file name and rename it to the long one afterwards.

I tried to replicate this and I did not get the same error. I created a folder in /home/patrick/ownCloud/Personal called `test128filename_________________________________________________________________________________________________________________` and created a text file inside called `test128filename_________________________________________________________________________________________________________________.txt` and this synced just fine.

**Comment by rootyElf** [comment] 2023-07-11 15:10
> NOTE: most linux filesystems have a 255 Charakter limit on filenames.

In my case I would not be able to create the files in the first place, if this limit applied. I'm using f2fs locally.



> > Same issue here, also with the docker image and Linux client. It seems to happen if the file path is over a certain length. I can reproduce it by creating a folder with a 128 character file name and putting a file inside which also has a 128 character long file name. It works when I upload it with a shorter file name and rename it to the long one afterwards.
> 
> I tried to replicate this and I did not get the same error. I created a folder in /home/patrick/ownCloud/Personal called `test128filename_________________________________________________________________________________________________________________` and created a text file inside called `test128filename_________________________________________________________________________________________________________________.txt` and this synced just fine.

Strange, for me this does not work. I created a file like this:
`cd ~/'ownCloud - Admin@localhost/Persönlich'`
`mkdir test128filename_________________________________________________________________________________________________________________`
`touch test128filename_________________________________________________________________________________________________________________/test128filename_________________________________________________________________________________________________________________.txt`

> Issues         ,File                                                            ,Folder                        ,Size  ,Account             ,Time                ,Status              ,
Server replied "412 Precondition Failed" to "POST https://localhost:9200/dav/spaces/ef016ebd-fd47-47c7-a975-310ab4598531$dd81ce8f-9c85-426f-838c-2f1140aeb09f",test128filename_________________________________________________________________________________________________________________/test128filename_________________________________________________________________________________________________________________.txt,ownCloud - Admin@localhost/Persönlich,0 B   ,Admin@localhost:9200,2023-07-11T17:09:13.000,Info                ,

**Comment by fpauser** [comment] 2023-09-01 06:36
Could it be the `$` sign in the filenames?

**Comment by EduardRe** [comment] 2024-03-13 15:11
Hello, I also have a problem - some files are not synchronized - error 412 Precondition Failed, Blacklisted.
![image](https://github.com/owncloud/ocis/assets/65927124/d9b27182-f45f-4c1f-b4d8-cfb1e0e353b6)

The latest version of OCIS is installed (currently) 4.0.6

It was found out experimentally that this is some kind of OCIS (not file system) limitation here are examples of file paths on my PC:

D:\ownCloud\Личный\Trionix работа\Работа\Бизнес-процессы\Брайт Парк\Формирование docx файлов по шаблону\ГОТОВЫЕ ШАБЛОНЫ\Новая версия шаблонов (от 20.04.2022)\template_answers\ответ_отказ_в_предоствлении_документов_PREPARE.docx

D:\ownCloud\Личный\Trionix работа\Работа\Бизнес-процессы\Брайт Парк\Формирование docx файлов по шаблону\ГОТОВЫЕ ШАБЛОНЫ\Новая версия шаблонов (от 20.04.2022)\template_answers\ответ_без_рассмотрения_PREPARE.docx

D:\ownCloud\Личный\Trionix работа\Работа\Бизнес-процессы\Брайт Парк\Формирование docx файлов по шаблону\ГОТОВЫЕ ШАБЛОНЫ\Новая версия шаблонов (от 20.04.2022)\template_answers\ответ_новые_отказ_налог_PREPARE.docx

D:\ownCloud\Личный\Trionix работа\Работа\Бизнес-процессы\Брайт Парк\Формирование docx файлов по шаблону\ГОТОВЫЕ ШАБЛОНЫ\Новая версия шаблонов (от 20.04.2022)\template_answers\ответ_отказ_без_конкретики_PREPARE.docx

OCIS is installed on Debian 12, the BTRFS file system.

For the test (just in case), I created a very long path in the root of this server and uploaded an SFTP file with a very long name there - and there were no problems - the file opens correctly
Here is the full path along with the file:

/test_long_path/test_very_long_path_______________________________________________________________/Trionix работа/Работа/Бизнес-процессы/Брайт Парк/Формирование docx файлов по шаблону/ГОТОВЫЕ ШАБЛОНЫ/Новая версия шаблонов (от 20.04.2022)/template_answers/телеграмма_экспертиза_PREPARE.docx________________________________________________________________________________________________________________

Please tell me how this can be fixed? Thank you in advance.

**Comment by micbar** [comment] 2024-04-05 18:18
@butonic @aduffeck any hints?

**Comment by EduardRe** [comment] 2024-04-06 06:16
Hello! I shortened the path as much as I could, some files were synchronized, but there are some files that do not want to synchronize in any way.
![image](https://github.com/owncloud/ocis/assets/65927124/f3f2f16b-a998-453c-85ba-3f7a68d62e43)

Since I am a developer (PHP Full stack) I wanted to contribute to OCIS - fix this bug (or at least try to do it) and make a Pool request, but I had problems deploying in docker, or rather the problem arose with creating a build. I've given up on this idea for now, as there's a lot of work to do. For me, this problem is very critical and I really want to overcome it.

**Comment by micbar** [comment] 2024-04-06 15:50
Please check out owncloud.dev 

It should be straight forward to get started.  You can also chat with the devs on matrix (link in the readme.md)

**Comment by micbar** [comment] 2024-04-06 15:51
@butonic @aduffeck @2403905 we should take a look at this ticket on Monday.

**Comment by butonic** [comment] 2024-04-24 09:33
> NOTE: most linux filesystems have a 255 Charakter limit on filenames.

Some nitpicking: The 255 bytes limit per path segment. A lot of linux software expects a PATH_MAX = 4096 (bytes that is). Keeping paths shorter than that is a recommendation.

oCIS itself and the current underlying decomposedfs implementation can actually handle longer paths because it is id based internally. We never exceed PATH_MAX on disk.

That you can rename the files after they are uploaded also shows that filename characters, encoding or length are not the problem. Some length perspective:

`/test_long_path/test_very_long_path_______________________________________________________________/Trionix работа/Работа/Бизнес-процессы/Брайт Парк/Формирование docx файлов по шаблону/ГОТОВЫЕ ШАБЛОНЫ/Новая версия шаблонов (от 20.04.2022)/template_answers/телеграмма_экспертиза_PREPARE.docx________________________________________________________________________________________________________________`

This path has 401 Characters, using 518 bytes. 1/8thk of the 4k MAX_PATH length.

@fpauser `$` is not a problem. You can even use `😍` as your filename if you want to. ;-)

@ThePatrickHe @EduardRe @rootyElf @fpauser I'm more interested in the `412 Precondition failed` status. Are you all getting this? And what version of oCIS are you on. Please report your findings with the latest stable release, currently [5.0.2](https://github.com/owncloud/ocis/releases/tag/v5.0.2)

Can you try running ocis with log level debug:
```console
docker run \
    --name ocis_runtime \
	--detach \
    --restart=always \
    -it \
    -p 9200:9200 \
    --mount type=bind,source=/mnt/expansion/ocis/ocis-config,target=/etc/ocis \
    --mount type=bind,source=/mnt/expansion/ocis/ocis-data,target=/var/lib/ocis \
    -e OCIS_INSECURE=true \
    -e PROXY_HTTP_ADDR=0.0.0.0:9200 \
    -e OCIS_URL=https://192.168.1.24:9200 \
    -e OCIS_LOG_LEVEL=debug
    owncloud/ocis
```
be sure to update your options accordingly. when wathing the logs try to upload a single file. If that fails check the log and post what happened on the server side.

Also, hit F12 on the desktop client to write logs. They might also explain why the desktop client thinks it has to blacklist the files.

**Comment by butonic** [comment] 2024-04-24 09:44
@ThePatrickHe how many files are you dragging into the client folder? It looks like a large tree. In terms of quantity of files and folders, not bytes written.

**Comment by EduardRe** [comment] 2024-04-24 10:42
Hello, OCIS is installed on Debian 12, the BTRFS file system (the installation was not in docker, but a binary file according to this instruction https://doc.owncloud.com/ocis/4.0/depl-examples/bare-metal.html , the version was the most recent at that time - 4.0.6).
Just yesterday I upgraded to version 5.0.2 (thanks for the help in the chat https://app.element.io/#/room/#ocis:matrix.org /$Rugx85BAcVa9Ky2QxI_KBCw-zRUpDcLFIjcO4CDI0S0) and after updating manually, I was able to restart the synchronization and the files were synchronized (in version 4.0.6 it did not work in any way). Now in version 5.0.2 I have created a very long directory and uploaded a file with a very long name there

D:\ownCloud\Личный\Trionix работа\Работа\Бизнес-процессы\Брайт Парк\Создание docx\Шаблоны\Новые (от 20.04.2022)\template_answers\добавим еще одну директорию с ну очень длинным названием\еще чуть длинее название\директория_\для тестирования синхронизации очень длинный путь к файлу вот вопрос улетит или нет сейча.txt

and this file was successfully synchronized and did not give any errors, I also opened it and changed the text in it and it also synchronized successfully - the new text appeared - checked in the browser. It turns out that the problem has already been solved.

**Closed** 2024-04-25 07:44 UTC
Labels: Type:Bug

**Comment by divinitas-art** [comment] 2025-08-24 17:55
I am getting the blacklisted error with simple keepass.kdbx filename... so I tried to rename it and it didnt help at all... Then i found out that its onyl this one file, not the name... the file has encrypted keepass database in it... nothing else... What? why? what can i do to help yo fix it, since its... big problem for me...

it looks like that i cant upload the file only from macos (nor web interface nor syncing app) when i upload it from andorid it works fine

**Comment by 2403905** [comment] 2025-08-25 07:27
@divinitas-art Thank you for your report. It will be helpful if you add some installation context:
* oCIS version
* Is a server running as docker / docker compose (the deployment example or custom) / binary?

**Comment by divinitas-art** [comment] 2025-08-25 07:33
> [@divinitas-art](https://github.com/divinitas-art) Thank you for your report. It will be helpful if you add some installation context:
> 
> * oCIS version
> * Is a server running as docker / docker compose (the deployment example or custom) / binary?

https://github.com/owncloud/ocis/issues/11616 I created its own issue, because its kinda bigger than i thought
