### ISSUE TITLE
Browser cookies spoil fresh login

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#258] opened 2020-05-07 11:19 UTC
Run EOS according to https://github.com/owncloud/ocis/blob/master/docs/eos.md#run-it

Connect with Firefox, login user marie.
`make eos-stop`
`make eos-start`
Re-connect with Firefox, try login user marie again.

It fails:
![image](https://user-images.githubusercontent.com/1108546/81288632-4b70c600-9065-11ea-9e65-97a646f63a82.png)

After removing cookies from the browser, marie can log in again:
![image](https://user-images.githubusercontent.com/1108546/81288388-d7ceb900-9064-11ea-9cd7-d32a7e6ad1bc.png)

**Comment by jnweiger** [comment] 2020-09-08 16:14
Workaround to unblock testing: always use firefox Multi-Account Containers plugin.

**Comment by wkloucek** [comment] 2022-02-04 10:46
I'm closing this since it's a oC Web topic and I can no longer reproduce it because we currently have no EOS setup

**Closed by wkloucek** 2022-02-04 10:46 UTC
Labels: Type:Bug, Category:Defect, Storage:EOS
