### ISSUE TITLE
Allow to assign group membership from oidc claim

### ISSUE THREAD

**Issue by dorianim** [owncloud/ocis#7341] opened 2023-09-23 17:08 UTC
## Is your feature request related to a problem? Please describe.
Currently, it is possible, to assign the user role using an OIDC claim. But for groups, that does not seem to be possible. However, I'd like to automatically add users to a group when they log in, so they can access corresponding spaces.

## Describe the solution you'd like
It would be nice if it was possible to define an oidc claim which contains a list of group names a user should be added to.

## Describe alternatives you've considered
Add all users to their groups manually.

## Additional context
Currently, this is only supported for LDAP and owncloudsql:
https://doc.owncloud.com/ocis/next/deployment/services/s-list/groups.html

**Comment by rhafer** [comment] 2023-09-25 08:32
This is a duplicate of: https://github.com/owncloud/ocis/issues/5538

**Closed by rhafer** 2023-09-25 08:32 UTC
