### ISSUE TITLE
New permission SpaceManagement

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocis#4877] opened 2022-10-21 13:35 UTC
References the [roles and permissions]( https://github.com/owncloud/ocis/blob/master/services/settings/pkg/store/defaults/defaults.go) code

For completeness, we imho need a new permission like `SpaceManagement` that defines the ability to manage a space.

Example: a space admin creates a space (allowed) and then transfers the right to manage the space to a user (undefined).

@micbar @kulmann fyi

**Comment by kulmann** [comment] 2022-10-21 13:39
Your example is actually covered by the `Manager` space member role. As the space admin created the space, they automatically receive the `Manager` space member role. That role can be transferred to another user then.

What's not covered (at least to my knowledge) is, that a space admin adds a new `manager` member to a space where the space admin is not a `manager` member themselves.

Looking at the code now, we probably want more fine grained permissions than a generic `SpaceManagement`.

Apart from all of that, the web ui currently doesn't allow to view spaces which the logged in user is not a member of.

**Comment by mmattel** [comment] 2022-10-21 14:22
First of all, I wanted to initiate a discussion about this to have properly fix in the future.

Then, when reading the text, I see that there is an implicit permission type named "Manager", as part of the space - which you cant see, but is present. If we would turn that implicit permission type to an explicit one, we could then grant permissions (PermissionValue) which would immediately make this transparent and available to roles.

**Comment by micbar** [comment] 2022-10-21 20:24
> From my understanding, we have to differenciate between being automatically a member of a space when created and a role to manage the space. Managing a space not necessarily means being able to read content but always be able to manage members.

Space Member == Access to space content

You can only become a space member through access roles (!!! These are not User Roles !!!). Currently we only have 3 access Roles: Manager, Editor, Viewer


> Imho we need a SpaceManagement permission type we could then grant permissions (PermissionValue) which would immediately make this transparent and available to roles without being able to access content of spaces.

Maybe I don't get your point, but that is exactly what we have. We have Global User Roles where we grant permissions to the handling and Lifecycle of a space (Create, Delete, Disable, Restore, Change Quota) These global permissions are not connected to the access to space content, which is managed inside the space. That separation is a strength of the spaces concept because we can separate concerns between Sysadmin and Space Manager Persona.

**Comment by kulmann** [comment] 2022-10-21 22:51
To be clear, the web ui is very far away from offering space management functionality **without** content access. Never heard of that requirement before (if I have space management privileges and can add myself to a space as a member, it doesn't make sense to try to hide the content of the space in the first place). Managing space access is fundamental part of the content-view of a space. Not giving access to content would cripple the current UX concept. And we won't invest in a separate "space management without content access" application in web in the near future. CLI might make more sense here.

Looking at existing backend side permissions regarding space in the code:
https://github.com/owncloud/ocis/blob/master/services/settings/pkg/service/v0/settings.go#L32 and following lines
-> we are already more fine grained than your proposed, very generic `SpaceManagement` permission. It makes sense to stay on the same granularity that we already follow, or change it entirely.

@mmattel @micbar please let's not refer to the single word term `role` anymore. Something like `system role` for the permission bundles that the settings service provides, or `access roles` for sharing context like @micbar proposed. Otherwise this gets confusing for everyone.

And I want to underline again, like @micbar did as well: `Manager` (access role) grants control within a space. `Space Manager` or `Admin` (system roles) have permissions across spaces. And again, the web ui doesn't list any spaces where the logged in user is not a member / doesn't have an access role. That will need more changes in web (which are already planned for after oCIS GA of course).

**Comment by micbar** [comment] 2022-10-23 10:02
Closing as the product is working as designed.

**Closed by micbar** 2022-10-23 10:02 UTC
Labels: Category:Enhancement
