### ISSUE TITLE
"Create and copy public link to clipboard" generates an invalid link

### ISSUE THREAD

**Issue by algihu** [owncloud/ocis#4380] opened 2022-08-10 19:05 UTC
"Create and copy public link to clipboard" generates an invalid link

## Describe the bug

Using the Windows desktop app pointed to an OCIS instance, when I right-click on a synced file in Windows and select "Create and copy public link to clipboard" a link is generated and copied to the clipboard but when browsing to that link an "Unknown error" is returned.

## Steps to reproduce

1. Set up ownCloud Desktop App (Windows) pointed to an OCIS server
2. In Windows Explorer navigate to any file in ownCloud and right-click on it
3. In the context menu, select ownCloud-->Create and copy public link to clipboard
4. Open a web browser (I used Chrome) and paste/navigate to the URL that was copied to your clipboard.

## Expected behavior
The browser should load a page where you can view/download the file

## Actual behavior
Although a link gets generated and copied to the clipboard, when I view the file's properties I can see that no link was actually associated with this file and when I try to navigate to the URL a page is show that says "Unknown error"
![image](https://user-images.githubusercontent.com/111002145/183973356-6cde0995-dcf9-4d0f-b722-907246ff7d9a.png)

Here is a video showing this behavior:
![Sharing Not Working](https://user-images.githubusercontent.com/111002145/183996410-1258c278-4431-44e8-9e29-e83e26852226.gif)

## Setup

Installed/Started OCIS 2.0.0-beta.5 using the quick start guide here: https://doc.owncloud.com/ocis/next/quickguide/quickguide.html

Installed ownCloud Desktop App 2.10.1 (build 7187) and configured it to sync as virtual files to my OCIS instance.

Created a folder with some pictures in it.

## Additional context
I _can_ generate a valid link using the dialog that opens when I select ownCloud-->Share. After clicking that option I select the "Public Links" tab, click on the "_Create new..._" option and then click the "Create" button. I then click the "..." next to the newly created Public Link and select "Copy Link to Clipboard" and then paste/navigate to that link in a browser, This successfully allows me to access the file.

Here is a video showing this working successfully.
![Sharing Working](https://user-images.githubusercontent.com/111002145/183996372-b0df9a9b-04ba-42db-8f7c-aa5e026ff02e.gif)

**Comment by michl19** [comment] 2022-08-22 12:42
@michaelstingl can you have a look into this as well. We're unsure if it's desktop or backend.

**Comment by michaelstingl** [comment] 2022-08-22 15:49
> We're unsure if it's desktop or backend.

Maybe desktop. Something's 🐟 -y. I'll have a look tomorrow…

**Comment by kulmann** [comment] 2022-08-23 13:20
What kind of permissions does the public link have? We've introduced so called `Internal links`, which have a permission bitmask of `0`. Those are supposed to resolve into the correct shared location in the authenticated context of the user. 

If the created link has permissions `0` then I'd have an explanation for the issue described above: Resolving internal links is not yet supported in ownCloud Web - support is coming with https://github.com/owncloud/web/pull/7405 which is close to being merged.

If it's a link with permissions > 0 then I have no idea, yet.

**Comment by michaelstingl** [comment] 2022-08-23 15:45
Because of https://github.com/owncloud/ocis/issues/4445 , Desktop sync client 2.11 tries to create a link with todays expiration date, and because https://github.com/owncloud/ocis/issues/4446 , the link creation fails silently.

**Comment by michaelstingl** [comment] 2022-08-23 16:03
No idea why both ways behave different in the desktop sync client. I opened an issue for further investigation: https://github.com/owncloud/client/issues/10057

**Comment by C0rby** [comment] 2022-09-14 10:08
@michaelstingl, can you still reproduce this? I can't but I'm testing it on Linux since I don't have Windows.

**Comment by kulmann** [comment] 2022-09-14 10:10
Should have been fixed with https://github.com/owncloud/ocis/pull/4475

**Comment by C0rby** [comment] 2022-09-14 10:11
Cool so I can close this issue?

**Comment by kulmann** [comment] 2022-09-14 10:13
yes 😁 @algihu please re-open if the issue is not fixed for you with ocis v2.0.0-beta.8

**Closed** 2022-09-14 10:17 UTC
Labels: Platform:Desktop, Type:Bug

**Comment by algihu** [comment] 2022-09-15 20:34
I just tested it again with v2.0.0-beta.8 and this feature now works correctly.

**Comment by kulmann** [comment] 2022-09-16 07:05
> I just tested it again with v2.0.0-beta.8 and this feature now works correctly.

Thanks for investing the time :heart: Glad to hear that it's fixed 👍
