### ISSUE TITLE
Prevent recursive copy/move of the same resources

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/ocis#3992] opened 2022-06-20 12:59 UTC
## Describe the bug

I've just managed to create a bit of an absurd situation by copy-pasting a folder into itself (https://github.com/owncloud/web/issues/7148). On the frontend side, it will be prevented via https://github.com/owncloud/web/pull/7151, but I suppose we should also add some backend logic too since it sends oCIS into hyperdrive (and potentially crashes it/leads an exceeded quota) 💩

**Comment by butonic** [comment] 2022-06-30 11:29
duplicate of https://github.com/owncloud/ocis/issues/3023 ?

**Comment by aduffeck** [comment] 2022-07-06 06:42
This has been fixed in master with the merge of https://github.com/owncloud/ocis/pull/4076

**Closed by aduffeck** 2022-07-06 06:42 UTC
Labels: Type:Bug
