### ISSUE TITLE
User in multiple groups only sees shares of one of the groups

### ISSUE THREAD

**Issue by willmackay** [owncloud/ocis#4671] opened 2022-09-26 21:56 UTC
## Describe the bug

A user who belongs to multiple groups only has the permissions of a single one of these groups.

## Steps to reproduce

1. I created two groups (KFQwWJSl and xZjCGDhi).

2. As the admin user, I created a new folder (AmUZWyXITXUqwBzQ) and shared it with the first group (KFQwWJSl ).

3. I created a new user (ePxUovIhybXazegI) and added them to both groups.

4. I logged out and logged back in, and the new user (ePxUovIhybXazegI) does not see the folder (AmUZWyXITXUqwBzQ).

5. I logged back in as admin and removed the user from the second group (xZjCGDhi).

6. I logged back in as the new user and now I can see the share.

## Expected behavior
The user should have seen the shared folder while in both groups.

## Actual behavior
No share was visible.

## Setup

I'm running ocis 2.0.0-beta8 on Debian 11, no containers.

```
PROXY_HTTP_ADDR=127.0.0.1:9200
OCIS_URL=https://ocis.alyrica.net
OCIS_BASE_DATA_PATH=/var/lib/ocis
OCIS_LOG_PRETTY=true
```

**Comment by willmackay** [comment] 2022-09-26 21:56
Here's some screenshots of the bug
![1 - groups](https://user-images.githubusercontent.com/24301649/192387928-a4bdbd86-c228-452f-a3e5-075877f94a71.png)
![2 - share](https://user-images.githubusercontent.com/24301649/192387932-31220408-9008-4221-bcba-5dea79ff70b2.png)
![3 - user](https://user-images.githubusercontent.com/24301649/192387934-b61e5e2e-41b7-4e00-9745-fa87d7de4b7d.png)
![4 - no shares](https://user-images.githubusercontent.com/24301649/192387937-c37b4a8b-289c-44b9-8332-e38075ab70c7.png)
![5 - removed](https://user-images.githubusercontent.com/24301649/192387938-fff4c213-403c-42ba-8ddb-039ddc164e86.png)
![6 - visible](https://user-images.githubusercontent.com/24301649/192387939-eea0e993-b86c-4fcf-9bda-eac48cbe2725.png)

**Comment by phil-davis** [comment] 2022-09-27 03:20
@saw-jan @amrita-shrestha please get someone to try and find a test scenario that checks access to shares for a user who is a member of multiple groups. If there is no automated test scenario, then create one - it should go in the core test suites, because we want to also verify that this works properly in oC10 core.

And then report if this is a problem with the oCIS back-end or with web.

**Comment by SagarGi** [comment] 2022-09-27 09:53
@phil-davis  i treid the above mentioned issue in latest docker image, building locally latest master `ocis`, and also tried checking out to `ocis 2.0.0-beta8`.

Latest Docker : Could not reproduce (may be fixed)
Latest master ocis : Could not reproduce (may be fixed)
ocis 2.0.0-beta8: Yes reproducable.

I will be adding up acceptance tests for this on core.

**Comment by SagarGi** [comment] 2022-09-30 08:44
The above following acceptance has been added so moving this to Done.

**Comment by butonic** [comment] 2023-03-21 15:49
@SagarGi hm I can reproduce this with ocis master and the demo accounts. create two folders with admin, share one with polonium-lovers, the other with physics-lovers. than marie will only see one share in the list of available shares.

**Comment by butonic** [comment] 2023-03-21 16:26
found the bug. in https://github.com/cs3org/reva/blob/edge/pkg/share/manager/jsoncs3/jsoncs3.go#L719-L729 we are overwriting the previous result.

fix incoming

**Comment by micbar** [comment] 2023-03-21 19:03
@willmackay  the fix will be in ocis master after the next reva update.

**Comment by rhafer** [comment] 2023-04-05 10:04
Fixed

**Closed by rhafer** 2023-04-05 10:04 UTC
Labels: Type:Bug
