### ISSUE TITLE
[enhancement] appearance: ability to upload login page background image

### ISSUE THREAD

**Issue by brandon1024** [owncloud/ocis#7674] opened 2023-09-29 13:24 UTC
### Description

Changing the login page background image isn't straightforward. To do this, we need to update the theme config to provide a path to the image.

It would be great if we could upload an image directly in the admin pages. It's possible to update the logo this way, but not the login page background.

Alternatively, configuring this through an environment variable would be nice too!

### Steps to reproduce
1. Log in as the admin user.
2. Navigate to the Admin Settings, under General.

### Expected behaviour

Ability to upload a background image for the login page, similar to how we can upload a logo currently.

### Actual behaviour

Currently cannot upload a background image. To do this, we need to update the theme config which is tricky to do.

### Environment general

```
ownCloud Infinite Scale Community
4.0.0+1fe1805ce
8.0.0-alpha.2
```

- **Operating system**: Docker
- **Backend (ownCloud Core or Infinite Scale)**: oCIS
- **Are you using an external user-backend, if yes which one:** No.

**Comment by kulmann** [comment] 2023-11-07 14:20
Hey @brandon1024 thanks for reaching out! Unfortunately, the theme config is super misleading in this case. The Web UI uses the background image you saw in the theme config on a `Loading` indicator page only. That was different a few months (years?) ago... please understand that theming the login page that is built into oCIS is only possible via code. It's all hardcoded in the `idp` service in the oCIS repo, see https://github.com/owncloud/ocis/tree/master/services/idp

There are even plans to switch over to Authelia as bundled IdP, so I fear it's not even worth to try and make it configurable in kopano konnect (the IdP that's currently bundled in oCIS). Discussion around that is here: https://central.owncloud.org/t/try-to-ship-authelia-as-the-default-idp-in-the-ocis-binary/45662

I moved your issue to the oCIS repo because that's something we can't solve in the web ui code base. The web ui just uses oidc and whatever IdP you've configured.

**Comment by brandon1024** [comment] 2023-11-07 15:20
Thanks a bunch for this info @kulmann! This makes a lot of sense--I should have guessed that the login page was bundled in the IDP project, not in the web project.

I'm good with that, and I'm happy to close this issue and wait for the switch to Authelia (or we can leave open, whatever you prefer) :slightly_smiling_face: 

Cheers!

**Comment by kulmann** [comment] 2023-11-07 15:37
Thank you. 😇  Personally I'm fine to keep this open as a reminder for possible theming options with Authelia.

CC'ing both @micbar (product owner for oCIS) and @pascalwengerter (who's already put a lot of brain capacity into proper theming here at ownCloud)

**Comment by micbar** [comment] 2023-11-07 15:39
duplicate of https://github.com/owncloud/ocis/issues/7468

The original ticket was closed because not planned.

**Comment by micbar** [comment] 2023-11-07 16:04
There is a guide how to theme the kopano IdP https://central.owncloud.org/t/theming-settings-in-ocis-yaml/45276/14

**Closed** 2024-01-31 14:02 UTC
Labels: Category:Enhancement
