### ISSUE TITLE
different output preview dimension from oc10 backend

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/ocis#2069] opened 2021-05-25 04:21 UTC
## Describe the bug
When a request for a thumbnail is made with the dimensions `x=1,y=32` then
- In `oC10`  server responds with an image `1px` wide and `32px` high
- In `ocis`, the larger value from the two dimensions is taken to recalculate the smaller dimension to match the original aspect ratio.

## Setup

export ACCOUNTS_HASH_DIFFICULTY=4 \
export OCIS_URL='https://localhost:9200' \
export STORAGE_HOME_DRIVER='owncloud' \
export STORAGE_USERS_DRIVER='owncloud' \
export STORAGE_DRIVER_OCIS_ROOT='/tmp/ocis/storage/users' \
export STORAGE_DRIVER_LOCAL_ROOT='/tmp/ocis/local/root' \
export STORAGE_DRIVER_OWNCLOUD_DATADIR='/tmp/ocis/owncloud/data' \
export STORAGE_METADATA_ROOT='/tmp/ocis/metadata' \
export STORAGE_HOME_DATA_SERVER_URL='http://localhost:9155/data' \
export STORAGE_USERS_DATA_SERVER_URL='http://localhost:9158/data' \
export WEB_UI_CONFIG=$HOME/www/ocConfigs/ocis-config.json \
export WEB_ASSET_PATH=$HOME/www/web/dist \
export IDP_IDENTIFIER_REGISTRATION_CONF=$HOME/www/ocConfigs/idp.yml \
export PROXY_ENABLE_BASIC_AUTH=True \
export OCIS_LOG_LEVEL='warn' \
export ACCOUNTS_DATA_PATH="/tmp/ocis-accounts/" \
export SETTINGS_DATA_PATH="/tmp/ocis/settings" \
export STORAGE_SHARING_USER_JSON_FILE="/tmp/ocis/shares.json" \
export STORAGE_DRIVER_OWNCLOUD_REDIS_ADDR='localhost:6379'

<details>
<p>

```console
BRANCH=master
```

</p>
</details>

**Comment by individual-it** [comment] 2021-05-25 09:49
@refs please close this issue if the behaviour is correct is ocis

**Comment by individual-it** [comment] 2021-05-26 11:31
- [ ] ToDo QA:Team : if this turns out to be the correct behaviour the tests of https://github.com/owncloud/ocis/pull/2075 need to be moved out of the `bugdemonstration` folder

**Comment by refs** [comment] 2021-05-27 09:00
IIRC, @C0rby , this is the expected behavior in oCIS, right?

**Comment by micbar** [comment] 2024-06-04 18:53
The ocis thumbnailer has now more features. Closing here.

**Closed by micbar** 2024-06-04 18:53 UTC
Labels: Type:Bug
