### ISSUE TITLE
[QA] trashcan "Empty" fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#1078] opened 2020-12-12 01:06 UTC
Deployed ocis master 2020-12-11 13:30h via hetzner-deploy/make_ocis_test.sh -> ocis/deployments/examples/ocis_traefik/

* login as einstein
* upload a file
* delete the file
* visit trashcan
* click "Empty". An error occurs. BAD
![image](https://user-images.githubusercontent.com/1108546/101968240-64a2ac00-3c1e-11eb-85cb-6e11bb884b3e.png)
* select all files, click "Delete". OK

expected behaviour: "Empty" empties the trashcan the same way as deleting all would do.

**Comment by kulmann** [comment] 2020-12-12 06:53
<img width="509" alt="Screenshot 2020-12-12 at 07 46 56" src="https://user-images.githubusercontent.com/3532843/101977621-0c37d280-3c4f-11eb-8694-6ca3bb32c0cd.png">

The `DELETE` request with an empty path is not implemented in reva, so we land here: 
https://github.com/cs3org/reva/blob/e791b5599a89577db43da51b60c98592b4814ca1/internal/http/services/owncloud/ocdav/trashbin.go#L125

**Comment by individual-it** [comment] 2020-12-16 09:59
duplication of https://github.com/owncloud/product/issues/254

**Comment by refs** [comment] 2021-01-12 14:04
closing as duplicate of https://github.com/owncloud/product/issues/254

**Closed by refs** 2021-01-12 14:04 UTC
