### ISSUE TITLE
Advanced permissions role is not displayed in the shares shared with advanced permissions

### ISSUE THREAD

**Issue by jasson99** [owncloud/ocis#1922] opened 2021-04-15 12:09 UTC
## Describe the bug

`Advanced permissions` role is not displayed in the shares shared with `Advanced Permissions` set.

## Steps to reproduce

1. Create user `jasmine2`
2. As admin, create folder `New Folder`
3. Share `New Folder` with user `jasmine2` as `Advanced Permissions` with no extra permissions specified

## Expected behavior
The displayed role should be `Advanced Permissions`

## Actual behavior
The displayed role is `Viewer`
![Screenshot from 2021-04-15 17-48-15](https://user-images.githubusercontent.com/40829116/114866637-894ca180-9e13-11eb-877e-cda07a48f591.png)

**Comment by kiranparajuli589** [comment] 2021-07-06 09:22
update: advanced permission is only displayed if any of the extra permissions checkboxes is checked.

**Comment by ScharfViktor** [comment] 2021-09-08 09:23
re-tested: with local server oCIS version 1.11.0 and web 4.1.0
still relevant

**Comment by saw-jan** [comment] 2022-04-05 11:15
web now has `Custom permissions` instead of `Advance Permissions`.
![custom-permissions](https://user-images.githubusercontent.com/52366632/161741712-5a0d0282-e641-415b-b0d2-e5a4e3cccb2c.png)

And if the Custom permissions match to `Viewer` or `Editor` then it will display as one of them, not as `Custom permissions`

I think we can close this one

**Comment by kulmann** [comment] 2022-04-05 11:21
Yes, it's by design that we show the exact role that matches the selected custom permissions, if there is one. Thanks for re-checking. I'll close this ticket now.

**Closed by kulmann** 2022-04-05 11:21 UTC
Labels: Type:Bug, Priority:p3-medium
