### ISSUE TITLE
Enable OCS Provisioning API tests

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis#512] opened 2020-09-01 05:24 UTC
We already have tests for the OCS Provisioning API in the OC 10 test suite which we use to run the API tests in ocis. But those tests are skipped currently because we didn't use to have the OCS Provisioning API in ocis. But since we have the ocis Provisioning API available now we can enable those tests and fix them to run with ocis.

- [x] enable the provisioning API tests https://github.com/owncloud/core/pull/37866
- [x] adjust the tests in core so that they understand better what to do on OCIS

**Comment by phil-davis** [comment] 2020-09-01 05:30
Issue https://github.com/owncloud/ocis-reva/issues/415 is related.

@dpakach which core scenarios are you thinking of? We run quite a lot of core scenarios in OCIS already (and many are listed in expected-failures)

**Comment by dpakach** [comment] 2020-09-01 05:32
@phil-davis, The provisioning API tests are currently tagged with `@notToImplementOnOCIS`. But since we have provisioning API in OCIS, we can probably run some of them now.

**Comment by phil-davis** [comment] 2020-09-01 05:56
OK - that will be useful so that we will know if the OCIS provisioning API endpoints have regressions (even if the OCIS Provisioning API does not get expanded to cover everything)

**Comment by phil-davis** [comment] 2020-09-01 12:45
I adjusted the issue title to be clear that this is about OCS Provisioning API tests.
See PR https://github.com/owncloud/core/pull/37866

**Comment by phil-davis** [comment] 2020-09-02 16:00
PR https://github.com/owncloud/core/pull/37874 was merged. That gets ordinary provisioning API user creation test scenarios working. There are scenarios that fail due to unusual usernames, mixed-case usernames, etc. Those look mostly to be deficiencies in the OCIS Provisioning API implementation.

- look through the Provisioning API test failures and either
  - raise issues for the things that fail
  - enhance the core test code (if the problem is related to the test code)

**Comment by phil-davis** [comment] 2020-09-14 03:09
The failing tests are listed in expected failures now, so we can follow those up separately.

**Closed by phil-davis** 2020-09-14 03:09 UTC
Labels: qa-team
