### ISSUE TITLE
[QA] shared file is visible, but cannot be accessed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#582] opened 2020-09-15 21:55 UTC
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * firefox

<details>
<summary>Version details ocis-1.0.0-rc1</summary>

<pre>
OCIS_VERSION:         v1.0.0-rc1
ocis --version:       ocis version 199267c^M
git log:              commit 199267c13e916aa8de027a81dbf6733af820369f (HEAD, tag: refs/tags/v1.0.0-rc1)
eos --version:        EOS 4.6.5 (2019)^M
xrootd -v:            v4.11.0^M
bin/ocis contains:
        owncloud/ocis-accounts@v0.4.2-0.20200901074457-6a27781a2741
        owncloud/ocis-glauth@v0.5.1-0.20200731165959-1081de7c60f1
        owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
        owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
        owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
        owncloud/ocis-konnectd@v0.3.2
        owncloud/ocis-migration@v0.2.0
        owncloud/ocis-ocs@v0.3.1
        owncloud/ocis-phoenix@v0.13.0
        owncloud/ocis-pkg/v2@v2.4.1-0.20200828095914-d3b859484b2b
        owncloud/ocis-proxy@v0.7.1-0.20200904132806-fcceec602fcb
        owncloud/ocis-reva@v0.13.0
        owncloud/ocis-settings@v0.3.2-0.20200902094647-35dc3aeaba78
        owncloud/ocis-store@v0.1.1
        owncloud/ocis-thumbnails@v0.3.0
        owncloud/ocis-webdav@v0.1.1

</pre>
</details>

Reproducer

* use two differnet browser session. log in marie and einstein simultaneously.
* marie uploads a photo.
* marie shares the photo with einstein
* einstein visits 'shared with me' and accepts the photo
* einstein visits his "Shares" folder, and sees the photo.
* einstein attempts media viewer. it fails.
* einstein attempts download, nothing happens.
* einstein attempts to copy the photo elsewhere, an error appears.
![image](https://user-images.githubusercontent.com/1108546/93269241-e9606400-f7ae-11ea-9778-33f39a5ff5d8.png)

Expected behaviour: einsteins should have at least read access.

**Comment by jnweiger** [comment] 2020-09-15 22:27
## Retested with 

* ocis-master via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * firefox

<details>
<summary>Version details ocis-master</summary>

OCIS_VERSION:         master
ocis --version:       ocis version 3f8fb10
git log:              commit 3f8fb10990c37377a0e102492922ffd4807571d6 (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
eos --version:        EOS 4.6.5 (2019)
xrootd -v:            v4.11.0
bin/ocis contains:
	owncloud/ocis-accounts@v0.4.2-0.20200911161616-e55b8ae2f440
	owncloud/ocis-glauth@v0.5.1-0.20200909064150-0735ec933777
	owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
	owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
	owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
	owncloud/ocis-konnectd@v0.3.2
	owncloud/ocis-migration@v0.2.0
	owncloud/ocis-ocs@v0.3.1
	owncloud/ocis-phoenix@v0.13.1-0.20200910090722-8e3ed0e966a5
	owncloud/ocis-pkg/v2@v2.4.1-0.20200902134813-1e87c6173ada
	owncloud/ocis-proxy@v0.7.1-0.20200907105449-201b9a652685
	owncloud/ocis-reva@v0.14.0
	owncloud/ocis-settings@v0.3.2-0.20200903035407-ad5de8264f91
	owncloud/ocis-store@v0.1.1
	owncloud/ocis-thumbnails@v0.3.0
	owncloud/ocis-webdav@v0.1.1
</pre>
</details>

Unchanged. Receiver cannot view.

**Comment by jnweiger** [comment] 2020-09-15 23:03
Desktop client also fails to access the received files

![image](https://user-images.githubusercontent.com/1108546/93273544-5f1cfd80-f7b8-11ea-9924-b195b81f1dbc.png)

**Comment by phil-davis** [comment] 2020-09-16 02:52
These kind of things are all likely the same problem as issue https://github.com/owncloud/product/issues/208

The failing API test scenario does this sequence:
- Alice shares a file with Brian
- Brian accepts the share
- Brian tries to download the file

The download in that scenario gets a 404 and the body content is therefore empty.

Fixing that will likely fix a lot of sharing stuff. It is being worked on in https://github.com/cs3org/reva/pull/1170

**Comment by jnweiger** [comment] 2020-10-30 13:03
@butonic This was marked a release blocker in RC1, any updates here? Related to https://github.com/owncloud/product/issues/208 ?

**Comment by micbar** [comment] 2020-12-07 15:57
Duplicate of cs3org/reva#1170

**Comment by micbar** [comment] 2020-12-07 15:57
Known limitiation on EOS, other storage drivers work fine

**Closed by micbar** 2020-12-07 15:57 UTC
Labels: bug, p3-medium
