### ISSUE TITLE
Export and zip folder tree

### ISSUE THREAD

**Issue by Lord-Y** [owncloud/ocis#6051] opened 2023-04-13 15:59 UTC
## Is your feature request related to a problem? Please describe.

Hello Team, with `owncloud 10` I was able to go on my server and zip my `2015` directory easily for example.
```
/data/owncloud/xxxx/files/Photos/Pellicule/2015/IMG_20150424_135424.jpg
/data/owncloud/xxxx/files/Photos/Pellicule/2015/IMG_20150424_135621.jpg
/data/owncloud/xxxx/files/Photos/Pellicule/2015/IMG_20150425_162227.jpg
/data/owncloud/xxxx/files/Photos/Pellicule/2015/IMG_20150425_162236.jpg
```

With `oCIS`, things are differents as files are stored like this:
```
users/spaces/d8/c6c0b7-d1b7-4d5f-9549-8ff90debe9d8/nodes/d8/c6/c0/b7/-d1b7-4d5f-9549-8ff90debe9d8
users/spaces/d8/c6c0b7-d1b7-4d5f-9549-8ff90debe9d8/nodes/d8/c6/c0/b7/-d1b7-4d5f-9549-8ff90debe9d8/20220813_133212.jpg
users/spaces/d8/c6c0b7-d1b7-4d5f-9549-8ff90debe9d8/nodes/d8/c6/c0/b7/-d1b7-4d5f-9549-8ff90debe9d8/test
users/spaces/d8/c6c0b7-d1b7-4d5f-9549-8ff90debe9d8/nodes/d8/c6/c0/b7/-d1b7-4d5f-9549-8ff90debe9d8/20230325_162452.jpg
users/spaces/d8/c6c0b7-d1b7-4d5f-9549-8ff90debe9d8/nodes/d8/c6/c0/b7/-d1b7-4d5f-9549-8ff90debe9d8/plop.txt
```

## Describe the solution you'd like
Do we have a `cli` option that permit to copy files with the right folder tree into a mentionned folder so I can zip it after, or `oCIS` can directly zip it?
I insist about the right folder tree because from the `UI`, I have a test directory and a file in this directory but on the server I can find the file like this:
```
users/spaces/d8/c6c0b7-d1b7-4d5f-9549-8ff90debe9d8/nodes/8f/a0/5e/36/-5525-47e5-a3df-cc12765b46d2/20220828_112953.jpg
```

If no, I think this is a must have.
Personnaly I check but didn't found any options.

Thx

**Comment by micbar** [comment] 2023-04-13 18:15
@Lord-Y Please understand the following technical background.

What you see on the oCIS storage on the disk is the DecomposedFS (Decomposed Filesystem). This is the data layout on disk which is needed to get rid of the database. The `nodes` are not the real files, they only contain the metadata of the file. The file tree is created by symlinks. 

## Conclusion

The ocis DecomposedFS was never designed to be accessed direclty (bypassing the ocis clients). 

## Alternative

Download the archive for a folder via the WebUI. If you select one or multiple resources and choose the download action, You will get (depending on your os) a .zip or .tar archive.

**Comment by micbar** [comment] 2023-05-17 08:23
> Is there a way to automate the WebUI "select all folders -> download" process, through CLI or API commands? This would allow users to preserve the native file tree in our backups. The [HTTP API](https://owncloud.dev/libre-graph-api/) seems to only expose administration commands.

Like all versions of owncloud, ocis uses WebDAV for all file operations. I would suggest to use `rclone` with the OIDC agent to download large ocis trees.

> From the documentation, it looks like the [future CephFS storage driver](https://owncloud.dev/ocis/storage-backends/cephfs/#implemented-aspects) will behave like the OP and I would want - native file tree, with the metadata and sharing handled through symlink. However, that driver is still in development and won't be ready for a while. Is that correct?

Please distinguish between CephFS and native Ceph support.
The latter will probably have a normal file tree.

The filesystem which was the `mother` of ocis is EOS and has all the capabilities in the filesytem. You even have the same ACLs on EOS like in ocis. That means you can access EOS directly on the filesystem or via ocis and it is consistent.

**Comment by micbar** [comment] 2024-06-04 13:50
Duplicate of #7126

**Closed by micbar** 2024-06-04 13:50 UTC
Labels: Status:Proposal, Category:Enhancement
