### ISSUE TITLE
CORS issues when running web on different host

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis#5108] opened 2022-11-23 14:46 UTC
## Describe the bug

Serving the web assets from a different host / port than the backend causes CORS issues.
The first failing request after login is an `OPTIONS` request to `/ocs/v1.php/cloud/user`, there are probably more issues. 😉 
In the case of the mentioned `OPTIONS` request the backend requires authentication and returns a `401`, whereas `OPTIONS` requests should never require authentication.

## Steps to reproduce

1. checkout `web` master (after https://github.com/owncloud/web/pull/8016 is merged)
2. run `docker-compose up -d`
3. create a symlink to the dev setup config.json: `ln -s ../dev/docker/ocis.web.config.json config/config.json`
4. run `pnpm i && pnpm serve`
5. try to log in on `https://host.docker.internal:9100` (you might need to add `host.docker.internal` as localhost alias to your `/etc/hosts` file if not already present)

## Expected behavior
You should be able to login and see your personal space ;-)

## Actual behavior
CORS errors

## Setup

The dev setup from the `web` repo, see `steps to reproduce`, with an up to date ocis docker image.

**Comment by kulmann** [comment] 2022-11-23 14:46
cc @wkloucek this is what we saw today in our zoom call

**Comment by dschmidt** [comment] 2022-11-25 20:45
I found a (fairly reasonable) workaround that works in our new development setup, so there's no real urgency to get this fixed from our side.
(Still think this should be fixed rather sooner than later but it's not blocking us anymore :trollface: )

**Comment by dschmidt** [comment] 2023-06-15 00:14
Despite the recently closed tickets/PRs linking this issue, it's still not fixed in oCIS latest

**Comment by micbar** [comment] 2023-06-15 06:45
@dschmidt what config did you use and what is exactly the problem?

You need to set the `OCIS_CORS_*` variables. https://doc.owncloud.com/ocis/next/deployment/services/env-vars-special-scope.html

**Comment by dschmidt** [comment] 2023-06-15 09:21
Thanks a lot, @wkloucek - really good catch!

With just `OCIS_CORS_ALLOW_ORIGINS` set, I can make oC Web boot up and render a personal space listing. But other issues become apparent now:

> Access to XMLHttpRequest at 'https://host.docker.internal:9200/ocs/v1.php/cloud/user/signing-key' from origin 'https://host.docker.internal:9201' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> Access to XMLHttpRequest at 'https://host.docker.internal:9200/remote.php/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157%24some-admin-user-id-0000-000000000000/sadfasdf.txt' from origin 'https://host.docker.internal:9201' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by 2403905** [comment] 2023-07-20 09:15
@dschmidt Can not reproduce on my local. Please describe your environment.

**Comment by 2403905** [comment] 2023-07-20 14:18
Looks like some requests don't contain the `Origin` header.
![Screenshot 2023-07-20 at 16 02 29](https://github.com/owncloud/ocis/assets/11679989/d5ce7ea7-c907-4491-b780-9658a77079ee)
@JanAckermann Could you validate please if the request on the screenshot contains the `Origin` header?

Steps:
Latest https://github.com/owncloud/web
Cometed out the # traefik.http.routers.ocis.middlewares: cors in docker-compose.yml
Run backend`docker-compose up ocis -d`
Run frontend `pnpm vite`
Login as an admin
Got to the Spaces, create a New space, go inside a New space.

**Comment by JanAckermann** [comment] 2023-07-21 10:20
@2403905 if Access-Control-Expose-Headers (for example value: '*') is not set on the server side, frontend can't retrieve multiple headers, that we rely on.

**Comment by 2403905** [comment] 2023-07-21 10:55
@JanAckermann https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
When the client sends the preflight request it could contain the Origin header. The question is why some request doesn't contain the Origin?

**Comment by JanAckermann** [comment] 2023-07-21 10:57
CORS will be set by the server, this is nothing that the frontend is in control of, I think your question could be better answered by a server team member.

**Comment by 2403905** [comment] 2023-07-27 11:46
@JanAckermann Is the frontend managing the `access-control-request-headers` ?

**Comment by JanAckermann** [comment] 2023-07-27 11:48
@2403905 as I said before, cors is exclusive handled by server. Cors would be senseless if managed by Frontend

**Comment by 2403905** [comment] 2023-07-27 14:46
I found the cause but @JanAckermann we still need to work together to figure out the root cause of this issue. 
We have the OPTION requests that contain the not allowed value `cache-control` in the `Access-Control-Request-Headers` which leads to CORS error.
Workaround: Add the `cache-control` to the allowed headers
`OCIS_CORS_ALLOW_HEADERS: 'Origin,Accept,Content-Type,Depth,Authorization,Ocs-Apirequest,If-None-Match,If-Match,Destination,Overwrite,X-Request-Id,X-Requested-With,Tus-Resumable,Tus-Checksum-Algorithm,Upload-Concat,Upload-Length,Upload-Metadata,Upload-Defer-Length,Upload-Expires,Upload-Checksum,Upload-Offset,X-HTTP-Method-Override,cache-control'`

**Closed** 2023-07-28 10:53 UTC
Labels: Type:Bug, Priority:p2-high
