### ISSUE TITLE
Api-test. Clean up creating test users via ocs endpoint

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6998] opened 2023-08-09 09:59 UTC
for our apiTest we have 3 option to create user/group using:

- graph endpoint(`TEST_WITH_GRAPH=true`)
- ldap (need for reva "TEST_WITH_LDAP": "true")
- ocs endpoint - not possible now (https://github.com/owncloud/ocis/pull/3685)

ocis doesn't create users/groups using the `ocs` endpoint after we switch to graph. 
mobile client doesn't support admin options 
we don't have any tests for creating or deleting users in ocis using `ocs` except https://github.com/owncloud/ocis/tree/master/tests/acceptance/features/coreApiAuthOcs 

@SwikritiT and me suggest to: 
- [x] delete all `ocs` steps (CRUD users/group) from Provisioning.php https://github.com/owncloud/ocis/issues/6998#issuecomment-1707719703
      - we are deleting all the `ocs` steps (CRUD users/group) because CRUD operation related to users/group through `ocs` are not possible anymore. Please refer to following PR's/issues for further information : https://github.com/owncloud/ocis/pull/3820, https://github.com/owncloud/ocis/pull/3685, https://github.com/owncloud/ocis/issues/3167, https://github.com/owncloud/ocis/pull/3404
- [ ] delete env `TEST_WITH_GRAPH=true` and use graph api by default @amrita-shrestha

**Comment by individual-it** [comment] 2023-08-09 10:54
duplicate of https://github.com/owncloud/ocis/issues/6729 ?

**Comment by SwikritiT** [comment] 2023-08-09 11:41
In addition to what's written here, we have some open issues related to `ocs provisioning api`  like https://github.com/owncloud/ocis/issues/2729, which might no longer be relevant, we can go through the issue and close them as well.

**Comment by S-Panta** [comment] 2023-09-06 06:00
The test codes that involve user creation (singly or in groups) have been moved so that they now use graph API only and the PR is merged. https://github.com/owncloud/ocis/pull/7019. The following tasks left to clean are:
- [ ] Deleting the user 
- [ ] Adding a user to the group
- [ ] remove the user from the group
- [ ] creating the group
- [ ] deleting the group
- [ ] setting the user quota

**Comment by S-Panta** [comment] 2023-09-06 06:01
@saw-jan can you add more if there are any left to do regarding this refactoring task?

**Comment by pascuflow** [comment] 2023-10-26 23:05
Newbie here, moved from OCS to OCIS and trying to create a user via api, using Docker with ocis 4.0.0+f5f11e0bd and web client version 8.0.0-alpha.4. Used to do it with OCS like:

```
    let storageData = new FormData();
    storageData.append("userid", email);
    storageData.append("password", password);

    await axios.post(storageUrl + "/ocs/v1.php/cloud/users", storageData, {
      auth: {
        username: process.env.ADMIN_USERNAME,
        password: process.env.ADMIN_PASSWORD,
      },
      headers: storageData.getHeaders(),
    });
  ```
  Do I need to do any setup before running the docker ocis image?  What endpoint to call?
  
  Thanks

**Comment by saw-jan** [comment] 2023-10-27 03:34
oCIS 4.0.0 uses graph API for user/group provisioning. The request looks like this:
```bash
curl -XPOST "https://localhost:9200/graph/v1.0/users" \
-d'{"displayName":"Alice Hansen","mail":"alice@example.org","onPremisesSamAccountName":"alice","passwordProfile":{"password":"1234"}}' \
-u admin:admin
```

**Comment by pascuflow** [comment] 2023-10-27 11:52
Tried that on localhost and behind a proxy with valid cert, got 401 for both, do I need an access token and if so how do I obtain one?

```
curl -k -i -XPOST "https://localhost:9200/graph/v1.0/users" -d'{"displayName":"Alice Hansen","mail":"alice@example.org","onPremisesSamAccountName":"alice","passwordProfile":{"password":"1234"}}' -u admin:admin
```

```
HTTP/1.1 401 Unauthorized
Www-Authenticate: Bearer realm="localhost:9200", charset="UTF-8"
X-Request-Id: 1ab3afc5569f/4KU04OtP27-000292
Date: Fri, 27 Oct 2023 11:43:28 GMT
Content-Length: 0
```

**Comment by saw-jan** [comment] 2023-10-27 13:15
Yeah, by default ocis doesn't allow basic auth. we need to enable basic-auth using `PROXY_ENABLE_BASIC_AUTH`.

**Comment by S-Panta** [comment] 2024-01-24 05:00
Closing this issue as all the task has been completed.

**Closed** 2024-01-24 05:04 UTC
Labels: QA:team
