### ISSUE TITLE
 e2e test integrations/searchProjectSpace.ocis.feature:3 failed in nightly

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/ocis#4849] opened 2022-10-19 03:50 UTC
Build: https://drone.owncloud.com/owncloud/ocis/16226/78/9
Following scenario failed on nightly and needs further investigation 
```
Scenario: Search in the project spaces (attempt 1, retried) # tests/e2e/cucumber/features/integrations/searchProjectSpace.ocis.feature:3
   ✔ Before # tests/e2e/cucumber/environment/index.ts:36
   ✔ Given "Admin" creates following users # tests/e2e/cucumber/steps/api.ts:6
       | id    |
       | Alice |
   ✔ And "Admin" assigns following roles to the users # tests/e2e/cucumber/steps/api.ts:20
       | id    | role       |
       | Alice | SpaceAdmin |
   ✔ When "Alice" logs in # tests/e2e/cucumber/steps/runtime/session.ts:19
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/runtime/application.ts:5
   ✔ And "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✔ And "Alice" creates the following project spaces # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:11
       | name | id     |
       | team | team.1 |
   ✔ And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:18
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:12
       | resource                   | type   |
       | folder(WithSymbols:!;_+-&) | folder |
   ✔ And "Alice" uploads the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:19
       | resource               | to                         |
       | new-'single'quotes.txt | folder(WithSymbols:!;_+-&) |
   ✔ And "Alice" navigates to the personal space page # tests/e2e/cucumber/steps/app-files/page/spaces/personal.ts:5
   ✔ When "Alice" searches "-'s" using the global search # tests/e2e/cucumber/steps/app-files/resource.ts:134
   ✖ Then following resources should be displayed in the search list for user "Alice" # tests/e2e/cucumber/steps/app-files/resource.ts:139
       | resource               |
       | new-'single'quotes.txt |
       Error: expect(received).toBe(expected) // Object.is equality

       Expected: true
       Received: false
           at Proxy.<anonymous> (/drone/src/webTestRunner/node_modules/@playwright/test/lib/expect.js:165:37)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/app-files/resource.ts:146:39)
   - But following resources should not be displayed in the search list for user "Alice" # tests/e2e/cucumber/steps/app-files/resource.ts:139
       | resource                   |
       | folder(WithSymbols:!;_+-&) |
   - When "Alice" searches "!;_+-&)" using the global search # tests/e2e/cucumber/steps/app-files/resource.ts:134
   - Then following resources should be displayed in the search list for user "Alice" # tests/e2e/cucumber/steps/app-files/resource.ts:139
       | resource                   |
       | folder(WithSymbols:!;_+-&) |
   - But following resources should not be displayed in the search list for user "Alice" # tests/e2e/cucumber/steps/app-files/resource.ts:139
       | resource               |
       | new-'single'quotes.txt |
   - And "Alice" logs out # tests/e2e/cucumber/steps/runtime/session.ts:28
   ✔ After # tests/e2e/cucumber/environment/index.ts:83
```

**Comment by SwikritiT** [comment] 2022-10-19 04:24
failed here too: https://drone.owncloud.com/owncloud/ocis/16227/78/9

**Comment by saw-jan** [comment] 2022-10-19 05:24
The description has a different build link :cry:

**Comment by SwikritiT** [comment] 2022-10-19 05:35
> The description has a different build link cry

Sorry for my mistake. I copy pasted the wrong link. It's updated now

**Comment by saw-jan** [comment] 2022-10-19 05:57
As per the initial investigation, the test failure is due to the race condition. Search shows `No results` on normal test run speed but passes with some slow-mo set.
![ss](https://user-images.githubusercontent.com/52366632/196608659-e96e8273-5a00-4172-b796-02b54d8e4a29.jpeg)

**Comment by ScharfViktor** [comment] 2022-10-19 09:53
test ran locally for me at the default speed. I think it isn't due to the race condition, perhaps the re-creation of the search index was slower than the test.


A file has been created, but not found. The test waits for the upload and after the upload clicks `#close-upload-info-btn`. `npx playwright show-trace https://cache.owncloud.com/public/16226/tracing/search-in-the-project-spaces-alice-2022-10-19-01-35-32.zip`

**Comment by saw-jan** [comment] 2022-10-19 10:00
> test ran locally for me at the default speed. I think it isn't due to the race condition, perhaps the re-creation of the search index was slower than the test.
> 
> A file has been created, but not found. The test waits for the upload and after the upload clicks `#close-upload-info-btn`. `npx playwright show-trace https://cache.owncloud.com/public/16226/tracing/search-in-the-project-spaces-alice-2022-10-19-01-35-32.zip`

Yeah true, file upload is successful everytime. Search index might have taken some more time to be updated.
This very exact problem was also with acceptance tests a while ago and there the explicit wait was added as a means to reduce the flackyness (see https://github.com/owncloud/web/pull/7675/commits/f77d04015c66770718637f4668ce293166cb6874)

Without using waits I couldn't find other solution for this. @ScharfViktor What do you suggest?

**Comment by saw-jan** [comment] 2022-10-19 10:02
> test ran locally for me at the default speed.

For me, test fails locally everytime. Only works if wait is added (`> ~500ms`)

**Comment by ScharfViktor** [comment] 2022-10-19 10:14
> Without using waits I couldn't find other solution for this. @ScharfViktor What do you suggest?

let me think about it. It's hard to do anything when it's not reproduce. Maybe before normal searching send first REPORT request as check health? To eliminate the strick waiting

**Comment by saw-jan** [comment] 2022-10-19 11:17
PR has been created but to take that into effect, web commit id needs to be bumped here in oCIS.

**Comment by saw-jan** [comment] 2022-10-25 03:57
Web commit bump has been made in PR https://github.com/owncloud/ocis/pull/4878 so now the new web test codes have been applied in oCIS.
Closing here!

**Closed by saw-jan** 2022-10-25 03:57 UTC
Labels: QA:team
