### ISSUE TITLE
when selecting a file unrelated shares are shown

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#592] opened 2020-09-18 08:23 UTC
when creating a new folder and selecting it in phoneix it will trigger two requests:

```
curl 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Ffrom%20einstein%20ro&reshares=true' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'authorization: Bearer ...' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36' \
  -H 'OCS-APIREQUEST: true' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'Accept: */*' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://localhost:9200/' \
  -H 'Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' \
  --compressed \
  --insecure
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>ok</status><statuscode>100</statuscode><message>OK</message></meta><data></data></ocs>
```

as well as

```
curl 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Ffrom%20einstein%20ro&shared_with_me=true' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'authorization: Bearer ...' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36' \
  -H 'OCS-APIREQUEST: true' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'Accept: */*' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://localhost:9200/' \
  -H 'Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' \
  --compressed \
  --insecure
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>ok</status><statuscode>100</statuscode><message>OK</message></meta><data><element><id>b79a6693-6d10-46a2-a561-f17b4513ab5d</id><share_type>0</share_type><uid_owner>f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c</uid_owner><displayname_owner>Marie Curie</displayname_owner><permissions>3</permissions><stime>1600169168</stime><parent></parent><expiration></expiration><token></token><uid_file_owner>f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c</uid_file_owner><displayname_file_owner>Marie Curie</displayname_file_owner><additional_info_owner></additional_info_owner><additional_info_file_owner></additional_info_file_owner><state>0</state><path></path><item_type></item_type><mimetype></mimetype><storage_id></storage_id><storage>0</storage><item_source></item_source><file_source></file_source><file_parent></file_parent><file_target></file_target><share_with>4c510ada-c86b-4815-8820-42cdf82c3d51</share_with><share_with_displayname>Albert Einstein</share_with_displayname><share_with_additional_info></share_with_additional_info><mail_send>0</mail_send><name></name></element></data></ocs>
```

the latter is a bug because we get an entry where marie is the owner (which makes sense as we are listing incoming shares).

the path does not seem to be taken into account.

might be caused by stale data? but even when creating a folder with a random name I see marie as owner ...

**Comment by pmaier1** [comment] 2020-09-18 08:40
Duplicate of https://github.com/owncloud/ocis/issues/574 ?

**Closed** 2021-01-12 11:15 UTC
Labels: bug
