### ISSUE TITLE
Searching for a user or group is case-sensitive

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#3534] opened 2022-04-13 20:29 UTC
ocis local v.1.20

- start ocis with idm (https://owncloud.dev/extensions/idm/setup/)
- create new user "marie" (displayName and onPremisesSamAccountName- low case)
- create new group "new group" (displayName is low case)
- try to share file to "Marie" or "New group"

Expected: Marie and the New Group are found in the sharing dialog

Actual: user or group not found. 
and reverse: If we create a user or group in upper case, we cannot find them in lower case.

**Comment by phil-davis** [comment] 2022-04-14 04:44
Note: in oC10 groups are case-sensitive. "Finance" and "finance" are two different groups. But when starting to share with "Fina" or "fina" both groups "Finance" and "finance" are shown as possibilities in the classic webUI and by the API that returns the potential matches.

In oC10 users are not case-sensitive - "Marie" and "marie" are the same user.

**Comment by rhafer** [comment] 2022-07-14 12:28
Duplicate of https://github.com/owncloud/ocis/issues/547

**Closed** 2022-07-14 13:08 UTC
Labels: Type:Bug
