### ISSUE TITLE
S3NG performs cross-storage move on uploads

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#4343] opened 2022-08-05 09:27 UTC
## Describe the bug
The S3NG storage driver performs a cross-storage move on uploads.

## Steps to reproduce
1. Use oCIS with S3NG storage driver
2. Upload a file

## Expected behavior
The file is written directly on the final storage (no cross-storage move happens)

## Actual behavior
A cross storage move happens

## Additional context

When the upload is finished, the blob is written:
https://github.com/cs3org/reva/blob/5eb6e708af1f7cdd4ae1f950610b0fceff96c28e/pkg/storage/utils/decomposedfs/upload.go#L552

In case of the S3 blobstore, it's a cross storage move:

https://github.com/cs3org/reva/blob/5eb6e708af1f7cdd4ae1f950610b0fceff96c28e/pkg/storage/fs/s3ng/blobstore/blobstore.go#L62-L79

**Comment by aduffeck** [comment] 2022-09-16 07:58
@wkloucek hm, we could use pre-signed URLs or try to implement other means of bypassing the provider storage when uploding files to S3NG, but the data has to be available at some point anyway for checksuming and post-processing (in experimental). So we need the payload on the provider before offloading it to the blobstore by design, no?

**Comment by aduffeck** [comment] 2022-09-20 09:56
@micbar after some discussion we came up with 3 approaches for handling that issue:

1. Bypass the dataprovider completely during upload by using presigned URLs. That minimizes load and traffic on the provider but will require bigger changes, including changes to the clients to support that kind of upload.
2. Make the clients upload to the data provider as before but stream the data directly to the S3 blobstore instead of holding it locally until the upload has been finished. That will reduce the amount of disk space required for uploads but still cause load and traffic on the provider.
3. Keep the process as it currently is and just document the requirements for storage in relation to the number and size of uploads that should be supported.

Please let us know how to proceed here.

**Comment by butonic** [comment] 2022-09-27 11:11
The upload process will become async in the near future. So copying from the blobstore to s3 is ok for now.

That being said, it would makes sense to improve the S3NG implementation to use the native object versioning to implement file versions. File objects should use the fille id as the object name and versions should be written to that object. For that the tus upload should directly stream to S3 to the final object ... 💥 

That would be a violation against the existing requirements: A file must remain in a quarantine area until a workflow moves it to the final destination. Otherwise the file (potentially carrying a virus) may aready have been downloaded by another client.

The cross storage move is by design.

We could however store the upload blob on S3 and use the s3 COPY from RPC call to leave the copy to the s3 server, omitting streaming back and fourth data.

**Comment by micbar** [comment] 2022-09-27 11:24
ok, @wkloucek @pmaier1 @hodyroff 

From my POV the requirement, that the file is uploaded to the upload area before we move it to the final storage has more weight. It is important for preprocessing steps like virus scanning. Especially if we have WORM storage.

Closing this ticket.

**Closed by micbar** 2022-09-27 11:24 UTC
Labels: Type:Technical-Debt, Category:Defect, Storage:S3NG

**Comment by hodyroff** [comment] 2022-09-27 11:29
Yes, lateron we might want to have a storage driver in addition to this one who takes the direct route and where we delete again or just call the file lost if we want to get rid of it later ...
