### ISSUE TITLE
[QA] OCM invitations cannot be accepted any more

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#10384] opened 2024-10-22 13:20 UTC
## Describe the bug

This is reproducable with v6.6.0 and also todays daily.

Setup two machines with e.g.

env OCIS_DNSNAME=dog-66-DATE OCIS_VERSION=v6.6.0 ./deploy_ocis_bare_metal.sh
env OCIS_DNSNAME=cat-66-DATE OCIS_VERSION=v6.6.0 ./deploy_ocis_bare_metal.sh

* the machines are mutually registered in /etc/ocis/ocmproviders.json
* user alice at cat visits the sciencemesh app and create an invite token for user bob at dog.
* user bob at dog enters the token, selects cat as institution of inviter, and clicks on accept. An error occurs:

![image](https://github.com/user-attachments/assets/181e4d2e-d5fa-40ac-8118-83463c86adac)

The X-Requiest-Id fb960496-86df-4c11-883f-d519c19ea4c0 is only seen twice in the log of machine dog (and not at all in the other machine):

```
journalctl -u ocis | grep fb960496-86df-4c11-883f-d519c19ea4c0
Oct 22 13:13:35 jw-ocis-v6-6-0-ong ocis[5930]: {"level":"debug","service":"ocm","pkg":"rhttp","traceid":"01583f850f1d56c8d5655cb98d20be9f","request-id":"fb960496-86df-4c11-883f-d519c19ea4c0","path":"/accept-invite","time":"2024-10-22T13:13:35Z","line":"github.com/cs3org/reva/v2@v2.26.0/internal/http/services/sciencemesh/sciencemesh.go:139","message":"sciencemesh routing"}
Oct 22 13:13:35 jw-ocis-v6-6-0-ong ocis[5930]: {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"fb960496-86df-4c11-883f-d519c19ea4c0","traceid":"3038021891a0e3698c106d8759578e18","remote-addr":"87.156.130.141","method":"POST","status":401,"path":"/sciencemesh/accept-invite","duration":35.622618,"bytes":74,"time":"2024-10-22T13:13:35Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
```

On the other machine, the log shows:
```
...
Oct 22 13:28:50 jw-ocis-v6-6-0-nmn ocis[5932]: {"level":"debug","service":"ocm","pkg":"rgrpc","traceid":"4e967a082389b03621c2f3e55de44233","time":"2024-10-22T13:28:50Z","line":"github.com/cs3org/reva/v2@v2.26.0/pkg/ocm/provider/authorizer/json/json.go:153","message":"Comparing 'dog-66-20241022.jw-qa.owncloud.works' to 'dog-66-20241022.jw-qa.owncloud.works'"}
Oct 22 13:28:50 jw-ocis-v6-6-0-nmn ocis[5932]: {"level":"debug","service":"ocm","pkg":"rgrpc","traceid":"4e967a082389b03621c2f3e55de44233","user-agent":"grpc-go/1.67.1","from":"tcp://127.0.0.1:58436","uri":"/cs3.ocm.provider.v1beta1.ProviderAPI/IsProviderAllowed","start":"22/Oct/2024:13:28:50 +0000","end":"22/Oct/2024:13:28:50 +0000","time_ns":448311,"code":"OK","time":"2024-10-22T13:28:50Z","line":"github.com/cs3org/reva/v2@v2.26.0/internal/grpc/interceptors/log/log.go:69","message":"unary"}
Oct 22 13:28:50 jw-ocis-v6-6-0-nmn ocis[5932]: {"level":"debug","service":"gateway","pkg":"rgrpc","traceid":"4e967a082389b03621c2f3e55de44233","user-agent":"grpc-go/1.67.1","from":"tcp://127.0.0.1:50906","uri":"/cs3.gateway.v1beta1.GatewayAPI/IsProviderAllowed","start":"22/Oct/2024:13:28:50 +0000","end":"22/Oct/2024:13:28:50 +0000","time_ns":978115,"code":"OK","time":"2024-10-22T13:28:50Z","line":"github.com/cs3org/reva/v2@v2.26.0/internal/grpc/interceptors/log/log.go:69","message":"unary"}
Oct 22 13:28:50 jw-ocis-v6-6-0-nmn ocis[5932]: {"level":"error","service":"ocm","pkg":"rhttp","traceid":"5511c31e4b0e4a08203d7e92bfc412a7","request-id":"jw-ocis-v6-6-0-nmn/KWmYrnx181-000985","error":"error verifying mesh provider","time":"2024-10-22T13:28:50Z","line":"github.com/cs3org/reva/v2@v2.26.0/internal/http/services/reqres/reqres.go:64","message":"provider not trusted"}
...
```

Is there a way to verify machine trust state?

The entries in /etc/ocis/ocmproviders.json look like this:
```
{
  "name": "dog-66-20241022",
  "full_name": "dog-66-20241022 provider",
  "organization": "oCIS",
  "domain": "dog-66-20241022.jw-qa.owncloud.works",
  "homepage": "https://dog-66-20241022.jw-qa.owncloud.works",
  "services": [
    {
      "endpoint": {
        "type": {
          "name": "OCM",
          "description": "dog-66-20241022.jw-qa.owncloud.works Open Cloud Mesh API"
        },
        "name": "dog-66-20241022 - OCM API",
        "path": "https://dog-66-20241022.jw-qa.owncloud.works/ocm/",
        "is_monitored": true
      },
      "api_version": "0.0.1",
      "host": "http://dog-66-20241022.jw-qa.owncloud.works"
    },
    {
      "endpoint": {
        "type": {
          "name": "Webdav",
          "description": "dog-66-20241022.jw-qa.owncloud.works Webdav API"
        },
        "name": "dog-66-20241022 - Webdav API",
        "path": "https://dog-66-20241022.jw-qa.owncloud.works/dav/",
        "is_monitored": true
      },
      "api_version": "0.0.1",
      "host": "https://dog-66-20241022.jw-qa.owncloud.works"
    }
  ]
}
```

## Expected behavior
As per 6.5.0 the exactly same procedure created a mutual trust between users bob and alice.

**Comment by micbar** [comment] 2024-10-23 07:45
@ScharfViktor Can you confirm?

**Comment by micbar** [comment] 2024-10-23 07:47
@jnweiger @hodyroff 
We have that test running in CI and it works fine.

Let us find out what the issue is.

**Comment by ScharfViktor** [comment] 2024-10-23 08:35
> @ScharfViktor Can you confirm?

maybe some configuration issue? 
I checked using https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm
and accepting invitation works fine
<img width="1670" alt="Screenshot 2024-10-23 at 10 31 08" src="https://github.com/user-attachments/assets/01a48708-ca9a-4ba5-8a26-80dd6a88b9f1">

We also have an apiTests for this, which are green in Ci https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiOcm/acceptInvitation.feature

**Comment by ScharfViktor** [comment] 2024-10-23 08:38
my ocmproviders.json looks differently. maybe here is problem?
https://github.com/owncloud/ocis/blob/master/tests/config/drone/providers.json

**Comment by jnweiger** [comment] 2024-10-23 16:15
@ScharfViktor your ocmproviders.json differs
*  it misses the webdav endpoint.
* it has the port number in the domain. 
I could not see any other differences.

I doubt, that this is relevant. My exact same setup still works perfectly fine, when using the https://download.owncloud.com/ocis/ocis/rolling/6.5.0/ocis-6.5.0-linux-amd64 binary.

**Comment by micbar** [comment] 2024-10-23 16:37
Maybe related to https://github.com/owncloud/ocis/issues/10355

**Comment by micbar** [comment] 2024-10-23 16:38
@jnweiger how is your OCM_OCM_PROVIDER_AUTHORIZER_VERIFY_REQUEST_HOSTNAME config?

**Comment by micbar** [comment] 2024-10-23 16:38
We changed the default to true (security by default).

**Comment by micbar** [comment] 2024-10-23 17:55
Needs fixing. See related issue.

**Comment by 2403905** [comment] 2024-10-24 08:41
@jnweiger  I can't reproduce an issue. Your config doesn't look like a fool. The federated part is missing. Could you please share the full config.

**Comment by 2403905** [comment] 2024-10-24 14:00
@jnweiger FYI https://github.com/owncloud/ocis/issues/10355

**Comment by rhafer** [comment] 2024-10-24 14:36
Let's close this if it's just a duplicate of #10355

**Closed by rhafer** 2024-10-24 14:36 UTC
Labels: Type:Bug, QA:p2
