### ISSUE TITLE
[Sharing-NG] can't get sharing permission for a resource

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis#9541] opened 2024-07-05 08:15 UTC
## Describe the bug
I can not get permission of a particular share using both root and permissions endpoint. which should be possible according to the api specifications on:
https://owncloud.dev/libre-graph-api/#/drives.permissions/GetPermission
https://owncloud.dev/libre-graph-api/#/drives.root/GetPermissionSpaceRoot

## Steps to reproduce
1. create a link share of a resource
```bash
curl -k -XPOST https://localhost:9200/graph/v1beta1/drives/{drive-id}/items/{item-id}/createLink -uadmin:admin
```
2. get sharing permission for that resource
```bash
curl -k -XGET https://localhost:9200/graph/v1beta1/drives/{drive-id}/items/{item-id}/permissions/{permission-id} -uadmin:admin
```

## Expected behavior
The request should given the permission of the share 

## Actual behavior
The request gives `405` status code
```bash
< HTTP/1.1 405 Method Not Allowed
< Allow: PATCH
< Allow: DELETE
```

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
ownCloud Web UI 9.1.0-alpha.1
 Infinite Scale 6.0.0+aa6041abb6 Community
```

</p>
</details>

**Comment by saw-jan** [comment] 2024-07-12 06:38
CC @micbar @rhafer

**Comment by 2403905** [comment] 2024-07-12 15:32
The endpoint is not implemented.
We can retrieve the item permission via https://owncloud.dev/libre-graph-api/#/drives.permissions/ListPermissions

**Comment by rhafer** [comment] 2024-08-05 09:03
Duplicate of #8616

**Closed by rhafer** 2024-08-05 09:03 UTC
Labels: Type:Bug
