### ISSUE TITLE
folder share with edit permission - error with WOPI

### ISSUE THREAD

**Issue by dj4oC** [owncloud/ocis#8834] opened 2024-04-11 06:48 UTC
oCIS 5.0.0

Steps to reproduce:

1. create a folder
2. create a txt and a docx/pptx/xlsx document in that folder
3. share that folder with edit permissions
4. the share receiver can edit the txt document
5. the share receiver can not edit the docx/pptx/xlsx document 
6. the share receiver can not create a new docx/pptx/xlsx document 
7. the share receiver can create a new txt document 
8. the share receiver can not upload a docx/pptx/xlsx document 
9. the share receiver can not upload a txt document 

https://github.com/owncloud/ocis/assets/115982880/8020c358-d9f5-43c1-bc02-e2a384716e0e

**Comment by wkloucek** [comment] 2024-04-11 07:02
I'm not sure if we run the WOPI validator on public links in the meantime (https://github.com/owncloud/ocis/issues/5111, https://github.com/owncloud/ocis/issues/8712)

**Comment by micbar** [comment] 2024-04-11 07:27
Public link?

**Comment by dj4oC** [comment] 2024-04-11 08:32
> Public link?
yes

**Comment by micbar** [comment] 2024-04-11 09:36
Duplicate of #8691 and https://github.com/owncloud/enterprise/issues/6558

We are already on it.

Thanks for reporting.

EE issue from customer has Sev3, P3. Aligning.

**Comment by micbar** [comment] 2024-04-11 09:38
> I'm not sure if we run the WOPI validator on public links in the meantime (#5111, #8712)

Not related to WOPI. 

WOPI testing plans are here https://github.com/owncloud/ocis/issues/8712 for the new collaboration service.

**Comment by dj4oC** [comment] 2024-04-12 05:57
New finding: Also upload of office documents does not work. upload of text files work fine.

**Comment by micbar** [comment] 2024-04-15 14:14
> New finding: Also upload of office documents throughs an error after upload.

Not reproducable on the vanilla product.

**Closed** 2024-04-16 15:13 UTC
Labels: Type:Bug, Priority:p3-medium

**Comment by micbar** [comment] 2024-04-17 11:47
@ScharfViktor moved to "needs tests"

**Comment by ScharfViktor** [comment] 2024-04-17 11:59
> @ScharfViktor moved to "needs tests"

thanks. we'll create test for that
already tested it manualy. works fine 

same issue: https://github.com/owncloud/ocis/issues/8691
