### ISSUE TITLE
Name of public link is empty and not "Public link" when not specified in the create request

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/ocis#1237] opened 2020-07-20 08:10 UTC
#### webUI
1.  from ocis repo start ocis `bin/ocis server` . For details about the setup, check the section `run tests > with Ocis backend` https://owncloud.github.io/clients/web/testing/
2. Using webUI create public link for a file or folder
3. Now check the link of the created public share
Here public link's name in my case is `EJYhMuvpVSBuXyZ`:
![Screenshot from 2020-07-20 13-33-37](https://user-images.githubusercontent.com/34328907/87912776-ac694100-ca8d-11ea-93a2-491c7ce28a75.png)

#### Using api:
1. from ocis repo start phoenix `bin/ocis server` . For details about the setup, check the section `run tests > with Ocis backend` https://owncloud.github.io/clients/web/testing/

2. upload a file or a folder 

`curl -X PUT http://localhost:9140/remote.php/webdav/hari.txt -d "123" -u user1:1234`

3. make sure the file is uploaded

`curl -X PROPFIND http://localhost:9140/remote.php/webdav/hari.txt -u user1:1234 | xmllint --format -`

4. create a public share

`curl -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -u user1:1234 -d "permission=31&path=hari.txt&shareType=3" | xmllint --format -`

5. Now get the info of public share
`curl -X GET http://localhost:9140/ocs/v2.php/apps/files_sharing/api/v1/shares -u user1:1234 | xmllint --format -`

Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>200</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>SsInZvPdwNZsBhj</id>
      <share_type>3</share_type>
      <uid_owner>user1</uid_owner>
      <displayname_owner>User One</displayname_owner>
      <permissions>1</permissions>
      <stime>1595231914</stime>
      <parent/>
      <expiration/>
      <token>AZLsBDSMUTcrRsx</token>
      <uid_file_owner>user1</uid_file_owner>
      <displayname_file_owner>User One</displayname_file_owner>
      <additional_info_owner/>
      <additional_info_file_owner/>
      <state>0</state>
      <path>/hari.txt</path>
      <item_type>file</item_type>
      <mimetype>text/plain</mimetype>
      <storage_id>1284d238-aa92-42ce-bdc4-0b0000009154</storage_id>
      <storage>0</storage>
      <item_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjYzMGYyOWQ1LThmMjQtNDA2ZC04NTc1LWM3NTZjMmMzZTEwNg==</item_source>
      <file_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjYzMGYyOWQ1LThmMjQtNDA2ZC04NTc1LWM3NTZjMmMzZTEwNg==</file_source>
      <file_parent/>
      <file_target>/hari.txt</file_target>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <name/>
      <url>https://localhost:9200/#/s/AZLsBDSMUTcrRsx</url>
    </element>
  </data>
</ocs>
```
Here as you can see `<name />` is empty.

### Expected Behavior
1. Create public link in phoenix webUI
2. Check the name of last created public share:
![Screenshot from 2020-07-20 13-52-22](https://user-images.githubusercontent.com/34328907/87914415-4fbb5580-ca90-11ea-865e-c4bd4464cf02.png)

As you can see in above screen shot the name of public share is `Public link`

#### using api
If you get the info of the last public share:
`curl -X GET http://localhost/core2/ocs/v2.php/apps/files_sharing/api/v1/shares -u hari:admin | xmllint --format -`

Response:
```
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>200</statuscode>
    <message/>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data>
    <element>
      <id>251</id>
      <share_type>3</share_type>
      <uid_owner>hari</uid_owner>
      <displayname_owner>hari</displayname_owner>
      <permissions>1</permissions>
      <stime>1595232043</stime>
      <parent/>
      <expiration/>
      <token>PjDt5quoBjwD8Zn</token>
      <uid_file_owner>admin</uid_file_owner>
      <displayname_file_owner>admin</displayname_file_owner>
      <additional_info_owner/>
      <additional_info_file_owner/>
      <path>/test.txt</path>
      <item_type>file</item_type>
      <mimetype>text/plain</mimetype>
      <storage_id>shared::/test.txt</storage_id>
      <storage>1</storage>
      <item_source>2147485106</item_source>
      <file_source>2147485106</file_source>
      <file_parent>2147483955</file_parent>
      <file_target>/test.txt</file_target>
      <name>Public link</name>
      <url>http://localhost/core2/index.php/s/PjDt5quoBjwD8Zn</url>
      <mail_send>0</mail_send>
      <attributes/>
    </element>
  </data>
</ocs>
```

You can clearly see the name in response is `Public link` i.e. `<name>Public link</name>`

**Comment by refs** [comment] 2021-01-18 11:42
can confirm still happens in the current master.

**Comment by ScharfViktor** [comment] 2021-08-31 10:56
checked with a version oCIS 1.11.0:
it continues to happen:
<img width="1430" alt="Screenshot 2021-08-31 at 12 50 52" src="https://user-images.githubusercontent.com/84779829/131490565-4be8383a-ff33-42cc-ae03-e9db7a7c8d17.png">

There are 3 links in the screenshot: 
1- created using api
2- created using web (without name)
3- created using web (with name)

**Comment by ScharfViktor** [comment] 2022-05-18 20:43
That is low bug but it blocks UI test that we are running **2 years** every day in web CI and ocis CI(because has tag smokeTest)

test: https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature#L15-L35

I suggest some solutions:
1.  fix bug. Web is sending name "Public link" by default as in oc10
<img width="1187" alt="Screenshot 2022-05-18 at 17 14 14" src="https://user-images.githubusercontent.com/84779829/169151052-615e7043-1de7-405e-ba50-74a3d7466e70.png">

2. I can skip test for ocis (stop wasting time in CI)
3. I can change test. Drop checking `And a link named "Public link" should be listed with role "<role>" in the public link list of folder "simple-folder" on the webUI` and `| name        | Public link    |`.  test continues to be useful

@individual-it @pascalwengerter what do you think about?

**Comment by individual-it** [comment] 2022-05-19 03:36
If that is easy to fix I would prefer to fix the issue

**Comment by pascalwengerter** [comment] 2022-05-19 08:24
This is a capability which needs to be set, opening a PR in a second

**Comment by SwikritiT** [comment] 2022-05-23 09:55
Reopening as it's still reproducible in current master

```console
curl -vk -X POST https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares -u admin:admin -d "permission=31&path=test.txt&shareType=3" | xmllint --format -
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:9200...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [6 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [835 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=Acme Corp; CN=OCIS
*  start date: May 23 08:10:51 2022 GMT
*  expire date: May 23 08:10:51 2023 GMT
*  issuer: O=Acme Corp; CN=OCIS
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Server auth using Basic with user 'admin'
} [5 bytes data]
> POST /ocs/v1.php/apps/files_sharing/api/v1/shares HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 39
> Content-Type: application/x-www-form-urlencoded
> 
} [39 bytes data]
* upload completely sent off: 39 out of 39 bytes
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [130 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 1307
< Content-Type: text/xml; charset=utf-8
< Date: Mon, 23 May 2022 08:17:24 GMT
< Ocs-Api-Version: 1
< Vary: Origin
< 
{ [1035 bytes data]
100  1346  100  1307  100    39  18671    557 --:--:-- --:--:-- --:--:-- 19228
* Connection #0 to host localhost left intact
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <id>NOrpePcySKhOFDL</id>
    <share_type>3</share_type>
    <uid_owner>admin</uid_owner>
    <displayname_owner>Admin</displayname_owner>
    <additional_info_owner>admin@example.org</additional_info_owner>
    <permissions>1</permissions>
    <stime>1653293844</stime>
    <parent/>
    <expiration/>
    <token>zFpfTrYcEQZhJJB</token>
    <uid_file_owner>admin</uid_file_owner>
    <displayname_file_owner>Admin</displayname_file_owner>
    <additional_info_file_owner>admin@example.org</additional_info_file_owner>
    <state>0</state>
    <path>/test.txt</path>
    <item_type>file</item_type>
    <mimetype>text/plain</mimetype>
    <storage_id>shared::/test.txt</storage_id>
    <storage>0</storage>
    <item_source>1284d238-aa92-42ce-bdc4-0b0000009157$a89a7294-887b-4ab6-8314-37b324fafcb3!5228a30b-b943-4c9f-bf75-3ea73461c5f0</item_source>
    <file_source>1284d238-aa92-42ce-bdc4-0b0000009157$a89a7294-887b-4ab6-8314-37b324fafcb3!5228a30b-b943-4c9f-bf75-3ea73461c5f0</file_source>
    <file_parent/>
    <file_target>/test.txt</file_target>
    <share_with_user_type>0</share_with_user_type>
    <share_with_additional_info/>
    <mail_send>0</mail_send>
    <name/>
    <url>https://localhost:9200/s/zFpfTrYcEQZhJJB</url>
  </data>
</ocs>

```
And the related tests are still in expected to fail 
https://github.com/owncloud/ocis/blob/cd87caede944e757160ae6550733a7de38b4db43/tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md?plain=1#L22-L24

https://github.com/owncloud/ocis/blob/cd87caede944e757160ae6550733a7de38b4db43/tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md?plain=1#L30-L33

**Comment by ScharfViktor** [comment] 2022-05-23 12:50
You're right, it's still relevant.
![Screenshot 2022-05-23 at 14 48 44](https://user-images.githubusercontent.com/84779829/169823031-19c3f2b3-054a-41e7-9805-93fe84a0be0f.png)

**Comment by pascalwengerter** [comment] 2022-05-23 17:08
> You're right, it's still relevant. ![Screenshot 2022-05-23 at 14 48 44](https://user-images.githubusercontent.com/84779829/169823031-19c3f2b3-054a-41e7-9805-93fe84a0be0f.png)

Please note that the web UI part will be resolved via https://github.com/owncloud/web/pull/6961 (filling that field client-side). What @SwikritiT shows perhaps needs some minor tweak to the link-creation in oCIS which needs to take the capability introduced in #3834 into account

**Comment by pascalwengerter** [comment] 2022-12-16 13:07
@kulmann could you take a look and potentially close this issue? (Just checked and I'm still assigned)

- client-side we create links with a (translated) default name since https://github.com/owncloud/web/pull/6961
- server-side oCIS creates links with a default name which can be changed via capabilities https://github.com/owncloud/ocis/pull/3834

**Comment by kulmann** [comment] 2022-12-19 21:56
Doing the request via `curl` the link name is not empty anymore, but instead shows the public link token as name of the link. Which looks weird, but solves the issue and is somewhat ok, given that we don't have translations backend-wise. Expected failures mentioned by @SwikritiT also have been removed in the meantime. Closing here, thanks for the pointer.

**Closed by kulmann** 2022-12-19 21:56 UTC
Labels: Type:Bug, Category:Defect, Priority:p3-medium
