### ISSUE TITLE
[helm deployment] GDPR export by newly created user takes too long - probably generating doesn't finish

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#6168] opened 2023-04-27 11:16 UTC
Trying GDPR export by a fresh created user, report generation won't finish even after waiting significant time.

```bash
URL: https://ocis.kube.test/remote.php/dav/spaces/78d220ff-d7cf-4d68-8ef5-89e3e9365585%24c8503329-8731-4900-ba71-176b54113f92/.personal_data_export.json
Method: PROPFIND
Status: 200
```
```xml
<d:multistatus
	xmlns:s="http://sabredav.org/ns"
	xmlns:d="DAV:"
	xmlns:oc="http://owncloud.org/ns">
	<d:response>
		<d:href>/remote.php/dav/spaces/78d220ff-d7cf-4d68-8ef5-89e3e9365585$c8503329-8731-4900-ba71-176b54113f92/.personal_data_export.json</d:href>
		<d:propstat>
			<d:prop>
				<oc:permissions>RDNVWZ</oc:permissions>
				<oc:favorite>0</oc:favorite>
				<oc:fileid>78d220ff-d7cf-4d68-8ef5-89e3e9365585$c8503329-8731-4900-ba71-176b54113f92!3f9ee3cf-f998-4fe5-975e-d9424a8b8091</oc:fileid>
				<oc:file-parent>78d220ff-d7cf-4d68-8ef5-89e3e9365585$c8503329-8731-4900-ba71-176b54113f92!c8503329-8731-4900-ba71-176b54113f92</oc:file-parent>
				<oc:name>.personal_data_export.json</oc:name>
				<oc:owner-id>demo</oc:owner-id>
				<oc:owner-display-name>demo</oc:owner-display-name>
				<oc:privatelink>https://ocis.kube.test/f/78d220ff-d7cf-4d68-8ef5-89e3e9365585$c8503329-8731-4900-ba71-176b54113f92%213f9ee3cf-f998-4fe5-975e-d9424a8b8091</oc:privatelink>
				<d:getcontentlength>0</d:getcontentlength>
				<oc:size>0</oc:size>
				<d:getlastmodified>Thu, 27 Apr 2023 11:04:12 GMT</d:getlastmodified>
				<d:getetag>"9b500698d70001e5a4b3ee908dd67ee2"</d:getetag>
				<d:getcontenttype>application/json</d:getcontenttype>
				<d:resourcetype></d:resourcetype>
				<oc:tags></oc:tags>
			</d:prop>
			<d:status>HTTP/1.1 425 TOO EARLY</d:status>
		</d:propstat>
	</d:response>
</d:multistatus>
```

![Screenshot from 2023-04-27 16-59-30](https://user-images.githubusercontent.com/52366632/234846050-3d342951-7baa-4de7-b9d8-d4119ffd1bb7.png)

## Setup

Deployed via Helm charts: https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#kubernetes-and-helm

oCIS: `3.0.0-rc.1 Community`
Minikube: `1.30.1`
Kubernetes: `1.26.0`
OS: `Ubuntu22.04`

**Comment by micbar** [comment] 2023-04-27 13:43
Did you use the default config?

I don't know if the helm-charts enable ASYNC_POSTPROCESSING by default.

@kobergj what happens if we use the GDPR export with async postprocessing off

**Comment by saw-jan** [comment] 2023-04-27 16:34
> Did you use the default config?

Yeah, just followed the docs

**Comment by kobergj** [comment] 2023-04-28 07:27
> @kobergj what happens if we use the GDPR export with async postprocessing off?

Good point. That won't work atm. The file will be in `425` state forever

**Comment by micbar** [comment] 2023-05-02 09:53
needs fix.

**Comment by saw-jan** [comment] 2023-05-02 10:19
It works now with the latest helm chart.
What was the fix?

**Comment by kobergj** [comment] 2023-05-08 09:49
Latest helmchart has async uploads enabled. It only fails when async uploads are disabled.

**Comment by saw-jan** [comment] 2023-05-08 09:54
> Latest helmchart has async uploads enabled. It only fails when async uploads are disabled.

So, can it be closed?

**Comment by micbar** [comment] 2023-05-08 10:00
we should be safe that the feature also works for instances with postprocessing disabled.

**Comment by kobergj** [comment] 2023-05-09 09:24
Seems there was a different issue. I can't reproduce on current master, even with Async Postprocessing disabled.

Should we investigate why it didn't work before?

**Closed** 2023-05-09 12:19 UTC
Labels: Type:Bug, Type:Discussion, Priority:p2-high
