### ISSUE TITLE
deleting a share with wrong authentication returns OCS status 996 / HTTP 500

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#1229] opened 2020-07-09 10:44 UTC
1. create a folder: `curl -u user0:123456 -k http://localhost:9140/remote.php/webdav/FOLDER -X MKCOL`
2. share the folder `curl -u user0:123456 http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -d "permissions=17&path=%2FFOLDER&shareType=0&shareWith=user1" -X POST`
3.  use the share-id trying to delete the share as an other user `curl -u user1:1234 http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares/6321e2e1-2c15-47d5-ab11-9b385dcd9752 -X DELETE`

OCS status should be 404 and in case of OCS v2 the HTTP code should also be 404
but HTTP code is 500 and OCS status is 996

**Comment by refs** [comment] 2021-01-18 10:35
With the exact steps I got a different output:

![grafik](https://user-images.githubusercontent.com/6905948/104904140-23ba5780-5981-11eb-8773-c9b8e5646ce2.png)


Server logs:

![grafik](https://user-images.githubusercontent.com/6905948/104904166-2c129280-5981-11eb-856e-287b2360ce11.png)

[Testing with the latest master](https://github.com/owncloud/ocis/commit/f97f0d734261598315fdaeca309ecd1482ca6ed9)

**Comment by individual-it** [comment] 2021-01-18 10:59
- [ ] ToDo QA-team: retest and check if API tests exists that check the correct OCS & HTTP Status code

**Comment by saw-jan** [comment] 2021-01-25 07:47
trying to delete share as another user (sharee) with correct authentication:
```bash
curl -u moss:vista https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/43976314-a0f1-4213-9115-493bdbf16bf5 -X DELETE --insecure |xmllint --format -      ✔ ▓▒░
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   164  100   164    0     0  10250      0 --:--:-- --:--:-- --:--:-- 10250
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>996</statuscode>
    <message>grpc delete share request failed</message>
  </meta>
</ocs>
```
```bash
HTTP status code is 200
```
with incorrect authentication:
```bash
curl -u moss:1234 https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/43976314-a0f1-4213-9115-493bdbf16bf5 -X DELETE --insecure |xmllint --format -       ✔ ▓▒░
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
-:1: parser error : Document is empty

^
```
```bash
HTTP status code is 401
```

**Comment by saw-jan** [comment] 2021-01-25 07:49
> * [ ]  ToDo QA-team: retest and check if API tests exists that check the correct OCS & HTTP Status code

there seems no api test for this scenario
incoming PR

**Comment by kobergj** [comment] 2024-06-03 14:19
Not 100% sure this doesn't need fixing but since the impact is rather small and the issue is over 3 years old I'll just boldly close it. Sorry!

**Closed by kobergj** 2024-06-03 14:19 UTC
Labels: Type:Bug, Interaction:Needs-help
