### ISSUE TITLE
Implement prefer parameter to toggle output.

### ISSUE THREAD

**Issue by ainmosni** [owncloud/ocis#5445] opened 2023-01-23 11:15 UTC
To toggle the output of operations like alter classes, we want to use the `prefer` query parameter. Its behaviour should be as follows:

* Default: return the altered/created resource.
* `prefer=minimal`: Return NoContent

**Comment by rhafer** [comment] 2023-04-05 10:23
This is a bit of a duplicate of #5186 .

**Closed by rhafer** 2023-04-05 10:23 UTC
Labels: Category:Enhancement
