### ISSUE TITLE
[QA] Share lists deleted user as 'user'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#903] opened 2020-11-19 20:10 UTC
Setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost
From the WEB UI:

* moss creates user testy2
* marie shares folder testpic3 with testy2
* moss deletes user testy2
* marie inspects the sharing of her testpic3

![image](https://user-images.githubusercontent.com/1108546/99718503-3f9d9c00-2aab-11eb-9b6b-70007aeccbe7.png)

An unnamed user is seen  in the share. 

Expected behaviour: deleted user is leaves no traces in the shares he had received.

**Comment by individual-it** [comment] 2020-12-07 03:20
for QA-team: retest with owncloud & ocis storage drivers and add tests for this case (I think API tests should do because I guess the API does respond some wrong values)

**Comment by saw-jan** [comment] 2020-12-11 08:55
><em>marie inspects the sharing of her testpic3</em>

Above action makes call to 2 different APIs,

### API one (buggy 🐛)
```bash
curl --user moss:vista \
https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares\?path\=/shareit\&reshares\=true
```

#### Expected behavior
```xml
<ocs>
   <meta>
      <status>ok</status>
      <statuscode>100</statuscode>
      <message>OK</message>
   </meta>
   <data/>
</ocs>
```

#### Actual behavior
```xml
<ocs>
    <meta>
        <status>ok</status>
        <statuscode>100</statuscode>
        <message>OK</message>
    </meta>
    <data>
        <element>
            <id>dba65967-73de-4f0a-95bf-904f9645f15f</id>
            <share_type>0</share_type>
            <uid_owner>058bff95-6708-4fe5-91e4-9ea3d377588b</uid_owner>
            <displayname_owner>Maurice Moss</displayname_owner>
            <permissions>15</permissions>
            <stime>1607673851</stime>
            <parent/>
            <expiration/>
            <token/>
            <uid_file_owner>058bff95-6708-4fe5-91e4-9ea3d377588b</uid_file_owner>
            <displayname_file_owner>Maurice Moss</displayname_file_owner>
            <additional_info_owner/>
            <additional_info_file_owner/>
            <state>0</state>
            <path>/shareit</path>
            <item_type>folder</item_type>
            <mimetype>httpd/unix-directory</mimetype>
            <storage_id>1284d238-aa92-42ce-bdc4-0b0000009157</storage_id>
            <storage>0</storage>
            <item_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OmEwNjExMWMxLWJhYWUtNDRiZi1hZGRlLWQ2ZTMyYjY4YjRlZg==</item_source>
            <file_source>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OmEwNjExMWMxLWJhYWUtNDRiZi1hZGRlLWQ2ZTMyYjY4YjRlZg==</file_source>
            <file_parent/>
            <file_target>/shareit</file_target>
            <share_with>0951297f-9ad5-4bab-b45e-339a0c764fad</share_with>
            <share_with_displayname>doe</share_with_displayname>
            <share_with_additional_info/>
            <mail_send>0</mail_send>
            <name/>
        </element>
    </data>
</ocs>
```

### API two (works as aspected)
```bash
curl --user moss:vista \
https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares\?path\=/shareit\&shared_with_me\=true
```
#### Expected and Actual Behavior
```xml
<ocs>
   <meta>
      <status>ok</status>
      <statuscode>100</statuscode>
      <message>OK</message>
   </meta>
   <data/>
</ocs>
```

**Comment by individual-it** [comment] 2020-12-16 05:15
the first request you are talking about if requesting all initiated shares the second one is getting all received shares. So the first request demonstrates the bug

**Comment by dpakach** [comment] 2021-01-14 11:31
Added Bug demonstration test in https://github.com/owncloud/core/pull/38205/files

**Comment by ScharfViktor** [comment] 2021-09-06 09:53
re-tested with local server oCIS version 1.11.0.
It is reproduced

**Comment by grgprarup** [comment] 2024-04-30 09:14
The issue is fixed and cannot be reproduced in the latest version so closing it.

**Closed by grgprarup** 2024-04-30 09:14 UTC
Labels: Type:Bug, Category:Defect, Priority:p3-medium

**Comment by saw-jan** [comment] 2024-04-30 09:16
> The issue is fixed and cannot be reproduced in the latest version so closing it.

Test coverage was added in https://github.com/owncloud/core/pull/38205
