### ISSUE TITLE
Changing the logo is broken on 7.1.0-alpha

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ocis#6579] opened 2023-06-21 14:46 UTC
## Describe the bug

Changing the logo is broken

## Steps to reproduce

1. Upload a logo
2. Reload the UI

## Expected behavior
New logo is uploaded and visible

## Actual behavior
Nothing changed

## Setup
Tested on https://ocis.ocis-web.latest.owncloud.works/

ownCloud | Infinite Scale Community
3.1.0-next.2+5c7b15eae
7.1.0-alpha.1

**Comment by pascalwengerter** [comment] 2023-06-21 16:01
@ChrisEdS "logo" as in theming or "logo" as in "space image"? Most likely a web issue though?

**Comment by micbar** [comment] 2023-06-21 17:18
@pascalwengerter @ChrisEdS There should be an existing issue.


Duplicate of https://github.com/owncloud/ocis/issues/6122

It is not actually broken, browser caching issue, needs a hard reload.

**Closed by micbar** 2023-06-21 17:18 UTC
Labels: Type:Bug

**Comment by ChrisEdS** [comment] 2023-06-21 22:36
Yes I know, but I tried it in an incognito window, also with opened console and disabled cache

**Comment by micbar** [comment] 2023-06-22 06:44
I need more context. It works on https://ocis.ocis-wopi.latest.owncloud.works/

**Comment by ChrisEdS** [comment] 2023-06-22 07:01
Indeed, but not on https://ocis.ocis-web.latest.owncloud.works/ 

🤷‍♂️
