### ISSUE TITLE
[QA] Shared folder indications only visible after reloading

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#891] opened 2020-11-18 14:12 UTC
Setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost

At the WEB UI
* login in as einstein, create a folder 'To-Richard' and share it with richard.
* login as richard, accept the share.
* login as einstein, check the status: 
![image](https://user-images.githubusercontent.com/1108546/99540725-3085f380-29b0-11eb-9778-ecd3f59c3fd9.png)
-> The sharing icon under the folder name 'To-Richard' is missing. BAD.
* open the sharing dialog of 'To-Richard'
![image](https://user-images.githubusercontent.com/1108546/99540906-6dea8100-29b0-11eb-9459-79bcf41a96ce.png)
-> The sharing icon under the folder name 'To-Richard' now appears. Okayish
->  But the dialog shows nobody. BAD.

* click the up arrow next to 'People' twice. Now the dialog shows how it is shared.
![image](https://user-images.githubusercontent.com/1108546/99541216-d6d1f900-29b0-11eb-9345-65f03a0f2037.png)

Expected behaviour: The icon should always be under the folder name, the list of users should be visible immediately when opening the sharing dialog.

**Comment by kulmann** [comment] 2020-12-09 10:04
@jnweiger I can't reproduce that part: `-> But the dialog shows nobody. BAD.`. Your screenshot shows the form for adding people. That is in fact what happens when you click on the quick action for adding people. Could that be the icon you clicked, instead of the left one you're hovering over in the screenshot?

As @micbar said, the sharing indicator for `people` should now be directly visible. The one for public links is still an open issue.

**Comment by kulmann** [comment] 2020-12-09 10:55
This ticket is partly fixed by https://github.com/cs3org/reva/pull/1329 and will be fixed by https://github.com/owncloud/ocis/issues/1038

**Comment by ScharfViktor** [comment] 2021-09-16 09:56
It's fixed. Re-tested with local server oCIS version 1.12.0 and web 4.2.0
I close it with https://github.com/owncloud/web/issues/4167

**Closed by ScharfViktor** 2021-09-16 09:56 UTC
Labels: Type:Bug, Category:Defect, Storage:EOS
