### ISSUE TITLE
File is not renamed for the share recipient

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6376] opened 2023-05-24 10:33 UTC
testing: 

ocis 3.0.0-rc.4
web 7.0.0-rc.37

during the fixing https://github.com/owncloud/ocis/issues/4796 we created another bug I think

#### fixed case:
- admin shares `foo.txt` and `f1/foo.txt` files to einstein
- einstein accepts files and they display as:`foo.txt` and `foo (1).txt` - correct

#### but it broke this case:  
- admin shares `test.txt` to einstein
- einstein accepts file
- admin renames `test.txt` to `renamed.txt`

Expect: einstein sees file as `renamed.txt`
Actual: file didn't renamed for einstein. 
einstein see file `test.txt` but cannot find file by `test` - because it is `renamed.txt`

https://github.com/owncloud/ocis/assets/84779829/4dd3f911-2897-48dd-b21b-0589f7d93acc

That's not all: 
- einstein shares `test.txt` to marie
![Screenshot 2023-05-24 at 12 26 59](https://github.com/owncloud/ocis/assets/84779829/00406dd0-c360-4c1a-8d4a-63b21b8447aa)

- marie sees file as `renamed.txt`

<img width="1168" alt="Screenshot 2023-05-24 at 12 28 12" src="https://github.com/owncloud/ocis/assets/84779829/1db17b8e-723d-4b93-bff2-af318c4bef5e">

**Comment by micbar** [comment] 2023-05-25 19:58
we need to discuss the expected behavior.

**Comment by butonic** [comment] 2023-05-26 08:12
IMO the search needs to index the mount point for shares independently from the shared resource. Those are two different resources that need to be indexed individually. We should not add the name of the mount point to the shared resource because we have to be able store a mountpoint for every recipient. Furthermore, the permissions for the shared resource are different and we may want to include them in search results.

I personally do not want a  share recipient to be able to change the name of my file. If we allow recipients to rename the shared resource we have to implement and handle the completely new error case of 'You cannot rename this file because the owner already has a resource with the same name in the parent folder of the file' ... hell it is even hard to come up with a good error message for this problem...

If we disallow renaming of incoming shares the share jail breaks because every resource needs to have a dedicated URL in WebDAV and a unique file name in hierarchical filesystems.

So, I don't think these are valid options an we need to fix search. And I would actually hitde the shared resource if the share was mounted.

**Comment by 2403905** [comment] 2023-05-31 13:25
After renaming einstein is able to find by new file name which is also an issue
![Screenshot 2023-05-31 at 15 11 33](https://github.com/owncloud/ocis/assets/11679989/3d505a89-c2b2-41b2-a585-d78ecf78b428)

**Comment by dragonchaser** [comment] 2023-06-28 14:42
@tbsbdr shouldn´t we also send a notification to the share recipient when the file is renamed? For example I have several dozen of shares, one gets renamed, that would make it easier to find the specific one again.

**Comment by micbar** [comment] 2023-06-28 16:51
> I'd expect that if someone has write permissions and renames the resource, the renamed filename is visible for everyone. (for conflicts it would need a (1) appended or alike ).

There are technical aspects which speak against that. @butonic FYI

**Comment by micbar** [comment] 2023-06-28 16:53
@tbsbdr I think we should leave it like it is. oc10 also shares that behavior.

Once the share was accepted by the recipient, it will not be affected by a rename on the owner side. This prevents "naming battles" because people tend to be very obsessed of naming and like to have it under their control.

**Comment by dragonchaser** [comment] 2023-08-11 09:37
So I assume we can close this?

**Comment by micbar** [comment] 2023-08-11 11:51
Correct.

**Closed by micbar** 2023-08-11 11:51 UTC
Labels: Type:Bug, Interaction:Discussion, Priority:p4-low
